/* BMI160 pin */
#define GPIO_PORT_BMI160_CS 		GPIOA
#define GPIO_PIN_BMI160_CS 			GPIO_PIN_4
#define GPIO_PORT_BMI160_INT0 		GPIOA
#define GPIO_PIN_BMI160_INT0 		GPIO_PIN_9
#define GPIO_PORT_BMI160_INT1 		GPIOA
#define GPIO_PIN_BMI160_INT1 		GPIO_PIN_10

/* power pin */
#define GPIO_PORT_POWER_IN 			GPIOA
#define GPIO_PIN_POWER_IN 			GPIO_PIN_8
#define GPIO_PORT_POWER_LANCH 		GPIOD
#define GPIO_PIN_POWER_LANCH		GPIO_PIN_2

/* usart pin */
#define GPIO_PORT_USART_TX 			GPIOA
#define GPIO_PIN_USART_TX 			GPIO_PIN_2
#define GPIO_PORT_USART_RX 			GPIOA
#define GPIO_PIN_USART_RX 			GPIO_PIN_3

/* usb pin */
#define GPIO_PORT_USB_DM 			GPIOA
#define GPIO_PIN_USB_DM 			GPIO_PIN_11
#define GPIO_PORT_USB_DP 			GPIOA
#define GPIO_PIN_USB_DP				GPIO_PIN_12

/* indicate led */
#define GPIO_PORT_SYS_STATUS_LED	GPIOA
#define GPIO_PIN_SYS_STATUS_LED		GPIO_PIN_15

/* 32 display led pin */
#define GPIO_PORT_LED_D00 			GPIOC
#define GPIO_PIN_LED_D00 			GPIO_PIN_0
#define GPIO_PORT_LED_D01 			GPIOC
#define GPIO_PIN_LED_D01 			GPIO_PIN_1
#define GPIO_PORT_LED_D02 			GPIOC
#define GPIO_PIN_LED_D02 			GPIO_PIN_2
#define GPIO_PORT_LED_D03 			GPIOC
#define GPIO_PIN_LED_D03 			GPIO_PIN_3
#define GPIO_PORT_LED_D04 			GPIOC
#define GPIO_PIN_LED_D04 			GPIO_PIN_4
#define GPIO_PORT_LED_D05 			GPIOC
#define GPIO_PIN_LED_D05 			GPIO_PIN_5
#define GPIO_PORT_LED_D06 			GPIOC
#define GPIO_PIN_LED_D06 			GPIO_PIN_6
#define GPIO_PORT_LED_D07 			GPIOC
#define GPIO_PIN_LED_D07 			GPIO_PIN_7
#define GPIO_PORT_LED_D08 			GPIOC
#define GPIO_PIN_LED_D08 			GPIO_PIN_8
#define GPIO_PORT_LED_D09 			GPIOC
#define GPIO_PIN_LED_D09 			GPIO_PIN_9
#define GPIO_PORT_LED_D10 			GPIOC
#define GPIO_PIN_LED_D10 			GPIO_PIN_10
#define GPIO_PORT_LED_D11 			GPIOC
#define GPIO_PIN_LED_D11 			GPIO_PIN_11
#define GPIO_PORT_LED_D12 			GPIOC
#define GPIO_PIN_LED_D12 			GPIO_PIN_12
#define GPIO_PORT_LED_D13 			GPIOC
#define GPIO_PIN_LED_D13 			GPIO_PIN_13
#define GPIO_PORT_LED_D14 			GPIOC
#define GPIO_PIN_LED_D14 			GPIO_PIN_14
#define GPIO_PORT_LED_D15 			GPIOC
#define GPIO_PIN_LED_D15 			GPIO_PIN_15

#define GPIO_PORT_LED_D16 			GPIOB
#define GPIO_PIN_LED_D16 			GPIO_PIN_0
#define GPIO_PORT_LED_D17 			GPIOB
#define GPIO_PIN_LED_D17 			GPIO_PIN_1
#define GPIO_PORT_LED_D18 			GPIOB
#define GPIO_PIN_LED_D18 			GPIO_PIN_2
#define GPIO_PORT_LED_D19 			GPIOA
#define GPIO_PIN_LED_D19 			GPIO_PIN_0
#define GPIO_PORT_LED_D20 			GPIOB
#define GPIO_PIN_LED_D20 			GPIO_PIN_4
#define GPIO_PORT_LED_D21 			GPIOB
#define GPIO_PIN_LED_D21 			GPIO_PIN_5
#define GPIO_PORT_LED_D22 			GPIOB
#define GPIO_PIN_LED_D22 			GPIO_PIN_6
#define GPIO_PORT_LED_D23 			GPIOB
#define GPIO_PIN_LED_D23 			GPIO_PIN_7
#define GPIO_PORT_LED_D24 			GPIOB
#define GPIO_PIN_LED_D24 			GPIO_PIN_8
#define GPIO_PORT_LED_D25 			GPIOB
#define GPIO_PIN_LED_D25 			GPIO_PIN_9
#define GPIO_PORT_LED_D26 			GPIOB
#define GPIO_PIN_LED_D26 			GPIO_PIN_10
#define GPIO_PORT_LED_D27 			GPIOA
#define GPIO_PIN_LED_D27 			GPIO_PIN_1
#define GPIO_PORT_LED_D28 			GPIOB
#define GPIO_PIN_LED_D28 			GPIO_PIN_12
#define GPIO_PORT_LED_D29 			GPIOB
#define GPIO_PIN_LED_D29 			GPIO_PIN_13
#define GPIO_PORT_LED_D30 			GPIOB
#define GPIO_PIN_LED_D30			GPIO_PIN_14
#define GPIO_PORT_LED_D31 			GPIOB
#define GPIO_PIN_LED_D31 			GPIO_PIN_15

void gpio_init(void);
void gpio_dump_status(void);
