nRF51822 Beacon Firmware Documentation: components/libraries/timer/app_timer_ble_gzll.c File Reference
app_timer_ble_gzll.c File Reference
#include "app_timer.h"
#include "app_util_platform.h"
#include <stdlib.h>
#include "nrf51.h"
#include "nrf51_bitfields.h"
#include "nrf_soc.h"
#include "nrf_assert.h"
#include "nrf_delay.h"
#include "app_util.h"
Data Structures
struct timer_node_t
Timer node type. The nodes will be used form a linked list of running timers.
struct timer_user_op_start_t
Structure describing a timer start operation.
struct timer_user_op_t
Structure describing a timer operation.
struct timer_user_t
Structure describing a timer user.
Macros
#define RTC1_IRQ_PRI APP_IRQ_PRIORITY_LOW
#define SWI1_IRQ_PRI APP_IRQ_PRIORITY_LOW
#define MAX_RTC_CNT 0x00FFFFFF
#define APP_HIGH_USER_ID 0
#define APP_LOW_USER_ID 1
#define THREAD_MODE_USER_ID 2
#define RTC_COMPARE_OFFSET_MIN 3
#define MAX_RTC_TASKS_DELAY 47
#define TIMER_NULL ((app_timer_id_t)(0 - 1))
#define CONTEXT_QUEUE_SIZE_MAX (2)
Typedefs
typedef uint32_t timer_user_id_t
User id type.
Enumerations
enum timer_alloc_state_t { STATE_FREE, STATE_ALLOCATED, STATE_FREE, STATE_ALLOCATED }
Timer accodation state type.
enum timer_user_op_type_t {
TIMER_USER_OP_TYPE_NONE, TIMER_USER_OP_TYPE_START, TIMER_USER_OP_TYPE_STOP, TIMER_USER_OP_TYPE_STOP_ALL,
TIMER_USER_OP_TYPE_NONE, TIMER_USER_OP_TYPE_START, TIMER_USER_OP_TYPE_STOP, TIMER_USER_OP_TYPE_STOP_ALL
}
Set of available timer operation types.
Functions
STATIC_ASSERT (RTC1_IRQ_PRI==SWI1_IRQ_PRI)
STATIC_ASSERT (sizeof(timer_node_t)<=APP_TIMER_NODE_SIZE)
STATIC_ASSERT (sizeof(timer_node_t)%4==0)
STATIC_ASSERT (sizeof(timer_user_op_t)<=APP_TIMER_USER_OP_SIZE)
STATIC_ASSERT (sizeof(timer_user_op_t)%4==0)
STATIC_ASSERT (sizeof(timer_user_t)==APP_TIMER_USER_SIZE)
STATIC_ASSERT (sizeof(timer_user_t)%4==0)
static void rtc1_init (uint32_t prescaler)
Function for initializing and starting the RTC1 counter.
static void rtc1_start (void)
Function for starting the RTC1 timer.
static void rtc1_stop (void)
Function for stopping the RTC1 timer.
static __INLINE uint32_t rtc1_counter_get (void)
Function for returning the current value of the RTC1 counter.
static __INLINE uint32_t ticks_diff_get (uint32_t ticks_now, uint32_t ticks_old)
Function for computing the difference between two RTC1 counter values.
static __INLINE void rtc1_compare0_set (uint32_t value)
Function for setting the RTC1 Capture Compare register 0, and enabling the corresponding event.
static void timer_list_insert (app_timer_id_t timer_id)
Function for inserting a timer in the timer list.
static void timer_list_remove (app_timer_id_t timer_id)
Function for removing a timer from the timer queue.
static void timer_timeouts_check_sched (void)
Function for scheduling a check for timeouts by generating a RTC1 interrupt.
static void timer_list_handler_sched (void)
Function for scheduling a timer list update by generating a SWI0 interrupt.
static void timeout_handler_exec (timer_node_t *p_timer)
Function for executing an application timeout handler, either by calling it directly, or by passing an event to the Scheduler.
static void timer_timeouts_check (void)
Function for checking for expired timers.
static bool elapsed_ticks_acquire (uint32_t *p_ticks_elapsed)
Function for acquiring the number of ticks elapsed.
static bool list_deletions_handler (void)
Function for handling the timer list deletions.
static void expired_timers_handler (uint32_t ticks_elapsed, uint32_t ticks_previous, app_timer_id_t *p_restart_list_head)
Function for updating the timer list for expired timers.
static bool list_insertions_handler (app_timer_id_t restart_list_head)
Function for handling timer list insertions.
static void compare_reg_update (app_timer_id_t timer_id_head_old)
Function for updating the Capture Compare register.
static void timer_list_handler (void)
Function for handling changes to the timer list.
static timer_user_op_t * user_op_alloc (timer_user_t *p_user)
Function for allocating a new operations queue entry.
static uint32_t timer_start_op_schedule (timer_user_id_t user_id, app_timer_id_t timer_id, uint32_t timeout_initial, uint32_t timeout_periodic, void *p_context)
Function for scheduling a Timer Start operation.
static uint32_t timer_stop_op_schedule (timer_user_id_t user_id, app_timer_id_t timer_id)
Function for scheduling a Timer Stop operation.
static uint32_t timer_stop_all_op_schedule (timer_user_id_t user_id)
Function for scheduling a Timer Stop All operation.
void RTC1_IRQHandler (void)
Function for handling the RTC1 interrupt.
void SWI1_IRQHandler (void)
Function for handling the SWI0 interrupt.
uint32_t app_timer_init (uint32_t prescaler, uint8_t max_timers, uint8_t op_queues_size, void *p_buffer, app_timer_evt_schedule_func_t evt_schedule_func)
Function for initializing the timer module.
uint32_t app_timer_create (app_timer_id_t *p_timer_id, app_timer_mode_t mode, app_timer_timeout_handler_t timeout_handler)
Function for creating a timer instance.
static timer_user_id_t user_id_get (void)
Function for creating a timer user id from the current interrupt level.
uint32_t app_timer_start (app_timer_id_t timer_id, uint32_t timeout_ticks, void *p_context)
Function for starting a timer.
uint32_t app_timer_stop (app_timer_id_t timer_id)
Function for stopping the specified timer.
uint32_t app_timer_stop_all (void)
Function for stopping all running timers.
uint32_t app_timer_cnt_get (uint32_t *p_ticks)
Function for returning the current value of the RTC1 counter.
uint32_t app_timer_cnt_diff_compute (uint32_t ticks_to, uint32_t ticks_from, uint32_t *p_ticks_diff)
Function for computing the difference between two RTC1 counter values.
Variables
static uint8_t m_node_array_size
static timer_node_t * mp_nodes = NULL
static uint8_t m_user_array_size
static timer_user_t * mp_users
static app_timer_id_t m_timer_id_head
static uint32_t m_ticks_latest
static uint32_t m_ticks_elapsed [CONTEXT_QUEUE_SIZE_MAX]
static uint8_t m_ticks_elapsed_first
static uint8_t m_ticks_elapsed_last
static
app_timer_evt_schedule_func_t m_evt_schedule_func
Macro Definition Documentation
#define RTC1_IRQ_PRI APP_IRQ_PRIORITY_LOW
Priority of the RTC1 interrupt (used for checking for timeouts and executing timeout handlers).
Definition at line 23 of file app_timer_ble_gzll.c.
#define SWI1_IRQ_PRI APP_IRQ_PRIORITY_LOW
Priority of the SWI0 interrupt (used for updating the timer list).
Definition at line 24 of file app_timer_ble_gzll.c.
#define MAX_RTC_CNT 0x00FFFFFF
Maximum value of the RTC counter.
Definition at line 31 of file app_timer_ble_gzll.c.
#define APP_HIGH_USER_ID 0
User Id for the Application High "user".
Definition at line 33 of file app_timer_ble_gzll.c.
#define APP_LOW_USER_ID 1
User Id for the Application Low "user".
Definition at line 34 of file app_timer_ble_gzll.c.
#define THREAD_MODE_USER_ID 2
User Id for the Thread Mode "user".
Definition at line 35 of file app_timer_ble_gzll.c.
#define RTC_COMPARE_OFFSET_MIN 3
Minimum offset between the current RTC counter value and the Capture Compare register.
Definition at line 37 of file app_timer_ble_gzll.c.
#define MAX_RTC_TASKS_DELAY 47
Maximum delay until an RTC task is executed.
Definition at line 38 of file app_timer_ble_gzll.c.
#define TIMER_NULL ((app_timer_id_t)(0 - 1))
Invalid timer id.
Definition at line 125 of file app_timer_ble_gzll.c.
#define CONTEXT_QUEUE_SIZE_MAX (2)
Timer internal elapsed ticks queue size.
Definition at line 126 of file app_timer_ble_gzll.c.
Typedef Documentation
typedef uint32_t timer_user_id_t
User id type.
In the current implementation, this will automatically be generated from the current interrupt level.
Definition at line 123 of file app_timer_ble_gzll.c.
Enumeration Type Documentation
enum timer_alloc_state_t
Timer accodation state type.
Enumerator
STATE_FREE
The timer node is available.
STATE_ALLOCATED
The timer node has been allocated.
STATE_FREE
The timer node is available.
STATE_ALLOCATED
The timer node has been allocated.
Definition at line 41 of file app_timer_ble_gzll.c.
 {
     STATE_FREE,
     STATE_ALLOCATED
 } timer_alloc_state_t;
enum timer_user_op_type_t
Set of available timer operation types.
Enumerator
TIMER_USER_OP_TYPE_NONE
Invalid timer operation type.
TIMER_USER_OP_TYPE_START
Timer operation type Start.
TIMER_USER_OP_TYPE_STOP
Timer operation type Stop.
TIMER_USER_OP_TYPE_STOP_ALL
Timer operation type Stop All.
TIMER_USER_OP_TYPE_NONE
Invalid timer operation type.
TIMER_USER_OP_TYPE_START
Timer operation type Start.
TIMER_USER_OP_TYPE_STOP
Timer operation type Stop.
TIMER_USER_OP_TYPE_STOP_ALL
Timer operation type Stop All.
Definition at line 66 of file app_timer_ble_gzll.c.
 {
     TIMER_USER_OP_TYPE_NONE,
     TIMER_USER_OP_TYPE_START,
     TIMER_USER_OP_TYPE_STOP,
     TIMER_USER_OP_TYPE_STOP_ALL
 } timer_user_op_type_t;
Function Documentation
STATIC_ASSERT (RTC1_IRQ_PRI = =SWI1_IRQ_PRI)
STATIC_ASSERT (sizeof(timer_node_t)<= APP_TIMER_NODE_SIZE)
STATIC_ASSERT (sizeof(timer_node_t)% 4 = =0)
STATIC_ASSERT (sizeof(timer_user_op_t)<= APP_TIMER_USER_OP_SIZE)
STATIC_ASSERT (sizeof(timer_user_op_t)% 4 = =0)
STATIC_ASSERT (sizeof(timer_user_t) = =APP_TIMER_USER_SIZE)
STATIC_ASSERT (sizeof(timer_user_t)% 4 = =0)
static void rtc1_init (uint32_t prescaler) static
Function for initializing and starting the RTC1 counter.
Parameters
[in] prescaler Value of the RTC1 prescale register. Set to 0 for no prescaling.
Definition at line 144 of file app_timer_ble_gzll.c.
References NRF_RTC1, RTC1_IRQ_PRI, and RTC1_IRQn.
 {
     NRF_RTC1->PRESCALER = prescaler;
     NVIC_SetPriority(RTC1_IRQn, RTC1_IRQ_PRI);
 }
static void rtc1_start (void) static
Function for starting the RTC1 timer.
Definition at line 153 of file app_timer_ble_gzll.c.
References MAX_RTC_TASKS_DELAY, NRF_RTC1, RTC1_IRQn, RTC_EVTEN_COMPARE0_Msk, and RTC_INTENSET_COMPARE0_Msk.
 {
     NRF_RTC1->EVTENSET = RTC_EVTEN_COMPARE0_Msk;
     NRF_RTC1->INTENSET = RTC_INTENSET_COMPARE0_Msk;
     NVIC_ClearPendingIRQ(RTC1_IRQn);
     NVIC_EnableIRQ(RTC1_IRQn);
     NRF_RTC1->TASKS_START = 1;
     nrf_delay_us(MAX_RTC_TASKS_DELAY);
 }
static void rtc1_stop (void) static
Function for stopping the RTC1 timer.
Definition at line 168 of file app_timer_ble_gzll.c.
References MAX_RTC_TASKS_DELAY, NRF_RTC1, RTC1_IRQn, RTC_EVTEN_COMPARE0_Msk, and RTC_INTENSET_COMPARE0_Msk.
 {
     NVIC_DisableIRQ(RTC1_IRQn);
     NRF_RTC1->EVTENCLR = RTC_EVTEN_COMPARE0_Msk;
     NRF_RTC1->INTENCLR = RTC_INTENSET_COMPARE0_Msk;
     NRF_RTC1->TASKS_STOP = 1;
     nrf_delay_us(MAX_RTC_TASKS_DELAY);
 }
static __INLINE uint32_t rtc1_counter_get (void) static
Function for returning the current value of the RTC1 counter.
Returns
Current value of the RTC1 counter.
Definition at line 184 of file app_timer_ble_gzll.c.
References NRF_RTC1.
 {
     return NRF_RTC1->COUNTER;
 }
static __INLINE uint32_t ticks_diff_get (uint32_t ticks_now, uint32_t ticks_old) static
Function for computing the difference between two RTC1 counter values.
Returns
Number of ticks elapsed from ticks_old to ticks_now.
Definition at line 194 of file app_timer_ble_gzll.c.
References MAX_RTC_CNT.
 {
     if (ticks_now >= ticks_old)
     {
         return (ticks_now - ticks_old);
     }
     else
     {
         return (MAX_RTC_CNT + 1) - (ticks_old - ticks_now);
     }
 }
static __INLINE void rtc1_compare0_set (uint32_t value) static
Function for setting the RTC1 Capture Compare register 0, and enabling the corresponding event.
Parameters
[in] value New value of Capture Compare register 0.
Definition at line 211 of file app_timer_ble_gzll.c.
References NRF_RTC1.
 {
     NRF_RTC1->CC[0] = value;
 }
static void timer_list_insert (app_timer_id_t timer_id) static
Function for inserting a timer in the timer list.
Parameters
[in] timer_id Id of timer to insert.
Definition at line 221 of file app_timer_ble_gzll.c.
References m_timer_id_head, mp_nodes, timer_node_t::next, timer_node_t::ticks_to_expire, and TIMER_NULL.
 {
     timer_node_t * p_timer = &mp_nodes[timer_id];
     if (m_timer_id_head == TIMER_NULL)
     {
         m_timer_id_head = timer_id;
     }
     else
     {
         if (p_timer->ticks_to_expire <= mp_nodes[m_timer_id_head].ticks_to_expire)
         {
             mp_nodes[m_timer_id_head].ticks_to_expire -= p_timer->ticks_to_expire;
             p_timer->next   = m_timer_id_head;
             m_timer_id_head = timer_id;
         }
         else
         {
             app_timer_id_t previous;
             app_timer_id_t current;
             uint32_t       ticks_to_expire;
             ticks_to_expire = p_timer->ticks_to_expire;
             previous        = m_timer_id_head;
             current         = m_timer_id_head;
             while ((current != TIMER_NULL) && (ticks_to_expire > mp_nodes[current].ticks_to_expire))
             {
                 ticks_to_expire -= mp_nodes[current].ticks_to_expire;
                 previous         = current;
                 current          = mp_nodes[current].next;
             }
             if (current != TIMER_NULL)
             {
                 mp_nodes[current].ticks_to_expire -= ticks_to_expire;
             }
             p_timer->ticks_to_expire = ticks_to_expire;
             p_timer->next            = current;
             mp_nodes[previous].next  = timer_id;
         }
     }
 }
static void timer_list_remove (app_timer_id_t timer_id) static
Function for removing a timer from the timer queue.
Parameters
[in] timer_id Id of timer to remove.
Definition at line 272 of file app_timer_ble_gzll.c.
References m_timer_id_head, mp_nodes, timer_node_t::next, timer_node_t::ticks_to_expire, and TIMER_NULL.
 {
     app_timer_id_t previous;
     app_timer_id_t current;
     uint32_t       timeout;
     // Find the timer's position in timer list.
     previous = m_timer_id_head;
     current  = previous;
     while (current != TIMER_NULL)
     {
         if (current == timer_id)
         {
             break;
         }
         previous = current;
         current  = mp_nodes[current].next;
     }
     // Timer not in active list.
     if (current == TIMER_NULL)
     {
         return;
     }
     // Timer is the first in the list.
     if (previous == current)
     {
         m_timer_id_head = mp_nodes[m_timer_id_head].next;
     }
     // Remaining timeout between next timeout.
     timeout = mp_nodes[current].ticks_to_expire;
     // Link previous timer with next of this timer, i.e. removing the timer from list.
     mp_nodes[previous].next = mp_nodes[current].next;
     // If this is not the last timer, increment the next timer by this timer timeout.
     current = mp_nodes[previous].next;
     if (current != TIMER_NULL)
     {
         mp_nodes[current].ticks_to_expire += timeout;
     }
 }
static void timer_timeouts_check_sched (void) static
Function for scheduling a check for timeouts by generating a RTC1 interrupt.
Definition at line 321 of file app_timer_ble_gzll.c.
References RTC1_IRQn.
 {
     NVIC_SetPendingIRQ(RTC1_IRQn);
 }
static void timer_list_handler_sched (void) static
Function for scheduling a timer list update by generating a SWI0 interrupt.
Definition at line 329 of file app_timer_ble_gzll.c.
References SWI1_IRQn.
 {
     NVIC_SetPendingIRQ(SWI1_IRQn);
 }
static void timeout_handler_exec (timer_node_t * p_timer) static
Function for executing an application timeout handler, either by calling it directly, or by passing an event to the Scheduler.
Parameters
[in] p_timer Pointer to expired timer.
Definition at line 340 of file app_timer_ble_gzll.c.
References ASSERT, m_evt_schedule_func, NRF_SUCCESS, timer_node_t::p_context, and timer_node_t::p_timeout_handler.
 {
     if (m_evt_schedule_func != NULL)
     {
         uint32_t err_code = m_evt_schedule_func(p_timer->p_timeout_handler, p_timer->p_context);
         if (err_code != NRF_SUCCESS)
         {
             ASSERT(false);
         }
     }
     else
     {
         p_timer->p_timeout_handler(p_timer->p_context);
     }
 }
static void timer_timeouts_check (void) static
Function for checking for expired timers.
Definition at line 359 of file app_timer_ble_gzll.c.
References CONTEXT_QUEUE_SIZE_MAX, m_ticks_elapsed, m_ticks_elapsed_first, m_ticks_elapsed_last, m_ticks_latest, m_timer_id_head, mp_nodes, timer_node_t::next, rtc1_counter_get(), ticks_diff_get(), timer_node_t::ticks_to_expire, timeout_handler_exec(), timer_list_handler_sched(), and TIMER_NULL.
 {
     // Handle expired of timer.
     if (m_timer_id_head != TIMER_NULL)
     {
         uint32_t ticks_expired;
         uint8_t  ticks_elapsed_last;
         // Initialize actual elapsed ticks being consumed to 0.
         ticks_expired = 0;
         // Queue the ticks elapsed (to make the value context safe).
         ticks_elapsed_last = m_ticks_elapsed_last + 1;
         if (ticks_elapsed_last == CONTEXT_QUEUE_SIZE_MAX)
         {
             ticks_elapsed_last = 0;
         }
         if (ticks_elapsed_last != m_ticks_elapsed_first)
         {
             app_timer_id_t timer_id;
             uint32_t       ticks_elapsed;
             // Ticks_elapsed is collected here, job will use it.
             ticks_elapsed = ticks_diff_get(rtc1_counter_get(), m_ticks_latest);
             // Auto variable containing the head of timers expiring.
             timer_id = m_timer_id_head;
             // Expire all timers within ticks_elapsed and collect ticks_expired.
             while (timer_id != TIMER_NULL)
             {
                 timer_node_t * p_timer;
                 // Auto variable for current timer node.
                 p_timer = &mp_nodes[timer_id];
                 // Do nothing if timer did not expire.
                 if (ticks_elapsed < p_timer->ticks_to_expire)
                 {
                     break;
                 }
                 // Decrement ticks_elapsed and collect expired ticks
                 ticks_elapsed -= p_timer->ticks_to_expire;
                 ticks_expired += p_timer->ticks_to_expire;
                 // Move to next timer
                 timer_id = p_timer->next;
                 // Execute Task
                 timeout_handler_exec(p_timer);
             }
         }
         // Queue the elapsed value
         m_ticks_elapsed[m_ticks_elapsed_last] = ticks_expired;
         m_ticks_elapsed_last                  = ticks_elapsed_last;
         timer_list_handler_sched();
     }
 }
static bool elapsed_ticks_acquire (uint32_t * p_ticks_elapsed) static
Function for acquiring the number of ticks elapsed.
Parameters
[out] p_ticks_elapsed Number of ticks elapsed.
Returns
TRUE if elapsed ticks was read from queue, FALSE otherwise.
Definition at line 429 of file app_timer_ble_gzll.c.
References CONTEXT_QUEUE_SIZE_MAX, m_ticks_elapsed, m_ticks_elapsed_first, m_ticks_elapsed_last, m_ticks_latest, and MAX_RTC_CNT.
 {
     // Pick the elapsed value from queue
     if (m_ticks_elapsed_first != m_ticks_elapsed_last)
     {
         *p_ticks_elapsed = m_ticks_elapsed[m_ticks_elapsed_first];
         // Dequeue elapsed value.
         m_ticks_elapsed_first++;
         if (m_ticks_elapsed_first == CONTEXT_QUEUE_SIZE_MAX)
         {
             m_ticks_elapsed_first = 0;
         }
         m_ticks_latest += *p_ticks_elapsed;
         m_ticks_latest &= MAX_RTC_CNT;
         return true;
     }
     else
     {
         // No elapsed value in queue.
         *p_ticks_elapsed = 0;
         return false;
     }
 }
static bool list_deletions_handler (void) static
Function for handling the timer list deletions.
Returns
TRUE if Capture Compare register must be updated, FALSE otherwise.
Definition at line 461 of file app_timer_ble_gzll.c.
References timer_user_t::first, timer_node_t::is_running, timer_user_t::last, m_timer_id_head, m_user_array_size, mp_nodes, mp_users, timer_node_t::next, timer_user_op_t::op_type, timer_user_t::p_user_op_queue, timer_user_op_t::timer_id, timer_list_remove(), TIMER_NULL, TIMER_USER_OP_TYPE_STOP, TIMER_USER_OP_TYPE_STOP_ALL, and timer_user_t::user_op_queue_size.
 {
     app_timer_id_t timer_id_old_head;
     uint8_t        user_id;
     // Remember the old head, so as to decide if new compare needs to be set.
     timer_id_old_head = m_timer_id_head;
     user_id = m_user_array_size;
     while (user_id--)
     {
         timer_user_t * p_user         = &mp_users[user_id];
         uint8_t        user_ops_first = p_user->first;
         while (user_ops_first != p_user->last)
         {
             timer_node_t *    p_timer;
             timer_user_op_t * p_user_op = &p_user->p_user_op_queue[user_ops_first];
             // Traverse to next operation in queue
             user_ops_first++;
             if (user_ops_first == p_user->user_op_queue_size)
             {
                 user_ops_first = 0;
             }
             switch (p_user_op->op_type)
             {
                 case TIMER_USER_OP_TYPE_STOP:
                     // Delete node if timer is running.
                     p_timer = &mp_nodes[p_user_op->timer_id];
                     if (p_timer->is_running)
                     {
                         timer_list_remove(p_user_op->timer_id);
                         p_timer->is_running = false;
                     }
                     break;
                 case TIMER_USER_OP_TYPE_STOP_ALL:
                     // Delete list of running timers, and mark all timers as not running.
                     while (m_timer_id_head != TIMER_NULL)
                     {
                         timer_node_t * p_head = &mp_nodes[m_timer_id_head];
                         p_head->is_running = false;
                         m_timer_id_head    = p_head->next;
                     }
                     break;
                 default:
                     // No implementation needed.
                     break;
             }
         }
     }
     // Detect change in head of the list.
     return (m_timer_id_head != timer_id_old_head);
 }
static void expired_timers_handler (uint32_t ticks_elapsed, uint32_t ticks_previous, app_timer_id_t * p_restart_list_head) static
Function for updating the timer list for expired timers.
Parameters
[in] ticks_elapsed Number of elapsed ticks.
[in] ticks_previous Previous known value of the RTC counter.
[out] p_restart_list_head List of repeating timers to be restarted.
Definition at line 528 of file app_timer_ble_gzll.c.
References timer_node_t::is_running, m_timer_id_head, MAX_RTC_CNT, mp_nodes, timer_node_t::next, timer_node_t::ticks_at_start, timer_node_t::ticks_first_interval, timer_node_t::ticks_periodic_interval, timer_node_t::ticks_to_expire, and TIMER_NULL.
 {
     uint32_t ticks_expired = 0;
     while (m_timer_id_head != TIMER_NULL)
     {
         timer_node_t * p_timer;
         app_timer_id_t id_expired;
         // Auto variable for current timer node.
         p_timer = &mp_nodes[m_timer_id_head];
         // Do nothing if timer did not expire.
         if (ticks_elapsed < p_timer->ticks_to_expire)
         {
             p_timer->ticks_to_expire -= ticks_elapsed;
             break;
         }
         // Decrement ticks_elapsed and collect expired ticks.
         ticks_elapsed -= p_timer->ticks_to_expire;
         ticks_expired += p_timer->ticks_to_expire;
         // Timer expired, set ticks_to_expire zero.
         p_timer->ticks_to_expire = 0;
         p_timer->is_running      = false;
         // Remove the expired timer from head.
         id_expired      = m_timer_id_head;
         m_timer_id_head = p_timer->next;
         // Timer will be restarted if periodic.
         if (p_timer->ticks_periodic_interval != 0)
         {
             p_timer->ticks_at_start       = (ticks_previous + ticks_expired) & MAX_RTC_CNT;
             p_timer->ticks_first_interval = p_timer->ticks_periodic_interval;
             p_timer->next                 = *p_restart_list_head;
             *p_restart_list_head          = id_expired;
         }
     }
 }
static bool list_insertions_handler (app_timer_id_t restart_list_head) static
Function for handling timer list insertions.
Parameters
[in] p_restart_list_head List of repeating timers to be restarted.
Returns
TRUE if Capture Compare register must be updated, FALSE otherwise.
Definition at line 579 of file app_timer_ble_gzll.c.
References timer_user_t::first, timer_node_t::is_running, timer_user_t::last, m_ticks_latest, m_timer_id_head, m_user_array_size, MAX_RTC_CNT, mp_nodes, mp_users, timer_node_t::next, timer_user_op_t::op_type, timer_node_t::p_context, timer_user_op_start_t::p_context, timer_user_t::p_user_op_queue, timer_user_op_t::params, timer_user_op_t::start, timer_node_t::ticks_at_start, timer_user_op_start_t::ticks_at_start, ticks_diff_get(), timer_node_t::ticks_first_interval, timer_user_op_start_t::ticks_first_interval, timer_node_t::ticks_periodic_interval, timer_user_op_start_t::ticks_periodic_interval, timer_node_t::ticks_to_expire, timer_user_op_t::timer_id, timer_list_insert(), TIMER_NULL, TIMER_USER_OP_TYPE_START, and timer_user_t::user_op_queue_size.
 {
     app_timer_id_t timer_id_old_head;
     uint8_t        user_id;
     // Remember the old head, so as to decide if new compare needs to be set.
     timer_id_old_head = m_timer_id_head;
     user_id = m_user_array_size;
     while (user_id--)
     {
         timer_user_t * p_user = &mp_users[user_id];
         // Handle insertions of timers.
         while ((restart_list_head != TIMER_NULL) || (p_user->first != p_user->last))
         {
             app_timer_id_t id_start;
             timer_node_t * p_timer;
             if (restart_list_head != TIMER_NULL)
             {
                 id_start          = restart_list_head;
                 p_timer           = &mp_nodes[id_start];
                 restart_list_head = p_timer->next;
             }
             else
             {
                 timer_user_op_t * p_user_op = &p_user->p_user_op_queue[p_user->first];
                 p_user->first++;
                 if (p_user->first == p_user->user_op_queue_size)
                 {
                     p_user->first = 0;
                 }
                 id_start = p_user_op->timer_id;
                 p_timer  = &mp_nodes[id_start];
                 if ((p_user_op->op_type != TIMER_USER_OP_TYPE_START) || p_timer->is_running)
                 {
                     continue;
                 }
                 p_timer->ticks_at_start          = p_user_op->params.start.ticks_at_start;
                 p_timer->ticks_first_interval    = p_user_op->params.start.ticks_first_interval;
                 p_timer->ticks_periodic_interval = p_user_op->params.start.ticks_periodic_interval;
                 p_timer->p_context               = p_user_op->params.start.p_context;
             }
             // Prepare the node to be inserted.
             if (((p_timer->ticks_at_start - m_ticks_latest) & MAX_RTC_CNT) < (MAX_RTC_CNT / 2))
             {
                 p_timer->ticks_to_expire = ticks_diff_get(p_timer->ticks_at_start, m_ticks_latest) +
                                            p_timer->ticks_first_interval;
             }
             else
             {
                 uint32_t delta_current_start;
                 delta_current_start = ticks_diff_get(m_ticks_latest, p_timer->ticks_at_start);
                 if (p_timer->ticks_first_interval > delta_current_start)
                 {
                     p_timer->ticks_to_expire = p_timer->ticks_first_interval - delta_current_start;
                 }
                 else
                 {
                     p_timer->ticks_to_expire = 0;
                 }
             }
             p_timer->ticks_at_start       = 0;
             p_timer->ticks_first_interval = 0;
             p_timer->is_running           = true;
             p_timer->next                 = TIMER_NULL;
             // Insert into list.
             timer_list_insert(id_start);
         }
     }
     return (m_timer_id_head != timer_id_old_head);
 }
static void compare_reg_update (app_timer_id_t timer_id_head_old) static
Function for updating the Capture Compare register.
Definition at line 664 of file app_timer_ble_gzll.c.
References m_ticks_latest, m_timer_id_head, MAX_RTC_CNT, mp_nodes, rtc1_compare0_set(), rtc1_counter_get(), rtc1_start(), rtc1_stop(), RTC_COMPARE_OFFSET_MIN, ticks_diff_get(), timer_node_t::ticks_to_expire, TIMER_NULL, and timer_timeouts_check_sched().
 {
     // Setup the timeout for timers on the head of the list.
     if (m_timer_id_head != TIMER_NULL)
     {
         uint32_t ticks_to_expire = mp_nodes[m_timer_id_head].ticks_to_expire;
         uint32_t counter         = rtc1_counter_get();
         uint32_t cc              = m_ticks_latest;
         uint32_t ticks_elapsed   = ticks_diff_get(counter, cc) + RTC_COMPARE_OFFSET_MIN;
         if (timer_id_head_old == TIMER_NULL)
         {
             // No timers were already running, start RTC.
             rtc1_start();
         }
         cc += (ticks_elapsed < ticks_to_expire) ? ticks_to_expire : ticks_elapsed;
         cc &= MAX_RTC_CNT;
         rtc1_compare0_set(cc);
         if (ticks_diff_get(rtc1_counter_get(), counter) > ticks_diff_get(cc, counter))
         {
             timer_timeouts_check_sched();
         }
     }
     else
     {
         // No timers are running, stop RTC.
         rtc1_stop();
     }
 }
static void timer_list_handler (void) static
Function for handling changes to the timer list.
Definition at line 700 of file app_timer_ble_gzll.c.
References compare_reg_update(), elapsed_ticks_acquire(), expired_timers_handler(), list_deletions_handler(), list_insertions_handler(), m_ticks_latest, m_timer_id_head, and TIMER_NULL.
 {
     app_timer_id_t restart_list_head = TIMER_NULL;
     uint32_t       ticks_elapsed;
     uint32_t       ticks_previous;
     bool           ticks_have_elapsed;
     bool           compare_update;
     app_timer_id_t timer_id_head_old;
     // Back up the previous known tick and previous list head.
     ticks_previous    = m_ticks_latest;
     timer_id_head_old = m_timer_id_head;
     // Get number of elapsed ticks.
     ticks_have_elapsed = elapsed_ticks_acquire(&ticks_elapsed);
     // Handle list deletions.
     compare_update = list_deletions_handler();
     // Handle expired timers.
     if (ticks_have_elapsed)
     {
         expired_timers_handler(ticks_elapsed, ticks_previous, &restart_list_head);
         compare_update = true;
     }
     // Handle list insertions.
     if (list_insertions_handler(restart_list_head))
     {
         compare_update = true;
     }
     // Update compare register if necessary.
     if (compare_update)
     {
         compare_reg_update(timer_id_head_old);
     }
 }
static timer_user_op_t* user_op_alloc (timer_user_t * p_user) static
Function for allocating a new operations queue entry.
Parameters
[in] p_user User that the entry is to be allocated for.
Returns
Pointer to allocated queue entry, or NULL if queue is full.
Definition at line 746 of file app_timer_ble_gzll.c.
References timer_user_t::first, timer_user_t::last, timer_user_t::p_user_op_queue, and timer_user_t::user_op_queue_size.
 {
     app_timer_id_t    last;
     timer_user_op_t * p_user_op;
     last = p_user->last + 1;
     if (last == p_user->user_op_queue_size)
     {
         last = 0;
     }
     if (last == p_user->first)
     {
         return NULL;
     }
     p_user_op    = &p_user->p_user_op_queue[p_user->last];
     p_user->last = last;
     return p_user_op;
 }
static uint32_t timer_start_op_schedule (timer_user_id_t user_id, app_timer_id_t timer_id, uint32_t timeout_initial, uint32_t timeout_periodic, void * p_context) static
Function for scheduling a Timer Start operation.
Parameters
[in] user_id Id of user calling this function.
[in] timer_id Id of timer to start.
[in] timeout_initial Time (in ticks) to first timer expiry.
[in] timeout_periodic Time (in ticks) between periodic expiries.
[in] p_context General purpose pointer. Will be passed to the timeout handler when the timer expires.
Returns
NRF_SUCCESS on success, otherwise an error code.
Definition at line 778 of file app_timer_ble_gzll.c.
References mp_users, NRF_ERROR_NO_MEM, NRF_SUCCESS, timer_user_op_t::op_type, timer_user_op_start_t::p_context, timer_user_op_t::params, rtc1_counter_get(), timer_user_op_t::start, timer_user_op_start_t::ticks_at_start, timer_user_op_start_t::ticks_first_interval, timer_user_op_start_t::ticks_periodic_interval, timer_user_op_t::timer_id, timer_list_handler_sched(), TIMER_USER_OP_TYPE_START, and user_op_alloc().
 {
     timer_user_op_t * p_user_op = user_op_alloc(&mp_users[user_id]);
     if (p_user_op == NULL)
     {
         return NRF_ERROR_NO_MEM;
     }
     p_user_op->op_type                              = TIMER_USER_OP_TYPE_START;
     p_user_op->timer_id                             = timer_id;
     p_user_op->params.start.ticks_at_start          = rtc1_counter_get();
     p_user_op->params.start.ticks_first_interval    = timeout_initial;
     p_user_op->params.start.ticks_periodic_interval = timeout_periodic;
     p_user_op->params.start.p_context               = p_context;
     timer_list_handler_sched();
     return NRF_SUCCESS;
 }
static uint32_t timer_stop_op_schedule (timer_user_id_t user_id, app_timer_id_t timer_id) static
Function for scheduling a Timer Stop operation.
Parameters
[in] user_id Id of user calling this function.
[in] timer_id Id of timer to stop.
Definition at line 808 of file app_timer_ble_gzll.c.
References mp_users, NRF_ERROR_NO_MEM, NRF_SUCCESS, timer_user_op_t::op_type, timer_user_op_t::timer_id, timer_list_handler_sched(), TIMER_USER_OP_TYPE_STOP, and user_op_alloc().
 {
     timer_user_op_t * p_user_op = user_op_alloc(&mp_users[user_id]);
     if (p_user_op == NULL)
     {
         return NRF_ERROR_NO_MEM;
     }
     p_user_op->op_type  = TIMER_USER_OP_TYPE_STOP;
     p_user_op->timer_id = timer_id;
     timer_list_handler_sched();
     return NRF_SUCCESS;
 }
static uint32_t timer_stop_all_op_schedule (timer_user_id_t user_id) static
Function for scheduling a Timer Stop All operation.
Parameters
[in] user_id Id of user calling this function.
Definition at line 829 of file app_timer_ble_gzll.c.
References mp_users, NRF_ERROR_NO_MEM, NRF_SUCCESS, timer_user_op_t::op_type, timer_user_op_t::timer_id, timer_list_handler_sched(), TIMER_NULL, TIMER_USER_OP_TYPE_STOP_ALL, and user_op_alloc().
 {
     timer_user_op_t * p_user_op = user_op_alloc(&mp_users[user_id]);
     if (p_user_op == NULL)
     {
         return NRF_ERROR_NO_MEM;
     }
     p_user_op->op_type  = TIMER_USER_OP_TYPE_STOP_ALL;
     p_user_op->timer_id = TIMER_NULL;
     timer_list_handler_sched();
     return NRF_SUCCESS;
 }
void RTC1_IRQHandler (void)
Function for handling the RTC1 interrupt.
Checks for timeouts, and executes timeout handlers for expired timers.
Definition at line 850 of file app_timer_ble_gzll.c.
References NRF_RTC1, and timer_timeouts_check().
 {
     // Clear all events (also unexpected ones).
     NRF_RTC1->EVENTS_COMPARE[0] = 0;
     NRF_RTC1->EVENTS_COMPARE[1] = 0;
     NRF_RTC1->EVENTS_COMPARE[2] = 0;
     NRF_RTC1->EVENTS_COMPARE[3] = 0;
     NRF_RTC1->EVENTS_TICK       = 0;
     NRF_RTC1->EVENTS_OVRFLW     = 0;
     // Check for expired timers.
     timer_timeouts_check();
 }
void SWI1_IRQHandler (void)
Function for handling the SWI0 interrupt.
Performs all updates to the timer list.
Definition at line 869 of file app_timer_ble_gzll.c.
References timer_list_handler().
 {
     timer_list_handler();
 }
static timer_user_id_t user_id_get (void) static
Function for creating a timer user id from the current interrupt level.
Returns
Timer user id.
Definition at line 983 of file app_timer_ble_gzll.c.
References APP_HIGH_USER_ID, APP_LOW_USER_ID, APP_TIMER_INT_LEVELS, STATIC_ASSERT(), and THREAD_MODE_USER_ID.
 {
     timer_user_id_t ret;
     STATIC_ASSERT(APP_TIMER_INT_LEVELS == 3);
     switch (current_int_priority_get())
     {
         case APP_IRQ_PRIORITY_HIGH:
             ret = APP_HIGH_USER_ID;
             break;
         case APP_IRQ_PRIORITY_LOW:
             ret = APP_LOW_USER_ID;
             break;
         default:
             ret = THREAD_MODE_USER_ID;
             break;
     }
     return ret;
 }
Variable Documentation
uint8_t m_node_array_size static
Size of timer node array.
Definition at line 128 of file app_timer_ble_gzll.c.
timer_node_t* mp_nodes = NULL static
Array of timer nodes.
Definition at line 129 of file app_timer_ble_gzll.c.
uint8_t m_user_array_size static
Size of timer user array.
Definition at line 130 of file app_timer_ble_gzll.c.
timer_user_t* mp_users static
Array of timer users.
Definition at line 131 of file app_timer_ble_gzll.c.
app_timer_id_t m_timer_id_head static
First timer in list of running timers.
Definition at line 132 of file app_timer_ble_gzll.c.
uint32_t m_ticks_latest static
Last known RTC counter value.
Definition at line 133 of file app_timer_ble_gzll.c.
uint32_t m_ticks_elapsed[CONTEXT_QUEUE_SIZE_MAX] static
Timer internal elapsed ticks queue.
Definition at line 134 of file app_timer_ble_gzll.c.
uint8_t m_ticks_elapsed_first static
Timer internal elapsed ticks queue read index.
Definition at line 135 of file app_timer_ble_gzll.c.
uint8_t m_ticks_elapsed_last static
Timer internal elapsed ticks queue write index.
Definition at line 136 of file app_timer_ble_gzll.c.
app_timer_evt_schedule_func_t m_evt_schedule_func static
Pointer to function for propagating timeout events to the scheduler.
Definition at line 137 of file app_timer_ble_gzll.c.