nRF51822 Beacon Firmware Documentation: components/libraries/button/app_button.c File Reference
app_button.c File Reference
#include "app_button.h"
#include <string.h>
#include "nordic_common.h"
#include "app_util.h"
#include "app_gpiote.h"
#include "app_timer.h"
#include "app_error.h"
Functions
static void button_handler_execute (app_button_cfg_t *p_btn, uint32_t transition)
Function for executing the application button handler for specified button.
static void detection_delay_timeout_handler (void *p_context)
Function for handling the timeout that delays reporting buttons as pushed.
static void gpiote_event_handler (uint32_t event_pins_low_to_high, uint32_t event_pins_high_to_low)
Function for handling the GPIOTE event.
uint32_t app_button_init (app_button_cfg_t *p_buttons, uint8_t button_count, uint32_t detection_delay, app_button_evt_schedule_func_t evt_schedule_func)
Function for initializing the Buttons.
uint32_t app_button_enable (void)
Function for enabling button detection.
uint32_t app_button_disable (void)
Function for disabling button detection.
uint32_t app_button_is_pushed (uint8_t button_id, bool *p_is_pushed)
Function for checking if a button is currently being pushed.
Variables
static app_button_cfg_t * mp_buttons = NULL
static uint8_t m_button_count
static uint32_t m_detection_delay
static
app_button_evt_schedule_func_t m_evt_schedule_func
static app_gpiote_user_id_t m_gpiote_user_id
static app_timer_id_t m_detection_delay_timer_id
static pin_transition_t m_pin_transition
Function Documentation
static void button_handler_execute (app_button_cfg_t * p_btn, uint32_t transition) static
Function for executing the application button handler for specified button.
Parameters
[in] p_btn Button that has been pushed.
Definition at line 35 of file app_button.c.
References APP_BUTTON_PUSH, APP_BUTTON_RELEASE, app_button_cfg_t::button_handler, m_evt_schedule_func, and app_button_cfg_t::pin_no.
 {
     if (m_evt_schedule_func != NULL)
     {
         uint32_t err_code = m_evt_schedule_func(p_btn->button_handler, p_btn->pin_no,transition);
         APP_ERROR_CHECK(err_code);
     }
     else
     {
         if(transition == APP_BUTTON_PUSH)
         {
             p_btn->button_handler(p_btn->pin_no, APP_BUTTON_PUSH);
         }
         else if(transition == APP_BUTTON_RELEASE)
         {
             p_btn->button_handler(p_btn->pin_no, APP_BUTTON_RELEASE);
         }
     }
 }
static void detection_delay_timeout_handler (void * p_context) static
Function for handling the timeout that delays reporting buttons as pushed.
The detection_delay_timeout_handler(...) is a call-back issued from the app_timer module. It is called with the p_context parameter. The p_context parameter is provided to the app_timer module when a timer is started, using the call app_timer_start. On app_timer_start the p_context will be holding the currently pressed buttons.
Parameters
[in] p_context Pointer used for passing information app_start_timer() was called. In the app_button module the p_context holds information on pressed buttons.
Definition at line 68 of file app_button.c.
References app_button_cfg_t::active_state, APP_BUTTON_ACTIVE_HIGH, APP_BUTTON_PUSH, APP_BUTTON_RELEASE, app_button_cfg_t::button_handler, button_handler_execute(), pin_transition_t::high_to_low, pin_transition_t::low_to_high, m_button_count, m_gpiote_user_id, NRF_SUCCESS, and app_button_cfg_t::pin_no.
 {
     uint32_t err_code;
     uint32_t current_state_pins;
     // Get current state of pins.
     err_code = app_gpiote_pins_state_get(m_gpiote_user_id, &current_state_pins);
     if (err_code != NRF_SUCCESS)
     {
         return;
     }
     uint8_t i;
     // Pushed button(s) detected, execute button handler(s).
     for (i = 0; i < m_button_count; i++)
     {
         app_button_cfg_t * p_btn = &mp_buttons[i];
         if (((m_pin_transition.high_to_low & (1 << p_btn->pin_no)) != 0) && (p_btn->button_handler != NULL))
         {
             //If it's active high then going from high to low was a release of the button.
             if(p_btn->active_state == APP_BUTTON_ACTIVE_HIGH)
             {
                 button_handler_execute(p_btn, APP_BUTTON_RELEASE);
             }
             //If it's active low then going from high to low was a push of the button.
             else
             {
                 button_handler_execute(p_btn, APP_BUTTON_PUSH);
             }
         }
         else if (((m_pin_transition.low_to_high & (1 << p_btn->pin_no)) != 0) && (p_btn->button_handler != NULL))
         {
             //If it's active high then going from low to high was a push of the button.
             if(p_btn->active_state == APP_BUTTON_ACTIVE_HIGH)
             {
                 button_handler_execute(p_btn,APP_BUTTON_PUSH);
             }
             //If it's active low then going from low to high was a release of the button.
             else
             {
                 button_handler_execute(p_btn,APP_BUTTON_RELEASE);
             }
         }
     }
 }
static void gpiote_event_handler (uint32_t event_pins_low_to_high, uint32_t event_pins_high_to_low) static
Function for handling the GPIOTE event.
Saves the current status of the button pins, and starts a timer. If the timer is already running, it will be restarted.
Parameters
[in] event_pins_low_to_high Mask telling which pin(s) had a low to high transition.
[in] event_pins_high_to_low Mask telling which pin(s) had a high to low transition.
Definition at line 126 of file app_button.c.
References app_timer_start(), app_timer_stop(), pin_transition_t::high_to_low, pin_transition_t::low_to_high, m_detection_delay, m_detection_delay_timer_id, NRF_SUCCESS, and STATIC_ASSERT().
 {
     uint32_t err_code;
     // Start detection timer. If timer is already running, the detection period is restarted.
     // NOTE: Using the p_context parameter of app_timer_start() to transfer the pin states to the
     //       timeout handler (by casting event_pins_mask into the equally sized void * p_context
     //       parameter).
     STATIC_ASSERT(sizeof(void *) == sizeof(uint32_t));
     err_code = app_timer_stop(m_detection_delay_timer_id);
     if (err_code != NRF_SUCCESS)
     {
         // The impact in app_button of the app_timer queue running full is losing a button press.
         // The current implementation ensures that the system will continue working as normal.
         return;
     }
     m_pin_transition.low_to_high = event_pins_low_to_high;
     m_pin_transition.high_to_low = event_pins_high_to_low;
     err_code = app_timer_start(m_detection_delay_timer_id,
                                m_detection_delay,
                                (void *)(event_pins_low_to_high | event_pins_high_to_low));
     if (err_code != NRF_SUCCESS)
     {
         // The impact in app_button of the app_timer queue running full is losing a button press.
         // The current implementation ensures that the system will continue working as normal.
     }
 }
Variable Documentation
app_button_cfg_t* mp_buttons = NULL static
Button configuration.
Definition at line 22 of file app_button.c.
uint8_t m_button_count static
Number of configured buttons.
Definition at line 23 of file app_button.c.
uint32_t m_detection_delay static
Delay before a button is reported as pushed.
Definition at line 24 of file app_button.c.
app_button_evt_schedule_func_t m_evt_schedule_func static
Pointer to function for propagating button events to the scheduler.
Definition at line 25 of file app_button.c.
app_gpiote_user_id_t m_gpiote_user_id static
GPIOTE user id for buttons module.
Definition at line 26 of file app_button.c.
app_timer_id_t m_detection_delay_timer_id static
Polling timer id.
Definition at line 27 of file app_button.c.
pin_transition_t m_pin_transition static
pin transaction direction.
Definition at line 28 of file app_button.c.