nRF51822 Beacon Firmware Documentation: components/ble/common/ble_conn_params.c File Reference
ble_conn_params.c File Reference
#include "ble_conn_params.h"
#include <stdlib.h>
#include "nordic_common.h"
#include "ble_hci.h"
#include "app_timer.h"
#include "ble_srv_common.h"
#include "app_util.h"
Functions
static bool is_conn_params_ok (ble_gap_conn_params_t *p_conn_params)
static void update_timeout_handler (void *p_context)
uint32_t ble_conn_params_init (const ble_conn_params_init_t *p_init)
Function for initializing the Connection Parameters module.
uint32_t ble_conn_params_stop (void)
Function for stopping the Connection Parameters module.
static void conn_params_negotiation (void)
static void on_connect (ble_evt_t *p_ble_evt)
static void on_disconnect (ble_evt_t *p_ble_evt)
static void on_write (ble_evt_t *p_ble_evt)
static void on_conn_params_update (ble_evt_t *p_ble_evt)
void ble_conn_params_on_ble_evt (ble_evt_t *p_ble_evt)
Function for handling the Application's BLE Stack events.
uint32_t ble_conn_params_change_conn_params (ble_gap_conn_params_t *new_params)
Function for changing the current connection parameters to a new set.
Variables
static ble_conn_params_init_t m_conn_params_config
static ble_gap_conn_params_t m_preferred_conn_params
static uint8_t m_update_count
static uint16_t m_conn_handle
static ble_gap_conn_params_t m_current_conn_params
static app_timer_id_t m_conn_params_timer_id
static bool m_change_param = false
Function Documentation
static bool is_conn_params_ok (ble_gap_conn_params_t * p_conn_params) static
Definition at line 31 of file ble_conn_params.c.
References ble_gap_conn_params_t::max_conn_interval, and ble_gap_conn_params_t::min_conn_interval.
 {
     // Check if interval is within the acceptable range.
     // NOTE: Using max_conn_interval in the received event data because this contains
     //       the client's connection interval.
     if (
         (p_conn_params->max_conn_interval >= m_preferred_conn_params.min_conn_interval)
         &&
         (p_conn_params->max_conn_interval <= m_preferred_conn_params.max_conn_interval)
        )
     {
         return true;
     }
     else
     {
         return false;
     }
 }
static void update_timeout_handler (void * p_context) static
Definition at line 51 of file ble_conn_params.c.
References BLE_CONN_HANDLE_INVALID, BLE_CONN_PARAMS_EVT_FAILED, BLE_HCI_CONN_INTERVAL_UNACCEPTABLE, ble_conn_params_init_t::disconnect_on_fail, ble_conn_params_init_t::error_handler, ble_conn_params_init_t::evt_handler, ble_conn_params_evt_t::evt_type, m_conn_handle, m_update_count, ble_conn_params_init_t::max_conn_params_update_count, and NRF_SUCCESS.
 {
     UNUSED_PARAMETER(p_context);
     if (m_conn_handle != BLE_CONN_HANDLE_INVALID)
     {
         // Check if we have reached the maximum number of attempts
         m_update_count++;
         if (m_update_count <= m_conn_params_config.max_conn_params_update_count)
         {
             uint32_t err_code;
             // Parameters are not ok, send connection parameters update request.
             err_code = sd_ble_gap_conn_param_update(m_conn_handle, &m_preferred_conn_params);
             if ((err_code != NRF_SUCCESS) && (m_conn_params_config.error_handler != NULL))
             {
                 m_conn_params_config.error_handler(err_code);
             }
         }
         else
         {
             m_update_count = 0;
             // Negotiation failed, disconnect automatically if this has been configured
             if (m_conn_params_config.disconnect_on_fail)
             {
                 uint32_t err_code;
                 err_code = sd_ble_gap_disconnect(m_conn_handle, BLE_HCI_CONN_INTERVAL_UNACCEPTABLE);
                 if ((err_code != NRF_SUCCESS) && (m_conn_params_config.error_handler != NULL))
                 {
                     m_conn_params_config.error_handler(err_code);
                 }
             }
             // Notify the application that the procedure has failed
             if (m_conn_params_config.evt_handler != NULL)
             {
                 ble_conn_params_evt_t evt;
                 evt.evt_type = BLE_CONN_PARAMS_EVT_FAILED;
                 m_conn_params_config.evt_handler(&evt);
             }
         }
     }
 }
static void conn_params_negotiation (void) static
Definition at line 141 of file ble_conn_params.c.
References app_timer_start(), BLE_CONN_PARAMS_EVT_FAILED, BLE_CONN_PARAMS_EVT_SUCCEEDED, ble_conn_params_init_t::error_handler, ble_conn_params_init_t::evt_handler, ble_conn_params_evt_t::evt_type, ble_conn_params_init_t::first_conn_params_update_delay, is_conn_params_ok(), m_change_param, m_conn_params_timer_id, m_update_count, ble_conn_params_init_t::next_conn_params_update_delay, and NRF_SUCCESS.
 {
     // Start negotiation if the received connection parameters are not acceptable
     if (!is_conn_params_ok(&m_current_conn_params))
     {
         uint32_t err_code;
         uint32_t timeout_ticks;
         if (m_change_param)
         {
             // Notify the application that the procedure has failed
             if (m_conn_params_config.evt_handler != NULL)
             {
                 ble_conn_params_evt_t evt;
                 evt.evt_type = BLE_CONN_PARAMS_EVT_FAILED;
                 m_conn_params_config.evt_handler(&evt);
             }
         }
         else
         {
             if (m_update_count == 0)
             {
                 // First connection parameter update
                 timeout_ticks = m_conn_params_config.first_conn_params_update_delay;
             }
             else
             {
                 timeout_ticks = m_conn_params_config.next_conn_params_update_delay;
             }
             err_code = app_timer_start(m_conn_params_timer_id, timeout_ticks, NULL);
             if ((err_code != NRF_SUCCESS) && (m_conn_params_config.error_handler != NULL))
             {
                 m_conn_params_config.error_handler(err_code);
             }
         }
     }
     else
     {
         // Notify the application that the procedure has succeded
         if (m_conn_params_config.evt_handler != NULL)
         {
             ble_conn_params_evt_t evt;
             evt.evt_type = BLE_CONN_PARAMS_EVT_SUCCEEDED;
             m_conn_params_config.evt_handler(&evt);
         }
     }
     m_change_param = false;
 }
static void on_connect (ble_evt_t * p_ble_evt) static
Definition at line 194 of file ble_conn_params.c.
References BLE_GATT_HANDLE_INVALID, ble_gap_evt_t::conn_handle, ble_gap_evt_connected_t::conn_params, conn_params_negotiation(), ble_gap_evt_t::connected, ble_evt_t::evt, ble_evt_t::gap_evt, m_conn_handle, m_update_count, ble_gap_evt_t::params, and ble_conn_params_init_t::start_on_notify_cccd_handle.
 {
     // Save connection parameters
     m_conn_handle         = p_ble_evt->evt.gap_evt.conn_handle;
     m_current_conn_params = p_ble_evt->evt.gap_evt.params.connected.conn_params;
     m_update_count        = 0;  // Connection parameter negotiation should re-start every connection
     // Check if we shall handle negotiation on connect
     if (m_conn_params_config.start_on_notify_cccd_handle == BLE_GATT_HANDLE_INVALID)
     {
         conn_params_negotiation();
     }
 }
static void on_disconnect (ble_evt_t * p_ble_evt) static
Definition at line 209 of file ble_conn_params.c.
References app_timer_stop(), BLE_CONN_HANDLE_INVALID, ble_conn_params_init_t::error_handler, m_conn_handle, m_conn_params_timer_id, m_update_count, and NRF_SUCCESS.
 {
     uint32_t err_code;
     m_conn_handle = BLE_CONN_HANDLE_INVALID;
     // Stop timer if running
     m_update_count = 0; // Connection parameters updates should happen during every connection
     err_code = app_timer_stop(m_conn_params_timer_id);
     if ((err_code != NRF_SUCCESS) && (m_conn_params_config.error_handler != NULL))
     {
         m_conn_params_config.error_handler(err_code);
     }
 }
static void on_write (ble_evt_t * p_ble_evt) static
Definition at line 226 of file ble_conn_params.c.
References app_timer_stop(), ble_srv_is_notification_enabled(), conn_params_negotiation(), ble_gatts_evt_write_t::data, ble_conn_params_init_t::error_handler, ble_evt_t::evt, ble_evt_t::gatts_evt, ble_gatts_evt_write_t::handle, ble_gatts_evt_write_t::len, m_conn_params_timer_id, NRF_SUCCESS, ble_gatts_evt_t::params, ble_conn_params_init_t::start_on_notify_cccd_handle, and ble_gatts_evt_t::write.
 {
     ble_gatts_evt_write_t * p_evt_write = &p_ble_evt->evt.gatts_evt.params.write;
     // Check if this the correct CCCD
     if (
         (p_evt_write->handle == m_conn_params_config.start_on_notify_cccd_handle)
         &&
         (p_evt_write->len == 2)
        )
     {
         // Check if this is a 'start notification'
         if (ble_srv_is_notification_enabled(p_evt_write->data))
         {
             // Do connection parameter negotiation if necessary
             conn_params_negotiation();
         }
         else
         {
             uint32_t err_code;
             // Stop timer if running
             err_code = app_timer_stop(m_conn_params_timer_id);
             if ((err_code != NRF_SUCCESS) && (m_conn_params_config.error_handler != NULL))
             {
                 m_conn_params_config.error_handler(err_code);
             }
         }
     }
 }
static void on_conn_params_update (ble_evt_t * p_ble_evt) static
Definition at line 258 of file ble_conn_params.c.
References ble_gap_evt_t::conn_param_update, ble_gap_evt_conn_param_update_t::conn_params, conn_params_negotiation(), ble_evt_t::evt, ble_evt_t::gap_evt, and ble_gap_evt_t::params.
 {
     // Copy the parameters
     m_current_conn_params = p_ble_evt->evt.gap_evt.params.conn_param_update.conn_params;
     conn_params_negotiation();
 }
Variable Documentation
ble_conn_params_init_t m_conn_params_config static
Configuration as specified by the application.
Definition at line 22 of file ble_conn_params.c.
ble_gap_conn_params_t m_preferred_conn_params static
Connection parameters preferred by the application.
Definition at line 23 of file ble_conn_params.c.
uint8_t m_update_count static
Number of Connection Parameter Update messages that has currently been sent.
Definition at line 24 of file ble_conn_params.c.
uint16_t m_conn_handle static
Current connection handle.
Definition at line 25 of file ble_conn_params.c.
ble_gap_conn_params_t m_current_conn_params static
Connection parameters received in the most recent Connect event.
Definition at line 26 of file ble_conn_params.c.
app_timer_id_t m_conn_params_timer_id static
Connection parameters timer.
Definition at line 27 of file ble_conn_params.c.
bool m_change_param = false static
Definition at line 29 of file ble_conn_params.c.