nRF51822 Beacon Firmware Documentation: components/ble/ble_services/ble_dfu/ble_dfu.c File Reference
ble_dfu.c File Reference
#include "ble_dfu.h"
#include "nrf_error.h"
#include "ble_types.h"
#include "ble_gatts.h"
#include "app_util.h"
#include "ble_srv_common.h"
#include "nordic_common.h"
#include <stdint.h>
#include <string.h>
#include <stddef.h>
Macros
#define MAX_DFU_PKT_LEN 20
#define PKT_START_DFU_PARAM_LEN 2
#define PKT_INIT_DFU_PARAM_LEN 2
#define PKT_RCPT_NOTIF_REQ_LEN 3
#define MAX_PKTS_RCPT_NOTIF_LEN 6
#define MAX_RESPONSE_LEN 7
#define MAX_NOTIF_BUFFER_LEN MAX(MAX_PKTS_RCPT_NOTIF_LEN, MAX_RESPONSE_LEN)
Enumerations
enum {
OP_CODE_START_DFU = 1, OP_CODE_RECEIVE_INIT = 2, OP_CODE_RECEIVE_FW = 3, OP_CODE_VALIDATE = 4,
OP_CODE_ACTIVATE_N_RESET = 5, OP_CODE_SYS_RESET = 6, OP_CODE_IMAGE_SIZE_REQ = 7, OP_CODE_PKT_RCPT_NOTIF_REQ = 8,
OP_CODE_RESPONSE = 16, OP_CODE_PKT_RCPT_NOTIF = 17
}
Functions
static uint32_t dfu_pkt_char_add (ble_dfu_t *const p_dfu)
Function for adding DFU Packet characteristic to the BLE Stack.
static uint32_t dfu_rev_char_add (ble_dfu_t *const p_dfu, ble_dfu_init_t const *const p_dfu_init)
Function for adding DFU Revision characteristic to the BLE Stack.
static uint32_t dfu_ctrl_pt_add (ble_dfu_t *const p_dfu)
Function for adding DFU Control Point characteristic to the BLE Stack.
static void on_connect (ble_dfu_t *p_dfu, ble_evt_t *p_ble_evt)
Function for handling the BLE_GAP_EVT_CONNECTED event from the S110 SoftDevice.
static bool is_cccd_configured (ble_dfu_t *p_dfu)
Function for checking if the CCCD of DFU Control point is configured for Notification.
static uint32_t on_ctrl_pt_write (ble_dfu_t *p_dfu, ble_gatts_evt_write_t *p_ble_write_evt)
Function for handling a Write event on the Control Point characteristic.
static void on_rw_auth_req (ble_dfu_t *p_dfu, ble_evt_t *p_ble_evt)
Function for handling the BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST event from the S110 Stack.
static void on_write (ble_dfu_t *p_dfu, ble_evt_t *p_ble_evt)
Function for handling the BLE_GATTS_EVT_WRITE event from the S110 SoftDevice.
static void on_disconnect (ble_dfu_t *p_dfu, ble_evt_t *p_ble_evt)
Function for handling the BLE_GAP_EVT_DISCONNECTED event from the S110 SoftDevice.
uint32_t ble_dfu_init (ble_dfu_t *p_dfu, ble_dfu_init_t *p_dfu_init)
Function for initializing the DFU service.
void ble_dfu_on_ble_evt (ble_dfu_t *p_dfu, ble_evt_t *p_ble_evt)
Function for handling a BLE event.
uint32_t ble_dfu_bytes_rcvd_report (ble_dfu_t *p_dfu, uint32_t num_of_firmware_bytes_rcvd)
Function for notifying the peer about the number of bytes of firmware data received.
uint32_t ble_dfu_pkts_rcpt_notify (ble_dfu_t *p_dfu, uint32_t num_of_firmware_bytes_rcvd)
Function for sending Packet Receipt Notification to the peer.
uint32_t ble_dfu_response_send (ble_dfu_t *p_dfu, ble_dfu_procedure_t dfu_proc, ble_dfu_resp_val_t resp_val)
Function for sending response to a control point command.
Variables
static bool m_is_dfu_service_initialized = false
static uint8_t m_notif_buffer [MAX_NOTIF_BUFFER_LEN]
Macro Definition Documentation
#define MAX_DFU_PKT_LEN 20
Maximum length (in bytes) of the DFU Packet characteristic.
Definition at line 24 of file ble_dfu.c.
#define PKT_START_DFU_PARAM_LEN 2
Length (in bytes) of the parameters for Packet Start DFU Request.
Definition at line 25 of file ble_dfu.c.
#define PKT_INIT_DFU_PARAM_LEN 2
Length (in bytes) of the parameters for Packet Init DFU Request.
Definition at line 26 of file ble_dfu.c.
#define PKT_RCPT_NOTIF_REQ_LEN 3
Length (in bytes) of the Packet Receipt Notification Request.
Definition at line 27 of file ble_dfu.c.
#define MAX_PKTS_RCPT_NOTIF_LEN 6
Maximum length (in bytes) of the Packets Receipt Notification.
Definition at line 28 of file ble_dfu.c.
#define MAX_RESPONSE_LEN 7
Maximum length (in bytes) of the response to a Control Point command.
Definition at line 29 of file ble_dfu.c.
#define MAX_NOTIF_BUFFER_LEN MAX(MAX_PKTS_RCPT_NOTIF_LEN, MAX_RESPONSE_LEN)
Maximum length (in bytes) of the buffer needed by DFU Service while sending notifications to peer.
Definition at line 30 of file ble_dfu.c.
Enumeration Type Documentation
anonymous enum
Enumerator
OP_CODE_START_DFU
Value of the Op code field for 'Start DFU' command.
OP_CODE_RECEIVE_INIT
Value of the Op code field for 'Initialize DFU parameters' command.
OP_CODE_RECEIVE_FW
Value of the Op code field for 'Receive firmware image' command.
OP_CODE_VALIDATE
Value of the Op code field for 'Validate firmware' command.
OP_CODE_ACTIVATE_N_RESET
Value of the Op code field for 'Activate & Reset' command.
OP_CODE_SYS_RESET
Value of the Op code field for 'Reset System' command.
OP_CODE_IMAGE_SIZE_REQ
Value of the Op code field for 'Report received image size' command.
OP_CODE_PKT_RCPT_NOTIF_REQ
Value of the Op code field for 'Request packet receipt notification.
OP_CODE_RESPONSE
Value of the Op code field for 'Response.
OP_CODE_PKT_RCPT_NOTIF
Value of the Op code field for 'Packets Receipt Notification'.
Definition at line 32 of file ble_dfu.c.
 {
     OP_CODE_START_DFU          = 1,
     OP_CODE_RECEIVE_INIT       = 2,
     OP_CODE_RECEIVE_FW         = 3,
     OP_CODE_VALIDATE           = 4,
     OP_CODE_ACTIVATE_N_RESET   = 5,
     OP_CODE_SYS_RESET          = 6,
     OP_CODE_IMAGE_SIZE_REQ     = 7,
     OP_CODE_PKT_RCPT_NOTIF_REQ = 8,
     OP_CODE_RESPONSE           = 16,
     OP_CODE_PKT_RCPT_NOTIF     = 17
 };
Function Documentation
static uint32_t dfu_pkt_char_add (ble_dfu_t *const p_dfu) static
Function for adding DFU Packet characteristic to the BLE Stack.
Parameters
[in] p_dfu DFU Service structure.
Returns
NRF_SUCCESS on success. Otherwise an error code.
Definition at line 55 of file ble_dfu.c.
References BLE_DFU_PKT_CHAR_UUID, BLE_GAP_CONN_SEC_MODE_SET_NO_ACCESS, BLE_GAP_CONN_SEC_MODE_SET_OPEN, BLE_GATTS_VLOC_STACK, ble_gatts_char_md_t::char_props, ble_dfu_s::dfu_pkt_handles, ble_gatts_attr_t::init_len, ble_gatts_attr_t::init_offs, MAX_DFU_PKT_LEN, ble_gatts_attr_t::max_len, ble_gatts_attr_t::p_attr_md, ble_gatts_char_md_t::p_cccd_md, ble_gatts_char_md_t::p_char_pf, ble_gatts_char_md_t::p_char_user_desc, ble_gatts_char_md_t::p_sccd_md, ble_gatts_char_md_t::p_user_desc_md, ble_gatts_attr_t::p_uuid, ble_gatts_attr_t::p_value, ble_gatts_attr_md_t::rd_auth, ble_gatts_attr_md_t::read_perm, ble_dfu_s::service_handle, ble_uuid_t::type, ble_uuid_t::uuid, ble_dfu_s::uuid_type, ble_gatts_attr_md_t::vlen, ble_gatts_attr_md_t::vloc, ble_gatts_attr_md_t::wr_auth, ble_gatts_attr_md_t::write_perm, and ble_gatt_char_props_t::write_wo_resp.
 {
     ble_gatts_char_md_t char_md;
     ble_gatts_attr_t    attr_char_value;
     ble_uuid_t          char_uuid;
     ble_gatts_attr_md_t attr_md;
     memset(&char_md, 0, sizeof(char_md));
     char_md.char_props.write_wo_resp = 1;
     char_md.p_char_user_desc         = NULL;
     char_md.p_char_pf                = NULL;
     char_md.p_user_desc_md           = NULL;
     char_md.p_cccd_md                = NULL;
     char_md.p_sccd_md                = NULL;
     char_uuid.type = p_dfu->uuid_type;
     char_uuid.uuid = BLE_DFU_PKT_CHAR_UUID;
     memset(&attr_md, 0, sizeof(attr_md));
     BLE_GAP_CONN_SEC_MODE_SET_NO_ACCESS(&attr_md.read_perm);
     BLE_GAP_CONN_SEC_MODE_SET_OPEN(&attr_md.write_perm);
     attr_md.vloc    = BLE_GATTS_VLOC_STACK;
     attr_md.rd_auth = 0;
     attr_md.wr_auth = 0;
     attr_md.vlen    = 1;
     memset(&attr_char_value, 0, sizeof(attr_char_value));
     attr_char_value.p_uuid    = &char_uuid;
     attr_char_value.p_attr_md = &attr_md;
     attr_char_value.init_len  = 0;
     attr_char_value.init_offs = 0;
     attr_char_value.max_len   = MAX_DFU_PKT_LEN;
     attr_char_value.p_value   = NULL;
     return sd_ble_gatts_characteristic_add(p_dfu->service_handle,
                                            &char_md,
                                            &attr_char_value,
                                            &p_dfu->dfu_pkt_handles);
 }
static uint32_t dfu_rev_char_add (ble_dfu_t *const p_dfu, ble_dfu_init_t const *const p_dfu_init) static
Function for adding DFU Revision characteristic to the BLE Stack.
Parameters
[in] p_dfu DFU Service structure.
Returns
NRF_SUCCESS on success. Otherwise an error code.
Definition at line 106 of file ble_dfu.c.
References BLE_DFU_REV_CHAR_UUID, BLE_GAP_CONN_SEC_MODE_SET_NO_ACCESS, BLE_GAP_CONN_SEC_MODE_SET_OPEN, BLE_GATTS_VLOC_STACK, ble_gatts_char_md_t::char_props, ble_dfu_s::dfu_rev_handles, ble_gatts_attr_t::init_len, ble_gatts_attr_t::init_offs, ble_gatts_attr_t::max_len, ble_gatts_attr_t::p_attr_md, ble_gatts_char_md_t::p_cccd_md, ble_gatts_char_md_t::p_char_pf, ble_gatts_char_md_t::p_char_user_desc, ble_gatts_char_md_t::p_sccd_md, ble_gatts_char_md_t::p_user_desc_md, ble_gatts_attr_t::p_uuid, ble_gatts_attr_t::p_value, ble_gatts_attr_md_t::rd_auth, ble_gatt_char_props_t::read, ble_gatts_attr_md_t::read_perm, ble_dfu_init_t::revision, ble_dfu_s::service_handle, ble_uuid_t::type, ble_uuid_t::uuid, ble_dfu_s::uuid_type, ble_gatts_attr_md_t::vlen, ble_gatts_attr_md_t::vloc, ble_gatts_attr_md_t::wr_auth, and ble_gatts_attr_md_t::write_perm.
 {
     ble_gatts_char_md_t char_md;
     ble_gatts_attr_t    attr_char_value;
     ble_uuid_t          char_uuid;
     ble_gatts_attr_md_t attr_md;
     memset(&char_md, 0, sizeof(char_md));
     char_md.char_props.read          = 1;
     char_md.p_char_user_desc         = NULL;
     char_md.p_char_pf                = NULL;
     char_md.p_user_desc_md           = NULL;
     char_md.p_cccd_md                = NULL;
     char_md.p_sccd_md                = NULL;
     char_uuid.type = p_dfu->uuid_type;
     char_uuid.uuid = BLE_DFU_REV_CHAR_UUID;
     memset(&attr_md, 0, sizeof(attr_md));
     BLE_GAP_CONN_SEC_MODE_SET_OPEN(&attr_md.read_perm);
     BLE_GAP_CONN_SEC_MODE_SET_NO_ACCESS(&attr_md.write_perm);
     attr_md.vloc    = BLE_GATTS_VLOC_STACK;
     attr_md.rd_auth = 0;
     attr_md.wr_auth = 0;
     attr_md.vlen    = 1;
     memset(&attr_char_value, 0, sizeof(attr_char_value));
     attr_char_value.p_uuid    = &char_uuid;
     attr_char_value.p_attr_md = &attr_md;
     attr_char_value.init_len  = sizeof(uint16_t);
     attr_char_value.init_offs = 0;
     attr_char_value.max_len   = sizeof(uint16_t);
     attr_char_value.p_value   = (uint8_t *)&p_dfu_init->revision;
     return sd_ble_gatts_characteristic_add(p_dfu->service_handle,
                                            &char_md,
                                            &attr_char_value,
                                            &p_dfu->dfu_rev_handles);
 }
static uint32_t dfu_ctrl_pt_add (ble_dfu_t *const p_dfu) static
Function for adding DFU Control Point characteristic to the BLE Stack.
Parameters
[in] p_dfu DFU Service structure.
Returns
NRF_SUCCESS on success. Otherwise an error code.
Definition at line 157 of file ble_dfu.c.
References BLE_DFU_CTRL_PT_UUID, BLE_GAP_CONN_SEC_MODE_SET_NO_ACCESS, BLE_GAP_CONN_SEC_MODE_SET_OPEN, BLE_GATTS_VLOC_STACK, BLE_L2CAP_MTU_DEF, ble_gatts_char_md_t::char_props, ble_dfu_s::dfu_ctrl_pt_handles, ble_gatts_attr_t::init_len, ble_gatts_attr_t::init_offs, ble_gatts_attr_t::max_len, ble_gatt_char_props_t::notify, ble_gatts_attr_t::p_attr_md, ble_gatts_char_md_t::p_cccd_md, ble_gatts_char_md_t::p_char_pf, ble_gatts_char_md_t::p_char_user_desc, ble_gatts_char_md_t::p_sccd_md, ble_gatts_char_md_t::p_user_desc_md, ble_gatts_attr_t::p_uuid, ble_gatts_attr_t::p_value, ble_gatts_attr_md_t::rd_auth, ble_gatts_attr_md_t::read_perm, ble_dfu_s::service_handle, ble_uuid_t::type, ble_uuid_t::uuid, ble_dfu_s::uuid_type, ble_gatts_attr_md_t::vlen, ble_gatts_attr_md_t::vloc, ble_gatts_attr_md_t::wr_auth, ble_gatt_char_props_t::write, and ble_gatts_attr_md_t::write_perm.
 {
     ble_gatts_char_md_t char_md;
     ble_gatts_attr_t    attr_char_value;
     ble_uuid_t          char_uuid;
     ble_gatts_attr_md_t attr_md;
     memset(&char_md, 0, sizeof(char_md));
     char_md.char_props.write  = 1;
     char_md.char_props.notify = 1;
     char_md.p_char_user_desc  = NULL;
     char_md.p_char_pf         = NULL;
     char_md.p_user_desc_md    = NULL;
     char_md.p_cccd_md         = NULL;
     char_md.p_sccd_md         = NULL;
     char_uuid.type = p_dfu->uuid_type;
     char_uuid.uuid = BLE_DFU_CTRL_PT_UUID;
     memset(&attr_md, 0, sizeof(attr_md));
     BLE_GAP_CONN_SEC_MODE_SET_NO_ACCESS(&attr_md.read_perm);
     BLE_GAP_CONN_SEC_MODE_SET_OPEN(&attr_md.write_perm);
     attr_md.vloc    = BLE_GATTS_VLOC_STACK;
     attr_md.rd_auth = 0;
     attr_md.wr_auth = 1;
     attr_md.vlen    = 1;
     memset(&attr_char_value, 0, sizeof(attr_char_value));
     attr_char_value.p_uuid    = &char_uuid;
     attr_char_value.p_attr_md = &attr_md;
     attr_char_value.init_len  = 0;
     attr_char_value.init_offs = 0;
     attr_char_value.max_len   = BLE_L2CAP_MTU_DEF;
     attr_char_value.p_value   = NULL;
     return sd_ble_gatts_characteristic_add(p_dfu->service_handle,
                                            &char_md,
                                            &attr_char_value,
                                            &p_dfu->dfu_ctrl_pt_handles);
 }
static void on_connect (ble_dfu_t * p_dfu, ble_evt_t * p_ble_evt) static
Function for handling the BLE_GAP_EVT_CONNECTED event from the S110 SoftDevice.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_ble_evt Pointer to the event received from BLE stack.
Definition at line 208 of file ble_dfu.c.
References ble_dfu_s::conn_handle, ble_gap_evt_t::conn_handle, ble_evt_t::evt, and ble_evt_t::gap_evt.
 {
     p_dfu->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
 }
static bool is_cccd_configured (ble_dfu_t * p_dfu) static
Function for checking if the CCCD of DFU Control point is configured for Notification.
This function checks if the CCCD of DFU Control Point characteristic is configured for Notification by the DFU Controller.
Parameters
[in] p_dfu DFU Service structure.
Returns
True if the CCCD of DFU Control Point characteristic is configured for Notification. False otherwise.
Definition at line 224 of file ble_dfu.c.
References BLE_CCCD_VALUE_LEN, ble_srv_is_notification_enabled(), ble_gatts_char_handles_t::cccd_handle, ble_dfu_s::dfu_ctrl_pt_handles, ble_dfu_s::error_handler, and NRF_SUCCESS.
 {
     // Check if the CCCDs are configured.
     uint16_t cccd_len = BLE_CCCD_VALUE_LEN;
     uint8_t  cccd_val_buf[BLE_CCCD_VALUE_LEN];
     // Check the CCCD Value of DFU Control Point.
     uint32_t err_code = sd_ble_gatts_value_get(p_dfu->dfu_ctrl_pt_handles.cccd_handle,
                                                0,
                                                &cccd_len,
                                                cccd_val_buf);
     if (err_code != NRF_SUCCESS)
     {
         if (p_dfu->error_handler != NULL)
         {
             p_dfu->error_handler(err_code);
         }
         return false;
     }
     return ble_srv_is_notification_enabled(cccd_val_buf);
 }
static uint32_t on_ctrl_pt_write (ble_dfu_t * p_dfu, ble_gatts_evt_write_t * p_ble_write_evt) static
Function for handling a Write event on the Control Point characteristic.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_ble_write_evt Pointer to the write event received from BLE stack.
Returns
NRF_SUCCESS on successful processing of control point write. Otherwise an error code.
Definition at line 255 of file ble_dfu.c.
References BLE_DFU_ACTIVATE_N_RESET, BLE_DFU_BYTES_RECEIVED_SEND, ble_dfu_evt_t::ble_dfu_evt_type, BLE_DFU_PKT_RCPT_NOTIF_DISABLED, BLE_DFU_PKT_RCPT_NOTIF_ENABLED, BLE_DFU_PKT_RCPT_REQ_PROCEDURE, ble_dfu_evt_t::ble_dfu_pkt_write, BLE_DFU_RECEIVE_APP_DATA, BLE_DFU_RECEIVE_INIT_DATA, BLE_DFU_RESP_VAL_NOT_SUPPORTED, BLE_DFU_RESP_VAL_OPER_FAILED, ble_dfu_response_send(), BLE_DFU_START, BLE_DFU_SYS_RESET, BLE_DFU_VALIDATE, BLE_GATT_STATUS_ATTERR_CPS_CCCD_CONFIG_ERROR, BLE_GATT_STATUS_SUCCESS, BLE_GATTS_AUTHORIZE_TYPE_WRITE, ble_dfu_s::conn_handle, ble_gatts_evt_write_t::data, ble_dfu_evt_t::evt, ble_dfu_s::evt_handler, ble_gatts_write_authorize_params_t::gatt_status, is_cccd_configured(), ble_dfu_pkt_write_t::len, ble_gatts_evt_write_t::len, NRF_SUCCESS, ble_pkt_rcpt_notif_req_t::num_of_pkts, OP_CODE_ACTIVATE_N_RESET, OP_CODE_IMAGE_SIZE_REQ, OP_CODE_PKT_RCPT_NOTIF_REQ, OP_CODE_RECEIVE_FW, OP_CODE_RECEIVE_INIT, OP_CODE_START_DFU, OP_CODE_SYS_RESET, OP_CODE_VALIDATE, ble_dfu_pkt_write_t::p_data, ble_gatts_rw_authorize_reply_params_t::params, PKT_INIT_DFU_PARAM_LEN, ble_dfu_evt_t::pkt_rcpt_notif_req, PKT_RCPT_NOTIF_REQ_LEN, PKT_START_DFU_PARAM_LEN, ble_gatts_rw_authorize_reply_params_t::type, and ble_gatts_rw_authorize_reply_params_t::write.
 {
     ble_gatts_rw_authorize_reply_params_t write_authorize_reply;
     write_authorize_reply.type = BLE_GATTS_AUTHORIZE_TYPE_WRITE;
     if (!is_cccd_configured(p_dfu))
     {
         // Send an error response to the peer indicating that the CCCD is improperly configured.
         write_authorize_reply.params.write.gatt_status =
             BLE_GATT_STATUS_ATTERR_CPS_CCCD_CONFIG_ERROR;
         return (sd_ble_gatts_rw_authorize_reply(p_dfu->conn_handle, &write_authorize_reply));
     }
     else
     {
         uint32_t err_code;
         write_authorize_reply.params.write.gatt_status = BLE_GATT_STATUS_SUCCESS;
         err_code = (sd_ble_gatts_rw_authorize_reply(p_dfu->conn_handle, &write_authorize_reply));
         if (err_code != NRF_SUCCESS)
         {
             return err_code;
         }
     }
     ble_dfu_evt_t ble_dfu_evt;
     switch (p_ble_write_evt->data[0])
     {
         case OP_CODE_START_DFU:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_START;
             if (p_ble_write_evt->len < PKT_START_DFU_PARAM_LEN)
             {
                 return ble_dfu_response_send(p_dfu,
                                              (ble_dfu_procedure_t) p_ble_write_evt->data[0],
                                              BLE_DFU_RESP_VAL_OPER_FAILED);
             }
             ble_dfu_evt.evt.ble_dfu_pkt_write.len    = 1;
             ble_dfu_evt.evt.ble_dfu_pkt_write.p_data = &(p_ble_write_evt->data[1]);
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_RECEIVE_INIT:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_RECEIVE_INIT_DATA;
             if (p_ble_write_evt->len < PKT_INIT_DFU_PARAM_LEN)
             {
                 return ble_dfu_response_send(p_dfu,
                                              (ble_dfu_procedure_t) p_ble_write_evt->data[0],
                                              BLE_DFU_RESP_VAL_OPER_FAILED);
             }
             ble_dfu_evt.evt.ble_dfu_pkt_write.len    = 1;
             ble_dfu_evt.evt.ble_dfu_pkt_write.p_data = &(p_ble_write_evt->data[1]);
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_RECEIVE_FW:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_RECEIVE_APP_DATA;
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_VALIDATE:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_VALIDATE;
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_ACTIVATE_N_RESET:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_ACTIVATE_N_RESET;
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_SYS_RESET:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_SYS_RESET;
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_PKT_RCPT_NOTIF_REQ:
             if (p_ble_write_evt->len < PKT_RCPT_NOTIF_REQ_LEN)
             {
                 return (ble_dfu_response_send(p_dfu,
                                               BLE_DFU_PKT_RCPT_REQ_PROCEDURE,
                                               BLE_DFU_RESP_VAL_NOT_SUPPORTED));
             }
             ble_dfu_evt.evt.pkt_rcpt_notif_req.num_of_pkts =
                 uint16_decode(&(p_ble_write_evt->data[1]));
             if (ble_dfu_evt.evt.pkt_rcpt_notif_req.num_of_pkts == 0)
             {
                 ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_PKT_RCPT_NOTIF_DISABLED;
             }
             else
             {
                 ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_PKT_RCPT_NOTIF_ENABLED;
             }
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         case OP_CODE_IMAGE_SIZE_REQ:
             ble_dfu_evt.ble_dfu_evt_type = BLE_DFU_BYTES_RECEIVED_SEND;
             p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
             break;
         default:
             // Unsupported op code.
             return ble_dfu_response_send(p_dfu,
                                          (ble_dfu_procedure_t) p_ble_write_evt->data[0],
                                          BLE_DFU_RESP_VAL_NOT_SUPPORTED);
     }
     return NRF_SUCCESS;
 }
static void on_rw_auth_req (ble_dfu_t * p_dfu, ble_evt_t * p_ble_evt) static
Function for handling the BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST event from the S110 Stack.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_ble_evt Pointer to the event received from BLE stack.
Definition at line 390 of file ble_dfu.c.
References ble_gatts_evt_t::authorize_request, BLE_GATTS_AUTHORIZE_TYPE_WRITE, ble_dfu_s::dfu_ctrl_pt_handles, ble_dfu_s::error_handler, ble_evt_t::evt, ble_evt_t::gatts_evt, ble_gatts_evt_write_t::handle, NRF_SUCCESS, on_ctrl_pt_write(), ble_gatts_evt_t::params, ble_gatts_evt_rw_authorize_request_t::request, ble_gatts_evt_rw_authorize_request_t::type, ble_gatts_char_handles_t::value_handle, and ble_gatts_evt_rw_authorize_request_t::write.
 {
     ble_gatts_evt_rw_authorize_request_t * p_authorize_request;
     p_authorize_request = &(p_ble_evt->evt.gatts_evt.params.authorize_request);
     if (
         (p_authorize_request->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
         &&
         (p_authorize_request->request.write.handle == p_dfu->dfu_ctrl_pt_handles.value_handle)
        )
     {
         uint32_t err_code;
         err_code = on_ctrl_pt_write(p_dfu, &(p_authorize_request->request.write));
         if (err_code != NRF_SUCCESS && p_dfu->error_handler != NULL)
         {
             p_dfu->error_handler(err_code);
         }
     }
 }
static void on_write (ble_dfu_t * p_dfu, ble_evt_t * p_ble_evt) static
Function for handling the BLE_GATTS_EVT_WRITE event from the S110 SoftDevice.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_ble_evt Pointer to the event received from BLE stack.
Definition at line 419 of file ble_dfu.c.
References ble_dfu_evt_t::ble_dfu_evt_type, BLE_DFU_PACKET_WRITE, ble_dfu_evt_t::ble_dfu_pkt_write, ble_gatts_evt_write_t::data, ble_dfu_s::dfu_pkt_handles, ble_dfu_evt_t::evt, ble_evt_t::evt, ble_dfu_s::evt_handler, ble_evt_t::gatts_evt, ble_gatts_evt_write_t::handle, ble_dfu_pkt_write_t::len, ble_gatts_evt_write_t::len, ble_dfu_pkt_write_t::p_data, ble_gatts_evt_t::params, ble_gatts_char_handles_t::value_handle, and ble_gatts_evt_t::write.
 {
     if (p_ble_evt->evt.gatts_evt.params.write.handle == p_dfu->dfu_pkt_handles.value_handle)
     {
         // DFU Packet written
         ble_dfu_evt_t ble_dfu_evt;
         ble_dfu_evt.ble_dfu_evt_type             = BLE_DFU_PACKET_WRITE;
         ble_dfu_evt.evt.ble_dfu_pkt_write.len    = p_ble_evt->evt.gatts_evt.params.write.len;
         ble_dfu_evt.evt.ble_dfu_pkt_write.p_data = p_ble_evt->evt.gatts_evt.params.write.data;
         p_dfu->evt_handler(p_dfu, &ble_dfu_evt);
     }
 }
static void on_disconnect (ble_dfu_t * p_dfu, ble_evt_t * p_ble_evt) static
Function for handling the BLE_GAP_EVT_DISCONNECTED event from the S110 SoftDevice.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_ble_evt Pointer to the event received from BLE stack.
Definition at line 441 of file ble_dfu.c.
References BLE_CONN_HANDLE_INVALID, and ble_dfu_s::conn_handle.
 {
     p_dfu->conn_handle = BLE_CONN_HANDLE_INVALID;
 }
Variable Documentation
bool m_is_dfu_service_initialized = false static
Variable to check if the DFU service was initialized by the application.
Definition at line 46 of file ble_dfu.c.
uint8_t m_notif_buffer[MAX_NOTIF_BUFFER_LEN] static
Buffer used for sending notifications to peer.
Definition at line 47 of file ble_dfu.c.