nRF51822 Beacon Firmware Documentation: components/libraries/bootloader_dfu/bootloader.c File Reference
bootloader.c File Reference
#include "bootloader.h"
#include <string.h>
#include "bootloader_types.h"
#include "bootloader_util.h"
#include "bootloader_settings.h"
#include "dfu.h"
#include "dfu_transport.h"
#include "nrf51.h"
#include "app_error.h"
#include "nrf_sdm.h"
#include "nordic_common.h"
#include "crc16.h"
#include "pstorage.h"
#include "app_scheduler.h"
#include "nrf_delay.h"
Macros
#define IRQ_ENABLED 0x01
#define MAX_NUMBER_INTERRUPTS 32
Enumerations
enum bootloader_status_t {
BOOTLOADER_UPDATING, BOOTLOADER_SETTINGS_SAVING, BOOTLOADER_COMPLETE, BOOTLOADER_TIMEOUT,
BOOTLOADER_RESET
}
Enumeration for specifying current bootloader status.
Functions
static void pstorage_callback_handler (pstorage_handle_t *p_handle, uint8_t op_code, uint32_t result, uint8_t *p_data, uint32_t data_len)
Function for handling callbacks from pstorage module.
static void wait_for_events (void)
Function for waiting for events.
bool bootloader_app_is_valid (uint32_t app_addr)
Function for validating application region in flash.
static void bootloader_settings_save (bootloader_settings_t *p_settings)
void bootloader_dfu_update_process (dfu_update_status_t update_status)
Function for processing DFU status update.
uint32_t bootloader_init (void)
Function for initializing the Bootloader.
uint32_t bootloader_dfu_start (void)
Function for starting the Device Firmware Update.
static void interrupts_disable (void)
Function for disabling all interrupts before jumping from bootloader to application.
void bootloader_app_start (uint32_t app_addr)
Function for exiting bootloader and booting into application.
bool bootloader_dfu_sd_in_progress (void)
Function getting state of SoftDevice update in progress. After a successfull SoftDevice transfer the system restarts in orderto disable SoftDevice and complete the update.
uint32_t bootloader_dfu_sd_update_continue (void)
Function for continuing the Device Firmware Update of a SoftDevice.
uint32_t bootloader_dfu_sd_update_finalize (void)
Function for finalizing the Device Firmware Update of a SoftDevice.
void bootloader_settings_get (bootloader_settings_t *const p_settings)
Function for retrieving the bootloader settings.
Variables
static pstorage_handle_t m_bootsettings_handle
static bootloader_status_t m_update_status
Macro Definition Documentation
#define IRQ_ENABLED 0x01
Field identifying if an interrupt is enabled.
Definition at line 29 of file bootloader.c.
#define MAX_NUMBER_INTERRUPTS 32
Maximum number of interrupts available.
Definition at line 30 of file bootloader.c.
Enumeration Type Documentation
enum bootloader_status_t
Enumeration for specifying current bootloader status.
Enumerator
BOOTLOADER_UPDATING
Bootloader status for indicating that an update is in progress.
BOOTLOADER_SETTINGS_SAVING
Bootloader status for indicating that saving of bootloader settings is in progress.
BOOTLOADER_COMPLETE
Bootloader status for indicating that all operations for the update procedure has completed and it is safe to reset the system.
BOOTLOADER_TIMEOUT
Bootloader status field for indicating that a timeout has occured and current update process should be aborted.
BOOTLOADER_RESET
Bootloader status field for indicating that a reset has been requested and current update process should be aborted.
Definition at line 34 of file bootloader.c.
 {
     BOOTLOADER_UPDATING,
     BOOTLOADER_SETTINGS_SAVING,
     BOOTLOADER_COMPLETE,
     BOOTLOADER_TIMEOUT,
     BOOTLOADER_RESET,
 } bootloader_status_t;
Function Documentation
static void pstorage_callback_handler (pstorage_handle_t * p_handle, uint8_t op_code, uint32_t result, uint8_t * p_data, uint32_t data_len) static
Function for handling callbacks from pstorage module.
Handles pstorage results for clear and storage operation. For detailed description of the parameters provided with the callback, please refer to pstorage_ntf_cb_t.
Definition at line 51 of file bootloader.c.
References BOOTLOADER_COMPLETE, BOOTLOADER_SETTINGS_SAVING, m_update_status, and PSTORAGE_STORE_OP_CODE.
 {
     // If we are in BOOTLOADER_SETTINGS_SAVING state and we receive an PSTORAGE_STORE_OP_CODE
     // response then settings has been saved and update has completed.
     if ((m_update_status == BOOTLOADER_SETTINGS_SAVING) && (op_code == PSTORAGE_STORE_OP_CODE))
     {
         m_update_status = BOOTLOADER_COMPLETE;
     }
     APP_ERROR_CHECK(result);
 }
static void wait_for_events (void) static
Function for waiting for events.
This function will place the chip in low power mode while waiting for events from the SoftDevice or other peripherals. When interrupted by an event, it will call the app_sched_execute function to process the received event. This function will return when the final state of the firmware update is reached OR when a tear down is in progress.
Definition at line 76 of file bootloader.c.
References app_sched_execute(), BOOTLOADER_COMPLETE, BOOTLOADER_RESET, BOOTLOADER_TIMEOUT, and m_update_status.
 {
     for (;;)
     {
         // Wait in low power state for any events.
         uint32_t err_code = sd_app_evt_wait();
         APP_ERROR_CHECK(err_code);
         // Event received. Process it from the scheduler.
         app_sched_execute();
         if ((m_update_status == BOOTLOADER_COMPLETE) ||
             (m_update_status == BOOTLOADER_TIMEOUT)  ||
             (m_update_status == BOOTLOADER_RESET))
         {
             // When update has completed or a timeout/reset occured we will return.
             return;
         }
     }
 }
static void bootloader_settings_save (bootloader_settings_t * p_settings) static
Definition at line 132 of file bootloader.c.
References m_bootsettings_handle, pstorage_clear(), and pstorage_store().
 {
     uint32_t err_code = pstorage_clear(&m_bootsettings_handle, sizeof(bootloader_settings_t));
     APP_ERROR_CHECK(err_code);
     err_code = pstorage_store(&m_bootsettings_handle,
                               (uint8_t *)p_settings,
                               sizeof(bootloader_settings_t),
                               0);
     APP_ERROR_CHECK(err_code);
 }
static void interrupts_disable (void) static
Function for disabling all interrupts before jumping from bootloader to application.
Definition at line 289 of file bootloader.c.
References IRQ_ENABLED, and MAX_NUMBER_INTERRUPTS.
 {
     uint32_t interrupt_setting_mask;
     uint32_t irq = 0; // We start from first interrupt, i.e. interrupt 0.
     // Fetch the current interrupt settings.
     interrupt_setting_mask = NVIC->ISER[0];
     for (; irq < MAX_NUMBER_INTERRUPTS; irq++)
     {
         if (interrupt_setting_mask & (IRQ_ENABLED << irq))
         {
             // The interrupt was enabled, and hence disable it.
             NVIC_DisableIRQ((IRQn_Type)irq);
         }
     }
 }
Variable Documentation
pstorage_handle_t m_bootsettings_handle static
Pstorage handle to use for registration and identifying the bootloader module on subsequent calls to the pstorage module for load and store of bootloader setting in flash.
Definition at line 43 of file bootloader.c.
bootloader_status_t m_update_status static
Current update status for the bootloader module to ensure correct behaviour when updating settings and when update completes.
Definition at line 44 of file bootloader.c.