nRF51822 Beacon Firmware Documentation: BleDfu Class Reference
BleDfu Class Reference
Public Member Functions
def __init__
def ProgressChanged
def data_received_handler
def setup_service
def get_uint32_from_intel_hex
def find_high_address
def char_string_to_hex_string
def wait_for_response
def dfu_send_image
Public Member Functions inherited from MasterEmulator
def __init__
def log_message_handler
def data_received_handler
def connected_handler
def disconnected_handler
def pipe_error_handler
def send_data
def setup_service
def set_local_data
def restore_bond_info
def filter_emulator_device
def change_byte_endianess
def scan_and_connect
def disconnect
Data Fields
hexfile_path
ready_to_send
send_crc
response_op_code_received
program_mode
updating_sd
updating_bl
updating_app
pipe_dfu_packet
pipe_dfu_control_point
pipe_dfu_control_point_notify
last_error
image_crc
Data Fields inherited from MasterEmulator
peer_device_address
num_of_errors
log_handler
connected
disconnect_event_expected
service_setup_done
last_disconnect_reason
baud_rate
own_address
bond_info
master
myPeerDevice
Static Public Attributes
tuple start_time = time.time()
int pkts_sent = 0
tuple hex_size = len(bin_array)
int data_packet_size = 20
int last_progress = 0
tuple progress = float(i)
last_progress = progress
list data_to_send = bin_array[i:i + data_packet_size]
tuple end_time = time.time()
Private Member Functions
def _get_softdevice_bin_array
def _get_bootloader_bin_array
def _get_application_bin_array
def _create_init_packet
def _create_binary_array
def _setup_dfu_sending
Detailed Description
Class to handle upload of a new hex image to the peer device.
Definition at line 92 of file ble_dfu.py.
Constructor & Destructor Documentation
def __init__ (self, peer_device_address, hexfile_path, baud_rate, program_mode, own_address = None, bond_info = None)
Definition at line 96 of file ble_dfu.py.
     def __init__(self, peer_device_address, hexfile_path, baud_rate, program_mode, own_address=None, bond_info=None):
         super(BleDfu, self).__init__(peer_device_address, baud_rate, own_address, bond_info)
         self.hexfile_path = hexfile_path
         self.ready_to_send = True
         self.send_crc = False
         self.response_op_code_received = -1
         self.program_mode = program_mode
         self.updating_sd = self.program_mode == DfuMode.SOFTDEVICE or self.program_mode == DfuMode.SdAndBl
         self.updating_bl = self.program_mode == DfuMode.BOOTLOADER or self.program_mode == DfuMode.SdAndBl
         self.updating_app = self.program_mode == DfuMode.APPLICATION
Member Function Documentation
def ProgressChanged (self, percent, message, finished = False)
Definition at line 110 of file ble_dfu.py.
     def ProgressChanged(self, percent, message, finished=False):
         pass
def data_received_handler (self, sender, e)
Handle received data from the peer device.
Note: This function overrides the parent class.
Definition at line 114 of file ble_dfu.py.
     def data_received_handler(self, sender, e):
         """ Handle received data from the peer device.
         Note: This function overrides the parent class.
         """
         if (e.PipeNumber == self.pipe_dfu_control_point_notify):
             op_code = int(e.PipeData[0])
             if op_code == OpCodes.PKT_RCPT_NOTIF:
                 if self.ready_to_send == True:
                     self.log_handler.log("ERROR: !!!! Pkt receipt notification received when it is not expected")
                 else:
                     self.log_handler.log("Pkt receipt notification received.")
                 self.log_handler.log("Number of bytes LSB = {0}".format(e.PipeData[1]))
                 self.log_handler.log("Number of bytes MSB = {0}".format(e.PipeData[2]))
                 self.ready_to_send = True
             elif op_code == OpCodes.RESPONSE:
                 request_op_code = int(e.PipeData[1])
                 response_value = int(e.PipeData[2])
                 self.log_handler.log("Response received for Request Op Code = {0}".format(request_op_code))
                 status_text = "UNKNOWN"
                 if status_code_lookup.has_key(response_value):
                     status_text = status_code_lookup[response_value]
                 if status_text != "SUCCESS":
                     last_error = status_text
                 if request_op_code == 1:
                     self.log_handler.log("Response for 'Start DFU' received - Status: %s" % status_text)
                 elif request_op_code == 2:
                     self.log_handler.log("Response for 'Initialize DFU Params' received - Status: %s" % status_text)
                 elif request_op_code == 3:
                     self.log_handler.log("Response for 'Receive FW Data' received - Status: %s" % status_text)
                 elif request_op_code == 4:
                     self.log_handler.log("Response for 'Validate' received - Status: %s" % status_text)
                 else:
                     self.log_handler.log("!!ERROR!! Response for Unknown command received.")
                 self.response_op_code_received = request_op_code
         else:
             self.log_handler.log("Received data on unexpected pipe %r"%e.PipeNumber)
def setup_service (self)
Set up DFU service database.
Definition at line 160 of file ble_dfu.py.
References dfu.ble_dfu.create_byte_array().
     def setup_service(self):
         """ Set up DFU service database. """
         # Add DFU Service
         self.master.SetupAddService(uuid_dfu_service, Nordicsemi.PipeStore.Remote)
         # Add DFU characteristics
         self.master.SetupAddCharacteristicDefinition(uuid_dfu_packet_characteristic, 2, create_byte_array(2))
         self.pipe_dfu_packet = self.master.SetupAssignPipe(Nordicsemi.PipeType.Transmit)
         self.master.SetupAddCharacteristicDefinition(uuid_dfu_control_state_characteristic, 2, create_byte_array(2))
         self.pipe_dfu_control_point = self.master.SetupAssignPipe(Nordicsemi.PipeType.TransmitWithAck)
         self.pipe_dfu_control_point_notify = self.master.SetupAssignPipe(Nordicsemi.PipeType.Receive)
def get_uint32_from_intel_hex (self, intel_hex, start_address)
Definition at line 174 of file ble_dfu.py.
     def get_uint32_from_intel_hex(self, intel_hex, start_address):
         value = 0
         for i in xrange(word_size):
             value += intel_hex[start_address + i] * 256**i
         return value
def find_high_address (self, intel_hex)
Definition at line 183 of file ble_dfu.py.
References BleDfu.get_uint32_from_intel_hex().
     def find_high_address(self, intel_hex):
         max_address = intel_hex.maxaddr() + 1
         #Rounding up to closest page start.
         #Because of 0-indexing address "page_size" should be rounded up to 2*page_size.
         max_address = ((max_address)/page_size + 1) * page_size
         if max_address < 0x100000:
             return max_address
         max_address = 0x100000
         while max_address >= 0:
             last_value = self.get_uint32_from_intel_hex(intel_hex, max_address)
             if last_value != 0xFFFFFFFF:
                 max_address += page_size
                 break;
             else:
                 max_address -= page_size
         return max_address
def char_string_to_hex_string (self, string)
Definition at line 206 of file ble_dfu.py.
     def char_string_to_hex_string(self, string):
         converted_string = ''
         for character in string[::-1]:
             hex_fragment = hex(ord(character))[2:]
             if len(hex_fragment) == 1:
                 hex_fragment = '0' + hex_fragment
             converted_string += hex_fragment
         return converted_string
def _get_softdevice_bin_array (self, intel_hex) private
Definition at line 218 of file ble_dfu.py.
References BleDfu.get_uint32_from_intel_hex().
     def _get_softdevice_bin_array(self, intel_hex):
         sd_bin_array = None
         try:
             sd_magic_value_address = 0x3004
             expected_magic_value = 0x51B1E5DB
             sd_magic_value = self.get_uint32_from_intel_hex(intel_hex, sd_magic_value_address)
             if sd_magic_value == expected_magic_value:
                 sd_end_address_address = 0x3008
                 sd_end_address = self.get_uint32_from_intel_hex(intel_hex, sd_end_address_address)
                 address_after_mbr_page = 0x1000
                 sd_last_byte_address = sd_end_address - 1
                 sd_bin_array = intel_hex.tobinarray(start = address_after_mbr_page,
                                                     end = sd_last_byte_address)
         except Exception, e:
             #Something is WRONG!
             pass
         return sd_bin_array
def _get_bootloader_bin_array (self, intel_hex) private
Definition at line 240 of file ble_dfu.py.
References BleDfu.find_high_address(), and BleDfu.get_uint32_from_intel_hex().
     def _get_bootloader_bin_array(self, intel_hex):
         bl_bin_array = None
         bl_start_address = 0x30000
         max_bl_start_address = 0x80000
         while bl_start_address < max_bl_start_address:
             init_stack_pointer = self.get_uint32_from_intel_hex(intel_hex, bl_start_address)
             stack_start_address = 0x20000000
             if init_stack_pointer != 0xFFFFFFFF:
                 if init_stack_pointer > stack_start_address:
                     break
             bl_start_address = bl_start_address + page_size
         bl_end_address = self.find_high_address(intel_hex)
         bl_last_byte_address = bl_end_address - 1
         bl_bin_array = intel_hex.tobinarray(start = bl_start_address, end = bl_last_byte_address)
         return bl_bin_array
def _get_application_bin_array (self, intel_hex) private
Definition at line 263 of file ble_dfu.py.
References BleDfu.find_high_address().
     def _get_application_bin_array(self, intel_hex):
         app_start_address = 0xFFFFFFFF
         app_start_address = intel_hex.minaddr()
         app_end_address = self.find_high_address(intel_hex)
         app_bin_array = intel_hex.tobinarray(start = app_start_address, end = (app_end_address - 1))
         return app_bin_array
def _create_init_packet (self, init_packet) private
Definition at line 273 of file ble_dfu.py.
     def _create_init_packet(self, init_packet):
         hardware_version = [0xFF, 0xFF]
         hardware_revision = [0xFF, 0xFF]
         application_version = [0xFF, 0xFF, 0xFF, 0xFF]
         softdevice_len = [0x01, 0x00]
         softdevice_array = [0xFE, 0xFF]
         init_packet.extend(hardware_version)
         init_packet.extend(hardware_revision)
         init_packet.extend(application_version)
         init_packet.extend(softdevice_len)
         init_packet.extend(softdevice_array)
def _create_binary_array (self, image_size_packet, bin_array) private
Definition at line 286 of file ble_dfu.py.
References BleDfu._get_application_bin_array(), BleDfu._get_bootloader_bin_array(), BleDfu._get_softdevice_bin_array(), dfu.ble_dfu.convert_uint32_to_array(), BleDfu.hexfile_path, BleDfu.updating_app, BleDfu.updating_bl, and BleDfu.updating_sd.
     def _create_binary_array(self, image_size_packet, bin_array):
         padding = [0x00] * 4
         # Open the hex file to be sent
         intel_hex = IntelHex(self.hexfile_path)
         if self.updating_sd:
             sd_bin_array = self._get_softdevice_bin_array(intel_hex)
             if sd_bin_array:
                 sd_hex_size_array_lsb = convert_uint32_to_array(len(sd_bin_array))
                 image_size_packet.extend(sd_hex_size_array_lsb)
                 bin_array.extend(sd_bin_array)
         expected_image_size_packet_size = 4
         if len(image_size_packet) < expected_image_size_packet_size:
             image_size_packet.extend(padding)
         if self.updating_bl:
             bl_bin_array = self._get_bootloader_bin_array(intel_hex)
             if bl_bin_array:
                 bl_hex_size_array_lsb = convert_uint32_to_array(len(bl_bin_array))
                 image_size_packet.extend(bl_hex_size_array_lsb)
                 bin_array.extend(bl_bin_array)
         expected_image_size_packet_size = 8
         if len(image_size_packet) < expected_image_size_packet_size:
             image_size_packet.extend(padding)
         if self.updating_app:
             app_bin_array = self._get_application_bin_array(intel_hex)
             if app_bin_array:
                 app_hex_size_array_lsb = convert_uint32_to_array(len(app_bin_array))
                 image_size_packet.extend(app_hex_size_array_lsb)
                 bin_array.extend(app_bin_array)
         expected_image_size_packet_size = 12
         if len(image_size_packet) < expected_image_size_packet_size:
             image_size_packet.extend(padding)
def _setup_dfu_sending (self, image_size_packet, init_packet) private
Definition at line 332 of file ble_dfu.py.
References dfu.ble_dfu.convert_uint16_to_array(), BleDfu.pipe_dfu_control_point, BleDfu.pipe_dfu_control_point_notify, BleDfu.pipe_dfu_packet, BleDfu.program_mode, BleDfu.ProgressChanged(), MasterEmulator.send_data(), and BleDfu.wait_for_response().
     def _setup_dfu_sending(self, image_size_packet, init_packet):
         try:
             self.master.OpenRemotePipe(self.pipe_dfu_control_point_notify)
         except Exception, e:
             self.ProgressChanged(0, "Device does not have the required DFU service.", True)
             return False
         if num_of_packets_between_notif:
             # Subscribing for packet receipt notifications
             self.send_data(self.pipe_dfu_control_point,
                            System.Array[System.Byte]([OpCodes.REQ_PKT_RCPT_NOTIF] + convert_uint16_to_array(num_of_packets_between_notif)),
                            num_of_send_tries,
                            "Enabling Packet receipt notifications from peer device")
         # Sending 'START DFU' command
         self.send_data(self.pipe_dfu_control_point,
                        System.Array[System.Byte]([OpCodes.START_DFU, self.program_mode]),
                        num_of_send_tries,
                        "Sending 'START DFU' command")
         # Sending image size
         self.send_data(self.pipe_dfu_packet,
                        System.Array[System.Byte](image_size_packet),
                        num_of_send_tries,
                        "Sending image size")
         self.wait_for_response(OpCodes.START_DFU)
         time.sleep(10)
         # Sending 'Init packet' command
         self.send_data(self.pipe_dfu_control_point,
                        System.Array[System.Byte]([OpCodes.INITIALIZE_DFU, 0x00]),
                        num_of_send_tries,
                        "Sending 'INIT DFU' command")
         # Sending init data
         self.send_data(self.pipe_dfu_packet,
                        System.Array[System.Byte](init_packet),
                        num_of_send_tries,
                        "Sending init data")
         self.send_data(self.pipe_dfu_control_point,
                        System.Array[System.Byte]([OpCodes.INITIALIZE_DFU, 0x01]),
                        num_of_send_tries,
                        "Sending 'Init Packet Complete' command")
         self.wait_for_response(OpCodes.INITIALIZE_DFU)
         # Send number of packets to receive before sending notification
         self.send_data(self.pipe_dfu_control_point,
                        System.Array[System.Byte]([0x08, 0x0A, 0x00]),
                        num_of_send_tries,
                        "Send number of packets before device sends notification")
         # Send 'RECEIVE FIRMWARE IMAGE' command to set DFU in firmware receive state.
         self.send_data(self.pipe_dfu_control_point,
                        System.Array[System.Byte]([OpCodes.RECEIVE_FIRMWARE_IMAGE]),
                        num_of_send_tries,
                        "Send 'RECEIVE FIRMWARE IMAGE' command")
         if last_error != "SUCCESS":
             self.ProgressChanged(0, "Error received from device while setting up DFU: %s" % last_error, True)
             return False
         return True
def wait_for_response (self, op_code)
Definition at line 401 of file ble_dfu.py.
References BleDfu.response_op_code_received.
     def wait_for_response(self, op_code):
         timeout = 2
         start_time = datetime.now()
         while self.response_op_code_received != op_code:
             timedOut = datetime.now() - start_time > timedelta(0, timeout)
             if timedOut:
                 self.last_error = "Timeout while waiting for response from device."
                 return
             time.sleep(0.1)
         self.response_op_code_received = -1
def dfu_send_image (self)
Send hex to peer in chunks of 20 bytes.
Definition at line 415 of file ble_dfu.py.
References BleDfu._create_binary_array(), and MasterEmulator.connected.
     def dfu_send_image(self):
         """ Send hex to peer in chunks of 20 bytes. """
         if not self.connected:
             return
         image_size_packet = []
         init_packet = []
         bin_array = []
         self._create_binary_array(image_size_packet, bin_array)
         self.image_crc = calc_crc16(bin_array)
Field Documentation
tuple start_time = time.time() static
Definition at line 432 of file ble_dfu.py.
int pkts_sent = 0 static
Definition at line 438 of file ble_dfu.py.
tuple hex_size = len(bin_array) static
Definition at line 443 of file ble_dfu.py.
int data_packet_size = 20 static
Definition at line 444 of file ble_dfu.py.
int last_progress = 0 static
Definition at line 448 of file ble_dfu.py.
tuple progress = float(i) static
Definition at line 449 of file ble_dfu.py.
last_progress = progress static
Definition at line 453 of file ble_dfu.py.
list data_to_send = bin_array[i:i + data_packet_size] static
Definition at line 463 of file ble_dfu.py.
tuple end_time = time.time() static
Definition at line 494 of file ble_dfu.py.
hexfile_path
Definition at line 99 of file ble_dfu.py.
ready_to_send
Definition at line 100 of file ble_dfu.py.
send_crc
Definition at line 101 of file ble_dfu.py.
response_op_code_received
Definition at line 102 of file ble_dfu.py.
program_mode
Definition at line 103 of file ble_dfu.py.
updating_sd
Definition at line 105 of file ble_dfu.py.
updating_bl
Definition at line 106 of file ble_dfu.py.
updating_app
Definition at line 107 of file ble_dfu.py.
pipe_dfu_packet
Definition at line 167 of file ble_dfu.py.
pipe_dfu_control_point
Definition at line 170 of file ble_dfu.py.
pipe_dfu_control_point_notify
Definition at line 171 of file ble_dfu.py.
last_error
Definition at line 408 of file ble_dfu.py.
image_crc
Definition at line 426 of file ble_dfu.py.
The documentation for this class was generated from the following file:
nrf51_beacon/ble_app_beacon_dfu/ble_dfu_send_hex/dfu/ble_dfu.py