nRF51822 Beacon Firmware Documentation: components/libraries/bootloader_dfu/experimental/dfu_app_handler.c File Reference
dfu_app_handler.c File Reference
#include <string.h>
#include "dfu_app_handler.h"
#include "bootloader_util.h"
#include "nrf.h"
#include "nrf_sdm.h"
#include "ble_gatts.h"
#include "app_error.h"
#include "dfu_ble_svc.h"
#include "device_manager.h"
Macros
#define IRQ_ENABLED 0x01
#define MAX_NUMBER_INTERRUPTS 32
Functions
static void dfu_app_reset_prepare (void)
Default reset prepare handler if application hasn't registered a handler.
static void interrupts_disable (void)
Function for disabling all interrupts before jumping from bootloader to application.
static void dfu_app_set_peer_data (void)
Function for providing peer information to DFU for re-establishing bonded connection in DFU mode.
static void bootloader_start (void)
Function for preparing the reset, disabling SoftDevice and jump to the bootloader.
void dfu_app_on_dfu_evt (ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
Function for handling of ble_dfu_evt_t from DFU Service.
void dfu_app_reset_prepare_set (dfu_app_reset_prepare_t reset_prepare_func)
Function for registering for reset prepare calls.
void dfu_app_set_dm_handle (dm_handle_t const *p_dm_handle)
Function for setting Device manager handle for current BLE connection.
Variables
static dfu_app_reset_prepare_t m_reset_prepare = dfu_app_reset_prepare
static dfu_ble_peer_data_t m_peer_data
static dm_handle_t m_dm_handle
static bool m_dm_handle_valid = false
Macro Definition Documentation
#define IRQ_ENABLED 0x01
Field identifying if an interrupt is enabled.
Definition at line 23 of file dfu_app_handler.c.
#define MAX_NUMBER_INTERRUPTS 32
Maximum number of interrupts available.
Definition at line 24 of file dfu_app_handler.c.
Function Documentation
static void dfu_app_reset_prepare (void) static
Default reset prepare handler if application hasn't registered a handler.
Forward declare of default reset handler.
Definition at line 35 of file dfu_app_handler.c.
 {
     // Reset prepare should be handled by application.
     // This function can be extended to include default handling if application does not implement
     // own handler.
 }
static void interrupts_disable (void) static
Function for disabling all interrupts before jumping from bootloader to application.
Definition at line 45 of file dfu_app_handler.c.
References IRQ_ENABLED, and MAX_NUMBER_INTERRUPTS.
 {
     uint32_t interrupt_setting_mask;
     uint32_t irq = 0; // We start from first interrupt, i.e. interrupt 0.
     // Fetch the current interrupt settings.
     interrupt_setting_mask = NVIC->ISER[0];
     for (; irq < MAX_NUMBER_INTERRUPTS; irq++)
     {
         if (interrupt_setting_mask & (IRQ_ENABLED << irq))
         {
             // The interrupt was enabled, and hence disable it.
             NVIC_DisableIRQ((IRQn_Type)irq);
         }
     }
 }
static void dfu_app_set_peer_data (void) static
Function for providing peer information to DFU for re-establishing bonded connection in DFU mode.
[DFU bond sharing]
[DFU bond sharing]
Definition at line 67 of file dfu_app_handler.c.
References dfu_ble_peer_data_t::addr, dfu_ble_peer_data_t::enc_info, dfu_ble_peer_data_t::irk, m_dm_handle, and m_peer_data.
 {
     uint32_t        err_code;
     dm_sec_keyset_t key_set;
     err_code = dm_distributed_keys_get(&m_dm_handle, &key_set);
     APP_ERROR_CHECK(err_code);
     m_peer_data.addr     = key_set.keys_central.p_id_key->id_addr_info;
     m_peer_data.enc_info = *key_set.keys_central.enc_key.p_enc_info;
     m_peer_data.irk      = key_set.keys_central.p_id_key->id_info;
     err_code = dfu_ble_svc_set_peer_data(&m_peer_data);
     APP_ERROR_CHECK(err_code);
 }
static void bootloader_start (void) static
Function for preparing the reset, disabling SoftDevice and jump to the bootloader.
Definition at line 88 of file dfu_app_handler.c.
References BOOTLOADER_DFU_START, bootloader_util_app_start(), dfu_app_set_peer_data(), interrupts_disable(), m_dm_handle_valid, m_reset_prepare, NRF_UICR, and SWI2_IRQn.
 {
     m_reset_prepare();
     uint32_t err_code = sd_power_gpregret_set(BOOTLOADER_DFU_START);
     APP_ERROR_CHECK(err_code);
     err_code = sd_softdevice_disable();
     APP_ERROR_CHECK(err_code);
     err_code = sd_softdevice_vector_table_base_set(NRF_UICR->BOOTLOADERADDR);
     APP_ERROR_CHECK(err_code);
     if (m_dm_handle_valid)
     {
         dfu_app_set_peer_data();
     }
     NVIC_ClearPendingIRQ(SWI2_IRQn);
     interrupts_disable();
     bootloader_util_app_start(NRF_UICR->BOOTLOADERADDR);
 }
Variable Documentation
dfu_app_reset_prepare_t m_reset_prepare = dfu_app_reset_prepare static
Callback function to application to prepare for system reset. Allows application to cleanup of service and memory prior to reset.
Definition at line 27 of file dfu_app_handler.c.
dfu_ble_peer_data_t m_peer_data static
Peer data to be used for data exchange when reseting into DFU mode.
Definition at line 28 of file dfu_app_handler.c.
dm_handle_t m_dm_handle static
Device Manager handle with instance id's of current BLE connection.
Definition at line 29 of file dfu_app_handler.c.
bool m_dm_handle_valid = false static
Variable indicating if the Device Manager handle is valid.
Definition at line 30 of file dfu_app_handler.c.