nRF51822 Beacon Firmware Documentation: nrf51_beacon/common/sdk_modified/dfu_dual_bank/dfu_dual_bank_mod.c File Reference
dfu_dual_bank_mod.c File Reference
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "dfu.h"
#include "dfu_types.h"
#include "dfu_bank_internal.h"
#include "nrf.h"
#include "nrf51.h"
#include "nrf51_bitfields.h"
#include "app_util.h"
#include "nrf_sdm.h"
#include "app_error.h"
#include "nrf_error.h"
#include "app_timer.h"
#include "nordic_common.h"
#include "bootloader.h"
#include "bootloader_types.h"
#include "pstorage.h"
#include "nrf_mbr.h"
#include "dfu_init.h"
Functions
static void pstorage_callback_handler (pstorage_handle_t *p_handle, uint8_t op_code, uint32_t result, uint8_t *p_data, uint32_t data_len)
Function for handling callbacks from pstorage module.
static void dfu_timeout_handler (void *p_context)
Function for handling the DFU timeout.
static uint32_t dfu_timer_restart (void)
Function for restarting the DFU Timer.
static void dfu_prepare_func_app_erase (uint32_t image_size)
Function for preparing of flash before receiving SoftDevice image.
static void dfu_prepare_func_swap_erase (uint32_t image_size)
Function for preparing swap before receiving application or bootloader image.
static void dfu_cleared_func_swap (void)
Function for handling behaviour when clear operation has completed.
static void dfu_cleared_func_app (void)
Function for handling behaviour when clear operation has completed.
uint32_t offset_calculate (uint32_t sd_image_size)
Function for calculating storage offset for receiving SoftDevice image.
static uint32_t dfu_activate_sd (void)
Function for activating received SoftDevice image.
static uint32_t dfu_activate_app (void)
Function for activating received Application image.
static uint32_t dfu_activate_bl (void)
Function for activating received Bootloader image.
uint32_t dfu_init (void)
Function for initializing the Device Firmware Update module.
void dfu_register_callback (dfu_callback_t callback_handler)
Function for registering a callback listener for dfu_data_pkt_handle callbacks.
uint32_t dfu_start_pkt_handle (dfu_update_packet_t *p_packet)
Function for setting the DFU image size.
uint32_t dfu_data_pkt_handle (dfu_update_packet_t *p_packet)
Function for handling DFU data packets.
uint32_t dfu_init_pkt_complete (void)
Function for handling DFU init packet complete.
uint32_t dfu_init_pkt_handle (dfu_update_packet_t *p_packet)
Function for handling DFU init packets.
uint32_t dfu_image_validate ()
Function for validating a transferred image after the transfer has completed.
uint32_t dfu_image_activate ()
Function for activating the transfered image after validation has successfully completed.
void dfu_reset (void)
Function for reseting the current update procedure and return to initial state.
static uint32_t dfu_compare_block (uint32_t *ptr1, uint32_t *ptr2, uint32_t len)
static uint32_t dfu_copy_sd (uint32_t *src, uint32_t *dst, uint32_t len)
static uint32_t dfu_sd_img_block_swap (uint32_t *src, uint32_t *dst, uint32_t len, uint32_t block_size)
uint32_t dfu_sd_image_swap (void)
Function for swapping existing SoftDevice with newly received.
uint32_t dfu_bl_image_swap (void)
Function for swapping existing bootloader with newly received.
uint32_t dfu_bl_image_validate (void)
Function for validating that new bootloader has been correctly installed.
uint32_t dfu_sd_image_validate (void)
Function for validating that new SoftDevicehas been correctly installed.
Variables
static dfu_state_t m_dfu_state
static uint32_t m_image_size
static dfu_start_packet_t m_start_packet
static uint8_t m_init_packet [64]
static uint8_t m_init_packet_length
static uint16_t m_image_crc
static app_timer_id_t m_dfu_timer_id
static bool m_dfu_timed_out = false
static pstorage_handle_t m_storage_handle_swap
static pstorage_handle_t m_storage_handle_app
static pstorage_handle_t * mp_storage_handle_active
static dfu_callback_t m_data_pkt_cb
static dfu_bank_func_t m_functions
Function Documentation
static void pstorage_callback_handler (pstorage_handle_t * p_handle, uint8_t op_code, uint32_t result, uint8_t * p_data, uint32_t data_len) static
Function for handling callbacks from pstorage module.
Handles pstorage results for clear and storage operation. For detailed description of the parameters provided with the callback, please refer to pstorage_ntf_cb_t.
Definition at line 59 of file dfu_dual_bank_mod.c.
References dfu_bank_func_t::cleared, DATA_PACKET, DFU_STATE_PREPARING, DFU_STATE_RDY, DFU_STATE_RX_DATA_PKT, m_data_pkt_cb, m_dfu_state, PSTORAGE_CLEAR_OP_CODE, PSTORAGE_STORE_OP_CODE, and START_PACKET.
 {
     switch (op_code)
     {
         case PSTORAGE_STORE_OP_CODE:
             if ((m_dfu_state == DFU_STATE_RX_DATA_PKT) && (m_data_pkt_cb != NULL))
             {
                 m_data_pkt_cb(DATA_PACKET, result, p_data);
             }
             break;
         case PSTORAGE_CLEAR_OP_CODE:
             if (m_dfu_state == DFU_STATE_PREPARING)
             {
                 m_functions.cleared();
                 m_dfu_state = DFU_STATE_RDY;
                 if (m_data_pkt_cb != NULL)
                 {
                     m_data_pkt_cb(START_PACKET, result, p_data);
                 }
             }
             break;
         default:
             break;
     }
     APP_ERROR_CHECK(result);
 }
static void dfu_timeout_handler (void * p_context) static
Function for handling the DFU timeout.
Parameters
[in] p_context The timeout context.
Definition at line 97 of file dfu_dual_bank_mod.c.
References bootloader_dfu_update_process(), DFU_TIMEOUT, m_dfu_timed_out, and dfu_update_status_t::status_code.
 {
     UNUSED_PARAMETER(p_context);
     dfu_update_status_t update_status;
     m_dfu_timed_out           = true;
     update_status.status_code = DFU_TIMEOUT;
     bootloader_dfu_update_process(update_status);
 }
static uint32_t dfu_timer_restart (void) static
Function for restarting the DFU Timer.
This function will stop and restart the DFU timer. This function will be called by the functions handling any DFU packet received from the peer that is transferring a firmware image.
Definition at line 115 of file dfu_dual_bank_mod.c.
References app_timer_start(), app_timer_stop(), DFU_TIMEOUT_INTERVAL, m_dfu_timed_out, m_dfu_timer_id, and NRF_ERROR_INVALID_STATE.
 {
     if (m_dfu_timed_out)
     {
         // The DFU timer had already timed out.
         return NRF_ERROR_INVALID_STATE;
     }
     uint32_t err_code = app_timer_stop(m_dfu_timer_id);
     APP_ERROR_CHECK(err_code);
     err_code = app_timer_start(m_dfu_timer_id, DFU_TIMEOUT_INTERVAL, NULL);
     APP_ERROR_CHECK(err_code);
     return err_code;
 }
static void dfu_prepare_func_app_erase (uint32_t image_size) static
Function for preparing of flash before receiving SoftDevice image.
This function will erase current application area to ensure sufficient amount of storage for the SoftDevice image. Upon erase complete a callback will be done. See dfu_bank_prepare_t for further details.
Definition at line 139 of file dfu_dual_bank_mod.c.
References DFU_STATE_PREPARING, m_dfu_state, m_image_size, m_storage_handle_app, and mp_storage_handle_active.
 {
     uint32_t err_code;
     mp_storage_handle_active = &m_storage_handle_app;
     // Doing a SoftDevice update thus current application must be cleared to ensure enough space
     // for new SoftDevice.
     m_dfu_state = DFU_STATE_PREPARING;
     err_code    = pstorage_raw_clear(&m_storage_handle_app, m_image_size);
     APP_ERROR_CHECK(err_code);
 }
static void dfu_prepare_func_swap_erase (uint32_t image_size) static
Function for preparing swap before receiving application or bootloader image.
This function will erase current swap area to ensure flash is ready for storage of the Application or Bootloader image. Upon erase complete a callback will be done. See dfu_bank_prepare_t for further details.
Definition at line 159 of file dfu_dual_bank_mod.c.
References DFU_IMAGE_MAX_SIZE_BANKED, DFU_STATE_PREPARING, m_dfu_state, m_storage_handle_swap, and mp_storage_handle_active.
 {
     uint32_t err_code;
     mp_storage_handle_active = &m_storage_handle_swap;
     m_dfu_state = DFU_STATE_PREPARING;
     err_code    = pstorage_raw_clear(&m_storage_handle_swap, DFU_IMAGE_MAX_SIZE_BANKED);
     APP_ERROR_CHECK(err_code);
 }
static void dfu_cleared_func_swap (void) static
Function for handling behaviour when clear operation has completed.
Definition at line 173 of file dfu_dual_bank_mod.c.
 {
 //    dfu_update_status_t update_status = {DFU_BANK_1_ERASED, };
 //    bootloader_dfu_update_process(update_status);
 }
static void dfu_cleared_func_app (void) static
Function for handling behaviour when clear operation has completed.
Definition at line 182 of file dfu_dual_bank_mod.c.
References bootloader_dfu_update_process(), and DFU_BANK_0_ERASED.
 {
     dfu_update_status_t update_status = {DFU_BANK_0_ERASED, };
     bootloader_dfu_update_process(update_status);
 }
uint32_t offset_calculate (uint32_t sd_image_size)
Function for calculating storage offset for receiving SoftDevice image.
When a new SoftDevice is received it will be temporary stored in flash before moved to address 0x0. In order to succesfully validate transfer and relocation it is important that temporary image and final installed image does not ovwerlap hence an offset must be calculated in case new image is larger than currently installed SoftDevice.
Definition at line 196 of file dfu_dual_bank_mod.c.
References CODE_PAGE_SIZE, DFU_BANK_0_REGION_START, and dfu_start_packet_t::sd_image_size.
 {
     uint32_t offset = 0;
     if (m_start_packet.sd_image_size > DFU_BANK_0_REGION_START)
     {
         uint32_t page_mask = (CODE_PAGE_SIZE - 1);
         uint32_t diff = m_start_packet.sd_image_size - DFU_BANK_0_REGION_START;
         offset = diff & ~page_mask;
         // Align offset to next page if image size is not page sized.
         if ((diff & page_mask) > 0)
         {
             offset += CODE_PAGE_SIZE;
         }
     }
     return offset;
 }
static uint32_t dfu_activate_sd (void) static
Function for activating received SoftDevice image.
Note
This function will not move the SoftDevice image. The bootloader settings will be marked as SoftDevice update complete and the swapping of current SoftDevice will occur after system reset.
Returns
NRF_SUCCESS on success.
Definition at line 226 of file dfu_dual_bank_mod.c.
References dfu_update_status_t::app_crc, dfu_start_packet_t::app_image_size, dfu_update_status_t::app_size, dfu_start_packet_t::bl_image_size, dfu_update_status_t::bl_size, bootloader_dfu_update_process(), DFU_BANK_0_REGION_START, DFU_UPDATE_SD_COMPLETE, m_image_crc, NRF_SUCCESS, dfu_start_packet_t::sd_image_size, dfu_update_status_t::sd_image_start, dfu_update_status_t::sd_size, and dfu_update_status_t::status_code.
 {
     dfu_update_status_t update_status;
     update_status.status_code    = DFU_UPDATE_SD_COMPLETE;
     update_status.app_crc        = m_image_crc;
     update_status.sd_image_start = DFU_BANK_0_REGION_START;
     update_status.sd_size        = m_start_packet.sd_image_size;
     update_status.bl_size        = m_start_packet.bl_image_size;
     update_status.app_size       = m_start_packet.app_image_size;
     bootloader_dfu_update_process(update_status);
     return NRF_SUCCESS;
 }
static uint32_t dfu_activate_app (void) static
Function for activating received Application image.
This function will move the received application image fram swap (bank 1) to application area (bank 0).
Returns
NRF_SUCCESS on success. Error code otherwise.
Definition at line 250 of file dfu_dual_bank_mod.c.
References dfu_update_status_t::app_crc, dfu_start_packet_t::app_image_size, dfu_update_status_t::app_size, bootloader_dfu_update_process(), DFU_UPDATE_APP_COMPLETE, m_image_crc, m_storage_handle_app, m_storage_handle_swap, NRF_SUCCESS, and dfu_update_status_t::status_code.
 {
     uint32_t err_code;
     // Erase BANK 0.
     err_code = pstorage_raw_clear(&m_storage_handle_app, m_start_packet.app_image_size);
     APP_ERROR_CHECK(err_code);
     err_code = pstorage_raw_store(&m_storage_handle_app,
                                   (uint8_t *)m_storage_handle_swap.block_id,
                                   m_start_packet.app_image_size,
                                   0);
     if (err_code == NRF_SUCCESS)
     {
         dfu_update_status_t update_status;
         memset(&update_status, 0, sizeof(dfu_update_status_t ));
         update_status.status_code = DFU_UPDATE_APP_COMPLETE;
         update_status.app_crc     = m_image_crc;
         update_status.app_size    = m_start_packet.app_image_size;
         bootloader_dfu_update_process(update_status);
     }
     return err_code;
 }
static uint32_t dfu_activate_bl (void) static
Function for activating received Bootloader image.
Note
This function will not move the bootloader image. The bootloader settings will be marked as Bootloader update complete and the swapping of current bootloader will occur after system reset.
Returns
NRF_SUCCESS on success.
Definition at line 287 of file dfu_dual_bank_mod.c.
References dfu_update_status_t::app_crc, dfu_start_packet_t::app_image_size, dfu_update_status_t::app_size, dfu_start_packet_t::bl_image_size, dfu_update_status_t::bl_size, bootloader_dfu_update_process(), DFU_UPDATE_BOOT_COMPLETE, m_image_crc, NRF_SUCCESS, dfu_start_packet_t::sd_image_size, dfu_update_status_t::sd_size, and dfu_update_status_t::status_code.
 {
     dfu_update_status_t update_status;
     update_status.status_code = DFU_UPDATE_BOOT_COMPLETE;
     update_status.app_crc     = m_image_crc;
     update_status.sd_size     = m_start_packet.sd_image_size;
     update_status.bl_size     = m_start_packet.bl_image_size;
     update_status.app_size    = m_start_packet.app_image_size;
     bootloader_dfu_update_process(update_status);
     return NRF_SUCCESS;
 }
static uint32_t dfu_compare_block (uint32_t * ptr1, uint32_t * ptr2, uint32_t len) static
Definition at line 663 of file dfu_dual_bank_mod.c.
References sd_mbr_command_t::command, sd_mbr_command_t::compare, sd_mbr_command_compare_t::len, sd_mbr_command_t::params, sd_mbr_command_compare_t::ptr1, sd_mbr_command_compare_t::ptr2, and SD_MBR_COMMAND_COMPARE.
 {
     sd_mbr_command_t sd_mbr_cmd;
     sd_mbr_cmd.command             = SD_MBR_COMMAND_COMPARE;
     sd_mbr_cmd.params.compare.ptr1 = ptr1;
     sd_mbr_cmd.params.compare.ptr2 = ptr2;
     sd_mbr_cmd.params.compare.len  = len / sizeof(uint32_t);
     return sd_mbr_command(&sd_mbr_cmd);
 }
static uint32_t dfu_copy_sd (uint32_t * src, uint32_t * dst, uint32_t len) static
Definition at line 676 of file dfu_dual_bank_mod.c.
References sd_mbr_command_t::command, sd_mbr_command_t::copy_sd, sd_mbr_command_copy_sd_t::dst, sd_mbr_command_copy_sd_t::len, sd_mbr_command_t::params, SD_MBR_COMMAND_COPY_SD, and sd_mbr_command_copy_sd_t::src.
 {
     sd_mbr_command_t sd_mbr_cmd;
     sd_mbr_cmd.command            = SD_MBR_COMMAND_COPY_SD;
     sd_mbr_cmd.params.copy_sd.src = src;
     sd_mbr_cmd.params.copy_sd.dst = dst;
     sd_mbr_cmd.params.copy_sd.len = len / sizeof(uint32_t);
     return sd_mbr_command(&sd_mbr_cmd);
 }
static uint32_t dfu_sd_img_block_swap (uint32_t * src, uint32_t * dst, uint32_t len, uint32_t block_size) static
Definition at line 689 of file dfu_dual_bank_mod.c.
References dfu_compare_block(), dfu_copy_sd(), NRF_SUCCESS, and SOFTDEVICE_REGION_START.
 {
     // It is neccesarry to swap the new SoftDevice in 3 rounds to ensure correct copy of data
     // and verifucation of data in case power reset occurs during write to flash.
     // To ensure the robustness of swapping the images are compared backwards till start of
     // image swap. If the back is identical everything is swapped.
     uint32_t err_code = dfu_compare_block(src, dst, len);
     if (err_code == NRF_SUCCESS)
     {
         return err_code;
     }
     if ((uint32_t)dst > SOFTDEVICE_REGION_START)
     {
         err_code = dfu_sd_img_block_swap((uint32_t *)((uint32_t)src - block_size),
                                          (uint32_t *)((uint32_t)dst - block_size),
                                          block_size,
                                          block_size);
         if (err_code != NRF_SUCCESS)
         {
             return err_code;
         }
     }
     err_code = dfu_copy_sd(src, dst, len);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     return dfu_compare_block(src, dst, len);
 }
Variable Documentation
dfu_state_t m_dfu_state static
Current DFU state.
Definition at line 35 of file dfu_dual_bank_mod.c.
uint32_t m_image_size static
Size of the image that will be transmitted.
Definition at line 36 of file dfu_dual_bank_mod.c.
dfu_start_packet_t m_start_packet static
Start packet received for this update procedure. Contains update mode and image sizes information to be used for image transfer.
Definition at line 38 of file dfu_dual_bank_mod.c.
uint8_t m_init_packet[64] static
Init packet, can hold CRC, Hash, Signed Hash and similar, for image validation, integrety check and authorization checking.
Definition at line 39 of file dfu_dual_bank_mod.c.
uint8_t m_init_packet_length static
Length of init packet received.
Definition at line 40 of file dfu_dual_bank_mod.c.
uint16_t m_image_crc static
Calculated CRC of the image received.
Definition at line 41 of file dfu_dual_bank_mod.c.
app_timer_id_t m_dfu_timer_id static
Application timer id.
Definition at line 43 of file dfu_dual_bank_mod.c.
bool m_dfu_timed_out = false static
Boolean flag value for tracking DFU timer timeout state.
Definition at line 44 of file dfu_dual_bank_mod.c.
pstorage_handle_t m_storage_handle_swap static
Pstorage handle for the swap area (bank 1). Bank used when updating an application or bootloader without SoftDevice.
Definition at line 46 of file dfu_dual_bank_mod.c.
pstorage_handle_t m_storage_handle_app static
Pstorage handle for the application area (bank 0). Bank used when updating a SoftDevice w/wo bootloader. Handle also used when swapping received application from bank 1 to bank 0.
Definition at line 47 of file dfu_dual_bank_mod.c.
pstorage_handle_t* mp_storage_handle_active static
Pointer to the pstorage handle for the active bank for receiving of data packets.
Definition at line 48 of file dfu_dual_bank_mod.c.
dfu_callback_t m_data_pkt_cb static
Callback from DFU Bank module for notification of asynchronous operation such as flash prepare.
Definition at line 50 of file dfu_dual_bank_mod.c.
dfu_bank_func_t m_functions static
Structure holding operations for the selected update process.
Definition at line 51 of file dfu_dual_bank_mod.c.