nRF51822 Beacon Firmware Documentation: components/libraries/bootloader_dfu/dfu_transport_ble.c File Reference
dfu_transport_ble.c File Reference
#include "dfu_transport.h"
#include "dfu.h"
#include "dfu_types.h"
#include <stddef.h>
#include <string.h>
#include "boards.h"
#include "nrf51.h"
#include "nrf_sdm.h"
#include "nrf_gpio.h"
#include "app_util.h"
#include "app_error.h"
#include "softdevice_handler.h"
#include "ble_stack_handler_types.h"
#include "ble_advdata.h"
#include "ble_l2cap.h"
#include "ble_gap.h"
#include "ble_gatt.h"
#include "ble_hci.h"
#include "ble_dfu.h"
#include "nordic_common.h"
#include "app_timer.h"
#include "ble_conn_params.h"
#include "hci_mem_pool.h"
#include "bootloader.h"
#include "dfu_ble_svc_internal.h"
#include "nrf_delay.h"
Macros
#define DFU_REV_MAJOR 0x00 /** DFU Major revision number to be exposed. */
#define DFU_REV_MINOR 0x05 /** DFU Minor revision number to be exposed. */
#define DFU_REVISION ((DFU_REV_MAJOR << 8) | DFU_REV_MINOR) /** DFU Revision number to be exposed. Combined of major and minor versions. */
#define ADVERTISING_LED_PIN_NO BSP_LED_0
#define CONNECTED_LED_PIN_NO BSP_LED_1
#define DEVICE_NAME "DfuTarg"
#define MANUFACTURER_NAME "NordicSemiconductor"
#define MIN_CONN_INTERVAL (uint16_t)(MSEC_TO_UNITS(15, UNIT_1_25_MS))
#define MAX_CONN_INTERVAL (uint16_t)(MSEC_TO_UNITS(30, UNIT_1_25_MS))
#define SLAVE_LATENCY 0
#define CONN_SUP_TIMEOUT (4 * 100)
#define APP_TIMER_PRESCALER 0
#define FIRST_CONN_PARAMS_UPDATE_DELAY APP_TIMER_TICKS(100, APP_TIMER_PRESCALER)
#define NEXT_CONN_PARAMS_UPDATE_DELAY APP_TIMER_TICKS(500, APP_TIMER_PRESCALER)
#define MAX_CONN_PARAMS_UPDATE_COUNT 3
#define APP_ADV_INTERVAL MSEC_TO_UNITS(25, UNIT_0_625_MS)
#define APP_ADV_TIMEOUT_IN_SECONDS BLE_GAP_ADV_TIMEOUT_GENERAL_UNLIMITED
#define APP_DIRECTED_ADV_TIMEOUT 5
#define PEER_ADDRESS_TYPE_INVALID 0xFF
#define SEC_PARAM_TIMEOUT 30
#define SEC_PARAM_BOND 1
#define SEC_PARAM_MITM 0
#define SEC_PARAM_IO_CAPABILITIES BLE_GAP_IO_CAPS_NONE
#define SEC_PARAM_OOB 0
#define SEC_PARAM_MIN_KEY_SIZE 7
#define SEC_PARAM_MAX_KEY_SIZE 16
#define MAX_SIZE_OF_BLE_STACK_EVT (sizeof(ble_evt_t) + BLE_L2CAP_MTU_DEF)
#define NUM_WORDS_RESERVED_FOR_BLE_EVENTS CEIL_DIV(MAX_SIZE_OF_BLE_STACK_EVT, sizeof(uint32_t))
#define IS_CONNECTED() (m_conn_handle != BLE_CONN_HANDLE_INVALID)
Enumerations
enum pkt_type_t {
PKT_TYPE_INVALID, PKT_TYPE_START, PKT_TYPE_INIT, PKT_TYPE_FIRMWARE_DATA,
PKT_TYPE_INVALID, PKT_TYPE_START, PKT_TYPE_INIT, PKT_TYPE_FIRMWARE_DATA
}
Packet type enumeration.
Functions
static ble_dfu_resp_val_t nrf_err_code_translate (uint32_t err_code, const ble_dfu_procedure_t current_dfu_proc)
Function to convert an nRF51 error code to a DFU Response Value.
static void dfu_cb_handler (uint32_t packet, uint32_t result, uint8_t *p_data)
Function for handling the callback events from the dfu module. Callbacks are expected when dfu_data_pkt_handle has been executed.
static void dfu_error_notify (ble_dfu_t *p_dfu, uint32_t err_code)
Function for notifying a DFU Controller about error conditions in the DFU module. This function also ensures that an error is translated from nrf_errors to DFU Response Value.
static void start_data_process (ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
Function for processing start data written by the peer to the DFU Packet Characteristic.
static void init_data_process (ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
Function for processing initialization data written by the peer to the DFU Packet Characteristic.
static void app_data_process (ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
Function for processing application data written by the peer to the DFU Packet Characteristic.
static void on_dfu_pkt_write (ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
Function for processing data written by the peer to the DFU Packet Characteristic.
static void conn_params_error_handler (uint32_t nrf_error)
Function for handling a Connection Parameters error.
static void conn_params_init (void)
Function for initializing the Connection Parameters module.
static void on_dfu_evt (ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
Function for the Device Firmware Update Service event handler.
static void advertising_init (uint8_t adv_flags)
Function for the Advertising functionality initialization.
static void advertising_start (void)
Function for starting advertising.
static void advertising_stop (void)
Function for stopping advertising.
static void on_ble_evt (ble_evt_t *p_ble_evt)
Function for the Application's S110 SoftDevice event handler.
static void ble_evt_dispatch (ble_evt_t *p_ble_evt)
Function for dispatching a S110 SoftDevice event to all modules with a S110 SoftDevice event handler.
static void leds_init (void)
Function for the LEDs initialization.
static void gap_params_init (void)
Function for the GAP initialization.
static void service_error_handler (uint32_t nrf_error)
Function for handling Service errors.
static void services_init (void)
Function for initializing services that will be used by the application.
static void sec_params_init (void)
Function for initializing security parameters.
uint32_t dfu_transport_update_start ()
Function for starting the update of Device Firmware.
uint32_t dfu_transport_close ()
Function for closing the transport layer.
Variables
static ble_gap_sec_params_t m_sec_params
static ble_gap_adv_params_t m_adv_params
static ble_dfu_t m_dfu
static pkt_type_t m_pkt_type
static uint8_t m_update_mode
static uint32_t m_num_of_firmware_bytes_rcvd
static uint16_t m_pkt_notif_target
static uint16_t m_pkt_notif_target_cnt
static uint8_t * mp_rx_buffer
static bool m_tear_down_in_progress = false
static bool m_pkt_rcpt_notif_enabled = false
static uint16_t m_conn_handle = BLE_CONN_HANDLE_INVALID
static bool m_is_advertising = false
static dfu_ble_peer_data_t m_ble_peer_data
static bool m_ble_peer_data_valid = false
static uint32_t m_direct_adv_cnt = APP_DIRECTED_ADV_TIMEOUT
Macro Definition Documentation
#define DFU_REV_MAJOR 0x00 /** DFU Major revision number to be exposed. */
Definition at line 40 of file dfu_transport_ble.c.
#define DFU_REV_MINOR 0x05 /** DFU Minor revision number to be exposed. */
Definition at line 41 of file dfu_transport_ble.c.
#define DFU_REVISION ((DFU_REV_MAJOR << 8) | DFU_REV_MINOR) /** DFU Revision number to be exposed. Combined of major and minor versions. */
Definition at line 42 of file dfu_transport_ble.c.
#define ADVERTISING_LED_PIN_NO BSP_LED_0
Is on when device is advertising.
Definition at line 43 of file dfu_transport_ble.c.
#define CONNECTED_LED_PIN_NO BSP_LED_1
Is on when device has connected.
Definition at line 44 of file dfu_transport_ble.c.
#define DEVICE_NAME "DfuTarg"
Name of device. Will be included in the advertising data.
Definition at line 46 of file dfu_transport_ble.c.
#define MANUFACTURER_NAME "NordicSemiconductor"
Manufacturer. Will be passed to Device Information Service.
Definition at line 47 of file dfu_transport_ble.c.
#define MIN_CONN_INTERVAL (uint16_t)(MSEC_TO_UNITS(15, UNIT_1_25_MS))
Minimum acceptable connection interval (11.25 milliseconds).
Definition at line 49 of file dfu_transport_ble.c.
#define MAX_CONN_INTERVAL (uint16_t)(MSEC_TO_UNITS(30, UNIT_1_25_MS))
Maximum acceptable connection interval (15 milliseconds).
Definition at line 50 of file dfu_transport_ble.c.
#define SLAVE_LATENCY 0
Slave latency.
Definition at line 51 of file dfu_transport_ble.c.
#define CONN_SUP_TIMEOUT (4 * 100)
Connection supervisory timeout (4 seconds).
Definition at line 52 of file dfu_transport_ble.c.
#define APP_TIMER_PRESCALER 0
Value of the RTC1 PRESCALER register.
Definition at line 54 of file dfu_transport_ble.c.
#define FIRST_CONN_PARAMS_UPDATE_DELAY APP_TIMER_TICKS(100, APP_TIMER_PRESCALER)
Time from the Connected event to first time sd_ble_gap_conn_param_update is called (100 milliseconds).
Definition at line 56 of file dfu_transport_ble.c.
#define NEXT_CONN_PARAMS_UPDATE_DELAY APP_TIMER_TICKS(500, APP_TIMER_PRESCALER)
Time between each call to sd_ble_gap_conn_param_update after the first call (500 milliseconds).
Definition at line 57 of file dfu_transport_ble.c.
#define MAX_CONN_PARAMS_UPDATE_COUNT 3
Number of attempts before giving up the connection parameter negotiation.
Definition at line 58 of file dfu_transport_ble.c.
#define APP_ADV_INTERVAL MSEC_TO_UNITS(25, UNIT_0_625_MS)
The advertising interval (25 ms.).
Definition at line 60 of file dfu_transport_ble.c.
#define APP_ADV_TIMEOUT_IN_SECONDS BLE_GAP_ADV_TIMEOUT_GENERAL_UNLIMITED
The advertising timeout in units of seconds. This is set to BLE_GAP_ADV_TIMEOUT_GENERAL_UNLIMITED so that the advertisement is done as long as there there is a call to dfu_transport_close function.
Definition at line 61 of file dfu_transport_ble.c.
#define APP_DIRECTED_ADV_TIMEOUT 5
number of direct advertisement (each lasting 1.28seconds).
Definition at line 62 of file dfu_transport_ble.c.
#define PEER_ADDRESS_TYPE_INVALID 0xFF
Value indicating that no valid peer address exists. This will be the case when a private resolvable address is used in which case there is no address available but instead an IRK is present.
Definition at line 63 of file dfu_transport_ble.c.
#define SEC_PARAM_TIMEOUT 30
Timeout for Pairing Request or Security Request (in seconds).
Definition at line 65 of file dfu_transport_ble.c.
#define SEC_PARAM_BOND 1
Perform bonding.
Definition at line 66 of file dfu_transport_ble.c.
#define SEC_PARAM_MITM 0
Man In The Middle protection not required.
Definition at line 67 of file dfu_transport_ble.c.
#define SEC_PARAM_IO_CAPABILITIES BLE_GAP_IO_CAPS_NONE
No I/O capabilities.
Definition at line 68 of file dfu_transport_ble.c.
#define SEC_PARAM_OOB 0
Out Of Band data not available.
Definition at line 69 of file dfu_transport_ble.c.
#define SEC_PARAM_MIN_KEY_SIZE 7
Minimum encryption key size.
Definition at line 70 of file dfu_transport_ble.c.
#define SEC_PARAM_MAX_KEY_SIZE 16
Maximum encryption key size.
Definition at line 71 of file dfu_transport_ble.c.
#define MAX_SIZE_OF_BLE_STACK_EVT (sizeof(ble_evt_t) + BLE_L2CAP_MTU_DEF)
Maximum size (in bytes) of the event received from S110 SoftDevice.
Definition at line 73 of file dfu_transport_ble.c.
#define NUM_WORDS_RESERVED_FOR_BLE_EVENTS CEIL_DIV(MAX_SIZE_OF_BLE_STACK_EVT, sizeof(uint32_t))
Size of the memory (in words) reserved for receiving S110 SoftDevice events.
Definition at line 74 of file dfu_transport_ble.c.
#define IS_CONNECTED () (m_conn_handle != BLE_CONN_HANDLE_INVALID)
Macro to determine if the device is in connected state.
Definition at line 76 of file dfu_transport_ble.c.
Enumeration Type Documentation
enum pkt_type_t
Packet type enumeration.
Enumerator
PKT_TYPE_INVALID
Invalid packet type. Used for initialization purpose.
PKT_TYPE_START
Start packet.
PKT_TYPE_INIT
Init packet.
PKT_TYPE_FIRMWARE_DATA
Firmware data packet.
PKT_TYPE_INVALID
Invalid packet type. Used for initialization purpose.
PKT_TYPE_START
Start packet.
PKT_TYPE_INIT
Init packet.
PKT_TYPE_FIRMWARE_DATA
Firmware data packet.
Definition at line 80 of file dfu_transport_ble.c.
 {
     PKT_TYPE_INVALID,
     PKT_TYPE_START,
     PKT_TYPE_INIT,
     PKT_TYPE_FIRMWARE_DATA
 } pkt_type_t;
Function Documentation
static ble_dfu_resp_val_t nrf_err_code_translate (uint32_t err_code, const ble_dfu_procedure_t current_dfu_proc) static
Function to convert an nRF51 error code to a DFU Response Value.
This function will convert a given nRF51 error code to a DFU Response Value. The result of this function depends on the current DFU procedure in progress, given as input in current_dfu_proc parameter.
Parameters
[in] err_code The nRF51 error code to be converted.
[in] current_dfu_proc Current DFU procedure in progress.
Returns
Converted Response Value.
Definition at line 117 of file dfu_transport_ble.c.
References BLE_DFU_RESP_VAL_CRC_ERROR, BLE_DFU_RESP_VAL_DATA_SIZE, BLE_DFU_RESP_VAL_INVALID_STATE, BLE_DFU_RESP_VAL_NOT_SUPPORTED, BLE_DFU_RESP_VAL_OPER_FAILED, BLE_DFU_RESP_VAL_SUCCESS, BLE_DFU_VALIDATE_PROCEDURE, NRF_ERROR_DATA_SIZE, NRF_ERROR_INVALID_DATA, NRF_ERROR_INVALID_STATE, NRF_ERROR_NOT_SUPPORTED, and NRF_SUCCESS.
 {
     switch (err_code)
     {
         case NRF_SUCCESS:
             return BLE_DFU_RESP_VAL_SUCCESS;
         case NRF_ERROR_INVALID_STATE:
             return BLE_DFU_RESP_VAL_INVALID_STATE;
         case NRF_ERROR_NOT_SUPPORTED:
             return BLE_DFU_RESP_VAL_NOT_SUPPORTED;
         case NRF_ERROR_DATA_SIZE:
             return BLE_DFU_RESP_VAL_DATA_SIZE;
         case NRF_ERROR_INVALID_DATA:
             if (current_dfu_proc == BLE_DFU_VALIDATE_PROCEDURE)
             {
                 // When this error is received in Validation phase, then it maps to a CRC Error.
                 // Refer dfu_image_validate function for more information.
                 return BLE_DFU_RESP_VAL_CRC_ERROR;
             }
             return BLE_DFU_RESP_VAL_OPER_FAILED;
         default:
             return BLE_DFU_RESP_VAL_OPER_FAILED;
     }
 }
static void dfu_cb_handler (uint32_t packet, uint32_t result, uint8_t * p_data) static
Function for handling the callback events from the dfu module. Callbacks are expected when dfu_data_pkt_handle has been executed.
Parameters
[in] packet Packet type for which this callback is related.
[in] result Operation result code. NRF_SUCCESS when a queued operation was successful.
[in] p_data Pointer to the data to which the operation is related.
Definition at line 156 of file dfu_transport_ble.c.
References ble_dfu_response_send(), BLE_DFU_START_PROCEDURE, BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION, DATA_PACKET, IS_CONNECTED, m_conn_handle, nrf_err_code_translate(), NRF_SUCCESS, and START_PACKET.
 {
     switch (packet)
     {
         ble_dfu_resp_val_t resp_val;
         uint32_t           err_code;
         case DATA_PACKET:
             if (result != NRF_SUCCESS)
             {
                 // Disconnect from peer.
                 if (IS_CONNECTED())
                 {
                     err_code = sd_ble_gap_disconnect(m_conn_handle,
                                                      BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION);
                     APP_ERROR_CHECK(err_code);
                 }
             }
             else
             {
                 err_code = hci_mem_pool_rx_consume(p_data);
                 APP_ERROR_CHECK(err_code);
             }
             break;
         case START_PACKET:
             // Translate the err_code returned by the above function to DFU Response Value.
             resp_val = nrf_err_code_translate(result, BLE_DFU_START_PROCEDURE);
             err_code = ble_dfu_response_send(&m_dfu,
                                              BLE_DFU_START_PROCEDURE,
                                              resp_val);
             APP_ERROR_CHECK(err_code);
             break;
         default:
             // ignore.
             break;
     }
 }
static void dfu_error_notify (ble_dfu_t * p_dfu, uint32_t err_code) static
Function for notifying a DFU Controller about error conditions in the DFU module. This function also ensures that an error is translated from nrf_errors to DFU Response Value.
Parameters
[in] p_dfu DFU Service Structure.
[in] err_code Nrf error code that should be translated and send to the DFU Controller.
Definition at line 205 of file dfu_transport_ble.c.
References BLE_DFU_RECEIVE_APP_PROCEDURE, ble_dfu_response_send(), and nrf_err_code_translate().
 {
     // An error has occurred. Notify the DFU Controller about this error condition.
     // Translate the err_code returned to DFU Response Value.
     ble_dfu_resp_val_t resp_val;
     resp_val = nrf_err_code_translate(err_code, BLE_DFU_RECEIVE_APP_PROCEDURE);
     err_code = ble_dfu_response_send(p_dfu, BLE_DFU_RECEIVE_APP_PROCEDURE, resp_val);
     APP_ERROR_CHECK(err_code);
 }
static void start_data_process (ble_dfu_t * p_dfu, ble_dfu_evt_t * p_evt) static
Function for processing start data written by the peer to the DFU Packet Characteristic.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_evt Pointer to the event received from the S110 SoftDevice.
Definition at line 224 of file dfu_transport_ble.c.
References dfu_start_packet_t::app_image_size, dfu_start_packet_t::bl_image_size, ble_dfu_evt_t::ble_dfu_pkt_write, BLE_DFU_RESP_VAL_NOT_SUPPORTED, ble_dfu_response_send(), BLE_DFU_START_PROCEDURE, dfu_start_pkt_handle(), dfu_start_packet_t::dfu_update_mode, ble_dfu_evt_t::evt, ble_dfu_pkt_write_t::len, m_update_mode, nrf_err_code_translate(), NRF_SUCCESS, ble_dfu_pkt_write_t::p_data, dfu_update_packet_t::packet_type, dfu_start_packet_t::sd_image_size, and START_PACKET.
 {
     uint32_t err_code;
     dfu_start_packet_t start_packet   = {.dfu_update_mode = m_update_mode};
     dfu_update_packet_t update_packet =
     {
         .packet_type         = START_PACKET,
         .params.start_packet = &start_packet
     };
     uint32_t length = p_evt->evt.ble_dfu_pkt_write.len;
     // Verify that the data is exactly three * four bytes (three words) long.
     // Or a single word to support backwards compatibility of application image transfer.
     if (length != (3 * sizeof(uint32_t)))
     {
         err_code = ble_dfu_response_send(p_dfu,
                                          BLE_DFU_START_PROCEDURE,
                                          BLE_DFU_RESP_VAL_NOT_SUPPORTED);
         APP_ERROR_CHECK(err_code);
     }
     else
     {
         // Extract the size of from the DFU Packet Characteristic.
         uint8_t * length_data = p_evt->evt.ble_dfu_pkt_write.p_data;
         start_packet.sd_image_size  = uint32_decode(length_data);
         start_packet.bl_image_size  = uint32_decode(length_data + 4);
         start_packet.app_image_size = uint32_decode(length_data + 8);
         err_code = dfu_start_pkt_handle(&update_packet);
         if (err_code != NRF_SUCCESS)
         {
             // Translate the err_code returned by the above function to DFU Response Value.
             ble_dfu_resp_val_t resp_val;
             resp_val = nrf_err_code_translate(err_code, BLE_DFU_START_PROCEDURE);
             err_code = ble_dfu_response_send(p_dfu, BLE_DFU_START_PROCEDURE, resp_val);
         }
         APP_ERROR_CHECK(err_code);
     }
 }
static void init_data_process (ble_dfu_t * p_dfu, ble_dfu_evt_t * p_evt) static
Function for processing initialization data written by the peer to the DFU Packet Characteristic.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_evt Pointer to the event received from the S110 SoftDevice.
Definition at line 277 of file dfu_transport_ble.c.
References BLE_DFU_INIT_PROCEDURE, ble_dfu_evt_t::ble_dfu_pkt_write, ble_dfu_response_send(), dfu_update_packet_t::data_packet, dfu_init_pkt_handle(), ble_dfu_evt_t::evt, INIT_PACKET, ble_dfu_pkt_write_t::len, nrf_err_code_translate(), NRF_SUCCESS, ble_dfu_pkt_write_t::p_data, dfu_data_packet_t::p_data_packet, dfu_data_packet_t::packet_length, dfu_update_packet_t::packet_type, and dfu_update_packet_t::params.
 {
     uint32_t            err_code;
     dfu_update_packet_t dfu_pkt;
     uint8_t             num_of_padding_bytes = 0;
     dfu_pkt.packet_type   = INIT_PACKET;
     dfu_pkt.params.data_packet.p_data_packet = (uint32_t *)p_evt->evt.ble_dfu_pkt_write.p_data;
     // The DFU module accepts the dfu_pkt.packet_length to be in 'number of words'. And so if the
     // received data does not have a size which is a multiple of four, it should be padded with
     // zeros and the packet_length should be incremented accordingly before calling
     // dfu_init_pkt_handle.
     if ((p_evt->evt.ble_dfu_pkt_write.len & (sizeof(uint32_t) - 1)) != 0)
     {
          // Find out the number of bytes to be padded.
          num_of_padding_bytes = sizeof(uint32_t)
                                 -
                                 (p_evt->evt.ble_dfu_pkt_write.len & (sizeof(uint32_t) - 1));
          uint32_t i;
          for (i = 0; i < num_of_padding_bytes; i++)
          {
              dfu_pkt.params.data_packet.p_data_packet[p_evt->evt.ble_dfu_pkt_write.len + i] = 0;
          }
     }
     dfu_pkt.params.data_packet.packet_length =
         (p_evt->evt.ble_dfu_pkt_write.len + num_of_padding_bytes) / sizeof(uint32_t);
     err_code = dfu_init_pkt_handle(&dfu_pkt);
     // Translate the err_code returned by the above function to DFU Response Value.
     if (err_code != NRF_SUCCESS)
     {
         ble_dfu_resp_val_t resp_val = nrf_err_code_translate(err_code, BLE_DFU_INIT_PROCEDURE);
         err_code = ble_dfu_response_send(p_dfu, BLE_DFU_INIT_PROCEDURE, resp_val);
         APP_ERROR_CHECK(err_code);
     }
 }
static void app_data_process (ble_dfu_t * p_dfu, ble_dfu_evt_t * p_evt) static
Function for processing application data written by the peer to the DFU Packet Characteristic.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_evt Pointer to the event received from the S110 SoftDevice.
Definition at line 327 of file dfu_transport_ble.c.
References ble_dfu_evt_t::ble_dfu_pkt_write, ble_dfu_pkts_rcpt_notify(), BLE_DFU_RECEIVE_APP_PROCEDURE, BLE_DFU_RESP_VAL_NOT_SUPPORTED, BLE_DFU_RESP_VAL_SUCCESS, ble_dfu_response_send(), DATA_PACKET, dfu_update_packet_t::data_packet, dfu_data_pkt_handle(), dfu_error_notify(), ble_dfu_evt_t::evt, ble_dfu_pkt_write_t::len, m_num_of_firmware_bytes_rcvd, m_pkt_notif_target, m_pkt_notif_target_cnt, m_pkt_rcpt_notif_enabled, mp_rx_buffer, NRF_ERROR_INVALID_LENGTH, NRF_SUCCESS, ble_dfu_pkt_write_t::p_data, dfu_data_packet_t::p_data_packet, dfu_data_packet_t::packet_length, dfu_update_packet_t::packet_type, and dfu_update_packet_t::params.
 {
     uint32_t err_code;
     if ((p_evt->evt.ble_dfu_pkt_write.len & (sizeof(uint32_t) - 1)) != 0)
     {
         // Data length is not a multiple of 4 (word size).
         err_code = ble_dfu_response_send(p_dfu,
                                          BLE_DFU_RECEIVE_APP_PROCEDURE,
                                          BLE_DFU_RESP_VAL_NOT_SUPPORTED);
         APP_ERROR_CHECK(err_code);
         return;
     }
     uint32_t length = p_evt->evt.ble_dfu_pkt_write.len;
     err_code = hci_mem_pool_rx_produce(length, (void**) &mp_rx_buffer);
     if (err_code != NRF_SUCCESS)
     {
         dfu_error_notify(p_dfu, err_code);
         return;
     }
     uint8_t * p_data_packet = p_evt->evt.ble_dfu_pkt_write.p_data;
     memcpy(mp_rx_buffer, p_data_packet, length);
     err_code = hci_mem_pool_rx_data_size_set(length);
     if (err_code != NRF_SUCCESS)
     {
         dfu_error_notify(p_dfu, err_code);
         return;
     }
     err_code = hci_mem_pool_rx_extract(&mp_rx_buffer, &length);
     if (err_code != NRF_SUCCESS)
     {
         dfu_error_notify(p_dfu, err_code);
         return;
     }
     dfu_update_packet_t dfu_pkt;
     dfu_pkt.packet_type                      = DATA_PACKET;
     dfu_pkt.params.data_packet.packet_length = length / sizeof(uint32_t);
     dfu_pkt.params.data_packet.p_data_packet = (uint32_t*)mp_rx_buffer;
     err_code = dfu_data_pkt_handle(&dfu_pkt);
     if (err_code == NRF_SUCCESS)
     {
         // All the expected firmware data has been received and processed successfully.
         m_num_of_firmware_bytes_rcvd += p_evt->evt.ble_dfu_pkt_write.len;
         // Notify the DFU Controller about the success about the procedure.
         err_code = ble_dfu_response_send(p_dfu,
                                          BLE_DFU_RECEIVE_APP_PROCEDURE,
                                          BLE_DFU_RESP_VAL_SUCCESS);
         APP_ERROR_CHECK(err_code);
     }
     else if (err_code == NRF_ERROR_INVALID_LENGTH)
     {
         // Firmware data packet was handled successfully. And more firmware data is expected.
         m_num_of_firmware_bytes_rcvd += p_evt->evt.ble_dfu_pkt_write.len;
         // Check if a packet receipt notification is needed to be sent.
         if (m_pkt_rcpt_notif_enabled)
         {
             // Decrement the counter for the number firmware packets needed for sending the
             // next packet receipt notification.
             m_pkt_notif_target_cnt--;
             if (m_pkt_notif_target_cnt == 0)
             {
                 err_code = ble_dfu_pkts_rcpt_notify(p_dfu, m_num_of_firmware_bytes_rcvd);
                 APP_ERROR_CHECK(err_code);
                 // Reset the counter for the number of firmware packets.
                 m_pkt_notif_target_cnt = m_pkt_notif_target;
             }
         }
     }
     else
     {
         uint32_t hci_error = hci_mem_pool_rx_consume(mp_rx_buffer);
         if (hci_error != NRF_SUCCESS)
         {
             dfu_error_notify(p_dfu, hci_error);
         }
         dfu_error_notify(p_dfu, err_code);
     }
 }
static void on_dfu_pkt_write (ble_dfu_t * p_dfu, ble_dfu_evt_t * p_evt) static
Function for processing data written by the peer to the DFU Packet Characteristic.
Parameters
[in] p_dfu DFU Service Structure.
[in] p_evt Pointer to the event received from the S110 SoftDevice.
Definition at line 427 of file dfu_transport_ble.c.
References app_data_process(), init_data_process(), m_pkt_type, PKT_TYPE_FIRMWARE_DATA, PKT_TYPE_INIT, PKT_TYPE_START, and start_data_process().
 {
     // The peer has written to the DFU Packet characteristic. Depending on the value of
     // the current value of the DFU Control Point, the appropriate action is taken.
     switch (m_pkt_type)
     {
         case PKT_TYPE_START:
             // The peer has written a start packet to the DFU Packet characteristic.
             start_data_process(p_dfu, p_evt);
             break;
         case PKT_TYPE_INIT:
             // The peer has written an init packet to the DFU Packet characteristic.
             init_data_process(p_dfu, p_evt);
             break;
         case PKT_TYPE_FIRMWARE_DATA:
             app_data_process(p_dfu, p_evt);
             break;
         default:
             // It is not possible to find out what packet it is. Ignore. Currently there is no
             // mechanism to notify the DFU Controller about this error condition.
             break;
     }
 }
static void conn_params_error_handler (uint32_t nrf_error) static
Function for handling a Connection Parameters error.
Parameters
[in] nrf_error Error code.
Definition at line 459 of file dfu_transport_ble.c.
 {
     APP_ERROR_HANDLER(nrf_error);
 }
static void conn_params_init (void) static
Function for initializing the Connection Parameters module.
Definition at line 467 of file dfu_transport_ble.c.
References ble_conn_params_init(), BLE_GATT_HANDLE_INVALID, conn_params_error_handler(), ble_conn_params_init_t::disconnect_on_fail, ble_conn_params_init_t::error_handler, ble_conn_params_init_t::evt_handler, ble_conn_params_init_t::first_conn_params_update_delay, FIRST_CONN_PARAMS_UPDATE_DELAY, ble_conn_params_init_t::max_conn_params_update_count, MAX_CONN_PARAMS_UPDATE_COUNT, ble_conn_params_init_t::next_conn_params_update_delay, NEXT_CONN_PARAMS_UPDATE_DELAY, ble_conn_params_init_t::p_conn_params, and ble_conn_params_init_t::start_on_notify_cccd_handle.
 {
     uint32_t               err_code;
     ble_conn_params_init_t cp_init;
     memset(&cp_init, 0, sizeof(cp_init));
     cp_init.p_conn_params                  = NULL;
     cp_init.first_conn_params_update_delay = FIRST_CONN_PARAMS_UPDATE_DELAY;
     cp_init.next_conn_params_update_delay  = NEXT_CONN_PARAMS_UPDATE_DELAY;
     cp_init.max_conn_params_update_count   = MAX_CONN_PARAMS_UPDATE_COUNT;
     cp_init.start_on_notify_cccd_handle    = BLE_GATT_HANDLE_INVALID;
     cp_init.disconnect_on_fail             = false;
     cp_init.evt_handler                    = NULL;
     cp_init.error_handler                  = conn_params_error_handler;
     err_code = ble_conn_params_init(&cp_init);
     APP_ERROR_CHECK(err_code);
 }
static void on_dfu_evt (ble_dfu_t * p_dfu, ble_dfu_evt_t * p_evt) static
Function for the Device Firmware Update Service event handler.
This function will be called for all Device Firmware Update Service events which are passed to the application.
Parameters
[in] p_dfu Device Firmware Update Service structure.
[in] p_evt Event received from the Device Firmware Update Service.
Definition at line 496 of file dfu_transport_ble.c.
References BLE_DFU_ACTIVATE_N_RESET, ble_dfu_bytes_rcvd_report(), BLE_DFU_BYTES_RECEIVED_SEND, ble_dfu_evt_t::ble_dfu_evt_type, BLE_DFU_INIT_PROCEDURE, BLE_DFU_PACKET_WRITE, BLE_DFU_PKT_RCPT_NOTIF_DISABLED, BLE_DFU_PKT_RCPT_NOTIF_ENABLED, ble_dfu_evt_t::ble_dfu_pkt_write, BLE_DFU_RECEIVE_APP_DATA, BLE_DFU_RECEIVE_INIT_DATA, ble_dfu_response_send(), BLE_DFU_START, BLE_DFU_SYS_RESET, BLE_DFU_VALIDATE, BLE_DFU_VALIDATE_PROCEDURE, dfu_image_activate(), dfu_image_validate(), DFU_INIT_COMPLETE, dfu_init_pkt_complete(), dfu_reset(), dfu_transport_close(), ble_dfu_evt_t::evt, m_num_of_firmware_bytes_rcvd, m_pkt_notif_target, m_pkt_notif_target_cnt, m_pkt_rcpt_notif_enabled, m_pkt_type, m_update_mode, nrf_err_code_translate(), NRF_SUCCESS, ble_pkt_rcpt_notif_req_t::num_of_pkts, on_dfu_pkt_write(), ble_dfu_pkt_write_t::p_data, ble_dfu_evt_t::pkt_rcpt_notif_req, PKT_TYPE_FIRMWARE_DATA, PKT_TYPE_INIT, and PKT_TYPE_START.
 {
     uint32_t           err_code;
     ble_dfu_resp_val_t resp_val;
     switch (p_evt->ble_dfu_evt_type)
     {
         case BLE_DFU_VALIDATE:
             err_code = dfu_image_validate();
             // Translate the err_code returned by the above function to DFU Response Value.
             resp_val = nrf_err_code_translate(err_code, BLE_DFU_VALIDATE_PROCEDURE);
             err_code = ble_dfu_response_send(p_dfu, BLE_DFU_VALIDATE_PROCEDURE, resp_val);
             APP_ERROR_CHECK(err_code);
             break;
         case BLE_DFU_ACTIVATE_N_RESET:
             err_code = dfu_transport_close();
             APP_ERROR_CHECK(err_code);
             // With the S110 Flash API it is safe to initiate the activate before connection is
             // fully closed.
             err_code = dfu_image_activate();
             if (err_code != NRF_SUCCESS)
             {
                 dfu_reset();
             }
             break;
         case BLE_DFU_SYS_RESET:
             err_code = dfu_transport_close();
             APP_ERROR_CHECK(err_code);
             dfu_reset();
             break;
         case BLE_DFU_START:
             m_pkt_type    = PKT_TYPE_START;
             m_update_mode = (uint8_t)p_evt->evt.ble_dfu_pkt_write.p_data[0];
             break;
         case BLE_DFU_RECEIVE_INIT_DATA:
             m_pkt_type = PKT_TYPE_INIT;
             if ((uint8_t)p_evt->evt.ble_dfu_pkt_write.p_data[0] == DFU_INIT_COMPLETE)
             {
                 err_code = dfu_init_pkt_complete();
                 // Translate the err_code returned by the above function to DFU Response Value.
                 resp_val = nrf_err_code_translate(err_code, BLE_DFU_INIT_PROCEDURE);
                 err_code = ble_dfu_response_send(p_dfu, BLE_DFU_INIT_PROCEDURE, resp_val);
                 APP_ERROR_CHECK(err_code);
             }
             break;
         case BLE_DFU_RECEIVE_APP_DATA:
             m_pkt_type = PKT_TYPE_FIRMWARE_DATA;
             break;
         case BLE_DFU_PACKET_WRITE:
             on_dfu_pkt_write(p_dfu, p_evt);
             break;
         case BLE_DFU_PKT_RCPT_NOTIF_ENABLED:
             m_pkt_rcpt_notif_enabled = true;
             m_pkt_notif_target       = p_evt->evt.pkt_rcpt_notif_req.num_of_pkts;
             m_pkt_notif_target_cnt   = p_evt->evt.pkt_rcpt_notif_req.num_of_pkts;
             break;
         case BLE_DFU_PKT_RCPT_NOTIF_DISABLED:
             m_pkt_rcpt_notif_enabled = false;
             m_pkt_notif_target       = 0;
             break;
        case BLE_DFU_BYTES_RECEIVED_SEND:
             err_code = ble_dfu_bytes_rcvd_report(p_dfu, m_num_of_firmware_bytes_rcvd);
             APP_ERROR_CHECK(err_code);
             break;
         default:
             // Unsupported event received from DFU Service. Ignore.
             break;
     }
 }
static void advertising_init (uint8_t adv_flags) static
Function for the Advertising functionality initialization.
Encodes the required advertising data and passes it to the stack. Also builds a structure to be passed to the stack when starting advertising.
Definition at line 588 of file dfu_transport_ble.c.
References BLE_ADVDATA_FULL_NAME, ble_advdata_set(), BLE_DFU_SERVICE_UUID, ble_advdata_t::flags, ble_advdata_t::include_appearance, ble_advdata_t::name_type, ble_advdata_uuid_list_t::p_uuids, ble_uuid_t::type, ble_uuid_t::uuid, ble_advdata_uuid_list_t::uuid_cnt, ble_dfu_s::uuid_type, and ble_advdata_t::uuids_more_available.
 {
     uint32_t            err_code;
     ble_advdata_t       advdata;
     ble_uuid_t          service_uuid;
     service_uuid.type   = m_dfu.uuid_type;
     service_uuid.uuid   = BLE_DFU_SERVICE_UUID;
     // Build and set advertising data.
     memset(&advdata, 0, sizeof(advdata));
     advdata.name_type                     = BLE_ADVDATA_FULL_NAME;
     advdata.include_appearance            = false;
     advdata.flags.size                    = sizeof(adv_flags);
     advdata.flags.p_data                  = &adv_flags;
     advdata.uuids_more_available.uuid_cnt = 1;
     advdata.uuids_more_available.p_uuids  = &service_uuid;
     err_code = ble_advdata_set(&advdata, NULL);
     APP_ERROR_CHECK(err_code);
 }
static void advertising_start (void) static
Function for starting advertising.
Definition at line 614 of file dfu_transport_ble.c.
References dfu_ble_peer_data_t::addr, ble_gap_whitelist_t::addr_count, ble_gap_addr_t::addr_type, advertising_init(), ADVERTISING_LED_PIN_NO, APP_ADV_INTERVAL, APP_ADV_TIMEOUT_IN_SECONDS, BLE_GAP_ADV_FLAG_BR_EDR_NOT_SUPPORTED, BLE_GAP_ADV_FLAGS_LE_ONLY_GENERAL_DISC_MODE, BLE_GAP_ADV_FLAGS_LE_ONLY_LIMITED_DISC_MODE, BLE_GAP_ADV_FP_ANY, BLE_GAP_ADV_FP_FILTER_CONNREQ, BLE_GAP_ADV_TYPE_ADV_DIRECT_IND, BLE_GAP_ADV_TYPE_ADV_IND, ble_gap_adv_params_t::fp, ble_gap_adv_params_t::interval, dfu_ble_peer_data_t::irk, ble_gap_whitelist_t::irk_count, m_ble_peer_data_valid, m_is_advertising, nrf_gpio_pin_clear(), ble_gap_adv_params_t::p_peer_addr, ble_gap_adv_params_t::p_whitelist, PEER_ADDRESS_TYPE_INVALID, ble_gap_whitelist_t::pp_addrs, ble_gap_whitelist_t::pp_irks, ble_gap_adv_params_t::timeout, and ble_gap_adv_params_t::type.
 {
     if (!m_is_advertising)
     {
         uint32_t err_code;
         // Initialize advertising parameters (used when starting advertising).
         memset(&m_adv_params, 0, sizeof(m_adv_params));
         if (m_ble_peer_data_valid)
         {
             if (m_ble_peer_data.addr.addr_type != PEER_ADDRESS_TYPE_INVALID)
             {
                 advertising_init(BLE_GAP_ADV_FLAGS_LE_ONLY_LIMITED_DISC_MODE);
                 m_adv_params.type        = BLE_GAP_ADV_TYPE_ADV_DIRECT_IND;
                 m_adv_params.p_peer_addr = &m_ble_peer_data.addr;
                 m_adv_params.fp          = BLE_GAP_ADV_FP_ANY;
                 m_adv_params.interval    = 0;
                 m_adv_params.timeout     = 0;
             }
             else
             {
                 ble_gap_irk_t      * p_irk[1];
                 ble_gap_addr_t     * p_addr[1];
                 p_irk[0]  = &m_ble_peer_data.irk;
                 p_addr[0] = &m_ble_peer_data.addr;
                 ble_gap_whitelist_t  whitelist;
                 whitelist.addr_count = 0;
                 whitelist.pp_addrs   = p_addr;
                 whitelist.irk_count  = 1;
                 whitelist.pp_irks    = p_irk;
                 advertising_init(BLE_GAP_ADV_FLAG_BR_EDR_NOT_SUPPORTED);
                 m_adv_params.type        = BLE_GAP_ADV_TYPE_ADV_IND;
                 m_adv_params.fp          = BLE_GAP_ADV_FP_FILTER_CONNREQ;
                 m_adv_params.p_whitelist = &whitelist;
                 m_adv_params.interval    = APP_ADV_INTERVAL;
                 m_adv_params.timeout     = APP_ADV_TIMEOUT_IN_SECONDS;
             }
         }
         else
         {
             advertising_init(BLE_GAP_ADV_FLAGS_LE_ONLY_GENERAL_DISC_MODE);
             m_adv_params.type        = BLE_GAP_ADV_TYPE_ADV_IND;
             m_adv_params.p_peer_addr = NULL;
             m_adv_params.fp          = BLE_GAP_ADV_FP_ANY;
             m_adv_params.interval    = APP_ADV_INTERVAL;
             m_adv_params.timeout     = APP_ADV_TIMEOUT_IN_SECONDS;
         }
         err_code = sd_ble_gap_adv_start(&m_adv_params);
         APP_ERROR_CHECK(err_code);
         nrf_gpio_pin_clear(ADVERTISING_LED_PIN_NO);
         m_is_advertising = true;
     }
 }
static void advertising_stop (void) static
Function for stopping advertising.
Definition at line 679 of file dfu_transport_ble.c.
References ADVERTISING_LED_PIN_NO, m_is_advertising, and nrf_gpio_pin_set().
 {
     if (m_is_advertising)
     {
         uint32_t err_code;
         err_code = sd_ble_gap_adv_stop();
         APP_ERROR_CHECK(err_code);
         nrf_gpio_pin_set(ADVERTISING_LED_PIN_NO);
         m_is_advertising = false;
     }
 }
static void on_ble_evt (ble_evt_t * p_ble_evt) static
Function for the Application's S110 SoftDevice event handler.
Parameters
[in] p_ble_evt S110 SoftDevice event.
Definition at line 699 of file dfu_transport_ble.c.
References ADVERTISING_LED_PIN_NO, advertising_start(), APP_DIRECTED_ADV_TIMEOUT, BLE_CONN_HANDLE_INVALID, BLE_GAP_EVT_CONN_SEC_UPDATE, BLE_GAP_EVT_CONNECTED, BLE_GAP_EVT_DISCONNECTED, BLE_GAP_EVT_SEC_INFO_REQUEST, BLE_GAP_EVT_SEC_PARAMS_REQUEST, BLE_GAP_EVT_TIMEOUT, BLE_GAP_SEC_STATUS_SUCCESS, BLE_GAP_TIMEOUT_SRC_ADVERTISEMENT, BLE_GATT_TIMEOUT_SRC_PROTOCOL, BLE_GATTS_EVT_SYS_ATTR_MISSING, BLE_GATTS_EVT_TIMEOUT, BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION, bootloader_dfu_update_process(), ble_gap_evt_t::conn_handle, CONNECTED_LED_PIN_NO, DFU_TIMEOUT, dfu_ble_peer_data_t::enc_info, ble_evt_t::evt, ble_evt_hdr_t::evt_id, ble_evt_t::gap_evt, ble_evt_t::gatts_evt, ble_evt_t::header, m_conn_handle, m_direct_adv_cnt, m_is_advertising, m_tear_down_in_progress, nrf_gpio_pin_clear(), nrf_gpio_pin_set(), ble_gatts_evt_t::params, ble_gap_evt_t::params, ble_gatts_evt_timeout_t::src, ble_gap_evt_timeout_t::src, dfu_update_status_t::status_code, ble_gatts_evt_t::timeout, and ble_gap_evt_t::timeout.
 {
     uint32_t err_code;
     switch (p_ble_evt->header.evt_id)
     {
         case BLE_GAP_EVT_CONNECTED:
             nrf_gpio_pin_clear(CONNECTED_LED_PIN_NO);
             nrf_gpio_pin_set(ADVERTISING_LED_PIN_NO);
             m_conn_handle    = p_ble_evt->evt.gap_evt.conn_handle;
             m_is_advertising = false;
             break;
         case BLE_GAP_EVT_DISCONNECTED:
             m_direct_adv_cnt = APP_DIRECTED_ADV_TIMEOUT;
             nrf_gpio_pin_set(CONNECTED_LED_PIN_NO);
             if (!m_tear_down_in_progress)
             {
                 // The Disconnected event is because of an external event. (Link loss or
                 // disconnect triggered by the DFU Controller before the firmware update was
                 // complete).
                 // Restart advertising so that the DFU Controller can reconnect if possible.
                 advertising_start();
             }
             m_conn_handle = BLE_CONN_HANDLE_INVALID;
             break;
         case BLE_GAP_EVT_SEC_PARAMS_REQUEST:
             err_code = sd_ble_gap_sec_params_reply(m_conn_handle,
                                                    BLE_GAP_SEC_STATUS_SUCCESS,
                                                    &m_sec_params);
             APP_ERROR_CHECK(err_code);
             break;
         case BLE_GATTS_EVT_TIMEOUT:
             if (p_ble_evt->evt.gatts_evt.params.timeout.src == BLE_GATT_TIMEOUT_SRC_PROTOCOL)
             {
                 err_code = sd_ble_gap_disconnect(m_conn_handle,
                                                  BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION);
                 APP_ERROR_CHECK(err_code);
             }
             break;
         case BLE_GAP_EVT_TIMEOUT:
             if (p_ble_evt->evt.gap_evt.params.timeout.src == BLE_GAP_TIMEOUT_SRC_ADVERTISEMENT)
             {
                 m_is_advertising = false;
                 m_direct_adv_cnt--;
                 if (m_direct_adv_cnt == 0)
                 {
                     dfu_update_status_t update_status = {.status_code = DFU_TIMEOUT};
                     bootloader_dfu_update_process(update_status);
                 }
                 else
                 {
                     advertising_start();
                 }
             }
             break;
         case BLE_GAP_EVT_SEC_INFO_REQUEST:
             err_code = sd_ble_gap_sec_info_reply(p_ble_evt->evt.gap_evt.conn_handle,
                                                  &m_ble_peer_data.enc_info,
                                                  NULL);
             APP_ERROR_CHECK(err_code);
             break;
         case BLE_GATTS_EVT_SYS_ATTR_MISSING:
         case BLE_GAP_EVT_CONN_SEC_UPDATE:
             err_code = sd_ble_gatts_sys_attr_set(m_conn_handle, NULL, 0);
             APP_ERROR_CHECK(err_code);
             break;
         default:
             // No implementation needed.
             break;
     }
 }
static void ble_evt_dispatch (ble_evt_t * p_ble_evt) static
Function for dispatching a S110 SoftDevice event to all modules with a S110 SoftDevice event handler.
This function is called from the S110 SoftDevice event interrupt handler after a S110 SoftDevice event has been received.
Parameters
[in] p_ble_evt S110 SoftDevice event.
Definition at line 792 of file dfu_transport_ble.c.
References ble_conn_params_on_ble_evt(), ble_dfu_on_ble_evt(), and on_ble_evt().
 {
     ble_conn_params_on_ble_evt(p_ble_evt);
     ble_dfu_on_ble_evt(&m_dfu, p_ble_evt);
     on_ble_evt(p_ble_evt);
 }
static void leds_init (void) static
Function for the LEDs initialization.
Initializes all LEDs used by this application.
Definition at line 804 of file dfu_transport_ble.c.
References ADVERTISING_LED_PIN_NO, CONNECTED_LED_PIN_NO, nrf_gpio_cfg_output(), and nrf_gpio_pin_set().
 {
     nrf_gpio_cfg_output(ADVERTISING_LED_PIN_NO);
     nrf_gpio_cfg_output(CONNECTED_LED_PIN_NO);
     nrf_gpio_pin_set(ADVERTISING_LED_PIN_NO);
     nrf_gpio_pin_set(CONNECTED_LED_PIN_NO);
 }
static void gap_params_init (void) static
Function for the GAP initialization.
This function will setup all the necessary GAP (Generic Access Profile) parameters of the device. It also sets the permissions and appearance.
Definition at line 818 of file dfu_transport_ble.c.
References BLE_GAP_CONN_SEC_MODE_SET_OPEN, CONN_SUP_TIMEOUT, ble_gap_conn_params_t::conn_sup_timeout, DEVICE_NAME, MAX_CONN_INTERVAL, ble_gap_conn_params_t::max_conn_interval, MIN_CONN_INTERVAL, ble_gap_conn_params_t::min_conn_interval, SLAVE_LATENCY, and ble_gap_conn_params_t::slave_latency.
 {
     uint32_t                err_code;
     ble_gap_conn_params_t   gap_conn_params;
     ble_gap_conn_sec_mode_t sec_mode;
     BLE_GAP_CONN_SEC_MODE_SET_OPEN(&sec_mode);
     err_code = sd_ble_gap_device_name_set(&sec_mode,
                                           (const uint8_t *)DEVICE_NAME,
                                           strlen(DEVICE_NAME));
     APP_ERROR_CHECK(err_code);
     memset(&gap_conn_params, 0, sizeof(gap_conn_params));
     gap_conn_params.min_conn_interval = MIN_CONN_INTERVAL;
     gap_conn_params.max_conn_interval = MAX_CONN_INTERVAL;
     gap_conn_params.slave_latency     = SLAVE_LATENCY;
     gap_conn_params.conn_sup_timeout  = CONN_SUP_TIMEOUT;
     err_code = sd_ble_gap_ppcp_set(&gap_conn_params);
     APP_ERROR_CHECK(err_code);
 }
static void service_error_handler (uint32_t nrf_error) static
Function for handling Service errors.
A pointer to this function will be passed to the DFU service which may need to inform the application about an error.
Parameters
[in] nrf_error Error code containing information about what went wrong.
Definition at line 850 of file dfu_transport_ble.c.
 {
     APP_ERROR_HANDLER(nrf_error);
 }
static void services_init (void) static
Function for initializing services that will be used by the application.
Definition at line 858 of file dfu_transport_ble.c.
References ble_dfu_init(), DFU_REVISION, ble_dfu_init_t::error_handler, ble_dfu_init_t::evt_handler, on_dfu_evt(), ble_dfu_init_t::revision, and service_error_handler().
 {
     uint32_t       err_code;
     ble_dfu_init_t dfu_init_obj;
     // Initialize the Device Firmware Update Service.
     memset(&dfu_init_obj, 0, sizeof(dfu_init_obj));
     dfu_init_obj.revision      = DFU_REVISION;
     dfu_init_obj.evt_handler   = on_dfu_evt;
     dfu_init_obj.error_handler = service_error_handler;
     err_code = ble_dfu_init(&m_dfu, &dfu_init_obj);
     APP_ERROR_CHECK(err_code);
 }
static void sec_params_init (void) static
Function for initializing security parameters.
Definition at line 878 of file dfu_transport_ble.c.
References ble_gap_sec_params_t::bond, ble_gap_sec_params_t::io_caps, ble_gap_sec_params_t::max_key_size, ble_gap_sec_params_t::min_key_size, ble_gap_sec_params_t::mitm, ble_gap_sec_params_t::oob, SEC_PARAM_BOND, SEC_PARAM_IO_CAPABILITIES, SEC_PARAM_MAX_KEY_SIZE, SEC_PARAM_MIN_KEY_SIZE, SEC_PARAM_MITM, SEC_PARAM_OOB, SEC_PARAM_TIMEOUT, and ble_gap_sec_params_t::timeout.
 {
     m_sec_params.timeout      = SEC_PARAM_TIMEOUT;
     m_sec_params.bond         = SEC_PARAM_BOND;
     m_sec_params.mitm         = SEC_PARAM_MITM;
     m_sec_params.io_caps      = SEC_PARAM_IO_CAPABILITIES;
     m_sec_params.oob          = SEC_PARAM_OOB;
     m_sec_params.min_key_size = SEC_PARAM_MIN_KEY_SIZE;
     m_sec_params.max_key_size = SEC_PARAM_MAX_KEY_SIZE;
 }
Variable Documentation
ble_gap_sec_params_t m_sec_params static
Security requirements for this application.
Definition at line 88 of file dfu_transport_ble.c.
ble_gap_adv_params_t m_adv_params static
Parameters to be passed to the stack when starting advertising.
Definition at line 89 of file dfu_transport_ble.c.
ble_dfu_t m_dfu static
Structure used to identify the Device Firmware Update service.
Definition at line 90 of file dfu_transport_ble.c.
pkt_type_t m_pkt_type static
Type of packet to be expected from the DFU Controller.
Definition at line 91 of file dfu_transport_ble.c.
uint8_t m_update_mode static
Type of update mode specified by the DFU Controller.
Definition at line 92 of file dfu_transport_ble.c.
uint32_t m_num_of_firmware_bytes_rcvd static
Cumulative number of bytes of firmware data received.
Definition at line 93 of file dfu_transport_ble.c.
uint16_t m_pkt_notif_target static
Number of packets of firmware data to be received before transmitting the next Packet Receipt Notification to the DFU Controller.
Definition at line 94 of file dfu_transport_ble.c.
uint16_t m_pkt_notif_target_cnt static
Number of packets of firmware data received after sending last Packet Receipt Notification or since the receipt of a BLE_DFU_PKT_RCPT_NOTIF_ENABLED event from the DFU service, which ever occurs later.
Definition at line 95 of file dfu_transport_ble.c.
uint8_t* mp_rx_buffer static
Pointer to a RX buffer.
Definition at line 96 of file dfu_transport_ble.c.
bool m_tear_down_in_progress = false static
Variable to indicate whether a tear down is in progress. A tear down could be because the application has initiated it or the peer has disconnected.
Definition at line 97 of file dfu_transport_ble.c.
bool m_pkt_rcpt_notif_enabled = false static
Variable to denote whether packet receipt notification has been enabled by the DFU controller.
Definition at line 98 of file dfu_transport_ble.c.
uint16_t m_conn_handle = BLE_CONN_HANDLE_INVALID static
Handle of the current connection.
Definition at line 99 of file dfu_transport_ble.c.
bool m_is_advertising = false static
Variable to indicate if advertising is ongoing.
Definition at line 100 of file dfu_transport_ble.c.
dfu_ble_peer_data_t m_ble_peer_data static
BLE Peer data exchanged from application on buttonless update mode.
Definition at line 101 of file dfu_transport_ble.c.
bool m_ble_peer_data_valid = false static
True if BLE Peer data has been exchanged from application.
Definition at line 102 of file dfu_transport_ble.c.
uint32_t m_direct_adv_cnt = APP_DIRECTED_ADV_TIMEOUT static
Counter of direct advertisements.
Definition at line 103 of file dfu_transport_ble.c.