nRF51822 Beacon Firmware Documentation: components/libraries/bootloader_dfu/dfu_transport_serial.c File Reference
dfu_transport_serial.c File Reference
#include "dfu_transport.h"
#include <stddef.h>
#include "dfu.h"
#include "dfu_types.h"
#include "app_error.h"
#include "app_util.h"
#include "hci_transport.h"
#include "app_timer.h"
#include "app_gpiote.h"
Data Structures
struct dfu_data_queue_t
Macros
#define MAX_BUFFERS 4u
#define APP_GPIOTE_MAX_USERS 1
#define DATA_QUEUE_FULL() (((MAX_BUFFERS -1) == m_data_queue.count) ? true : false)
#define DATA_QUEUE_EMPTY() ((0 == m_data_queue.count) ? true : false)
#define DATA_QUEUE_ELEMENT_INIT(i) m_data_queue.data_packet[(i)].packet_type = INVALID_PACKET
#define DATA_QUEUE_ELEMENT_SET_PTYPE(i, t) m_data_queue.data_packet[(i)].packet_type = (t)
#define DATA_QUEUE_ELEMENT_COPY_PDATA(i, dp) m_data_queue.data_packet[(i)].params.data_packet.p_data_packet = (uint32_t *)(dp)
#define DATA_QUEUE_ELEMENT_SET_PLEN(i, l) m_data_queue.data_packet[(i)].params.data_packet.packet_length = (l)
#define DATA_QUEUE_ELEMENT_GET_PDATA(i) (m_data_queue.data_packet[(i)].params.data_packet.p_data_packet)
#define DATA_QUEUE_ELEMENT_GET_PTYPE(i) m_data_queue.data_packet[(i)].packet_type
Functions
static void data_queue_element_init (uint8_t element_index)
Initializes an element of the data buffer queue.
static void data_queue_init (void)
static uint32_t data_queue_element_free (uint8_t element_index)
Function for freeing an element.
static uint32_t data_queue_element_alloc (uint8_t *p_element_index, uint8_t packet_type)
Function for Allocating element.
static void data_queue_flush (void)
static void dfu_cb_handler (uint32_t packet, uint32_t result, uint8_t *p_data)
Function for handling the callback events from the dfu module. Callbacks are expected when dfu_data_pkt_handle has been executed.
static void process_dfu_packet (void *p_event_data, uint16_t event_size)
void rpc_transport_event_handler (hci_transport_evt_t event)
uint32_t dfu_transport_update_start (void)
Function for starting the update of Device Firmware.
uint32_t dfu_transport_close (void)
Function for closing the transport layer.
Variables
static dfu_data_queue_t m_data_queue
Macro Definition Documentation
#define MAX_BUFFERS 4u
Maximum number of buffers that can be received queued without being consumed.
Definition at line 23 of file dfu_transport_serial.c.
#define APP_GPIOTE_MAX_USERS 1
Number of GPIOTE users in total. Used by dfu_transport_serial module (flow control).
Definition at line 24 of file dfu_transport_serial.c.
#define DATA_QUEUE_FULL () (((MAX_BUFFERS -1) == m_data_queue.count) ? true : false)
defgroup Data Packet Queue Access Operation MacrosProvides status showing if the queue is full or not.
Definition at line 32 of file dfu_transport_serial.c.
#define DATA_QUEUE_EMPTY () ((0 == m_data_queue.count) ? true : false)
Provides status showing if the queue is empty or not
Definition at line 36 of file dfu_transport_serial.c.
#define DATA_QUEUE_ELEMENT_INIT (i) m_data_queue.data_packet[(i)].packet_type = INVALID_PACKET
Initializes an element of the data queue.
Definition at line 40 of file dfu_transport_serial.c.
#define DATA_QUEUE_ELEMENT_SET_PTYPE (i, t) m_data_queue.data_packet[(i)].packet_type = (t)
Sets the packet type of an element of the data queue.
Definition at line 44 of file dfu_transport_serial.c.
#define DATA_QUEUE_ELEMENT_COPY_PDATA (i, dp) m_data_queue.data_packet[(i)].params.data_packet.p_data_packet = (uint32_t *)(dp)
Copies a data packet pointer of an element of the data queue.
Definition at line 48 of file dfu_transport_serial.c.
#define DATA_QUEUE_ELEMENT_SET_PLEN (i, l) m_data_queue.data_packet[(i)].params.data_packet.packet_length = (l)
Sets the packet length of an element in the data queue.
Definition at line 52 of file dfu_transport_serial.c.
#define DATA_QUEUE_ELEMENT_GET_PDATA (i) (m_data_queue.data_packet[(i)].params.data_packet.p_data_packet)
Gets a data packet pointer of an element in the data queue.
Definition at line 56 of file dfu_transport_serial.c.
#define DATA_QUEUE_ELEMENT_GET_PTYPE (i) m_data_queue.data_packet[(i)].packet_type
Gets the packet type of an element in the data queue.
Definition at line 60 of file dfu_transport_serial.c.
Function Documentation
static void data_queue_element_init (uint8_t element_index) static
Initializes an element of the data buffer queue.
Parameters
[in] element_index index of the element.
Definition at line 78 of file dfu_transport_serial.c.
References DATA_QUEUE_ELEMENT_COPY_PDATA, DATA_QUEUE_ELEMENT_INIT, DATA_QUEUE_ELEMENT_SET_PLEN, DATA_QUEUE_ELEMENT_SET_PTYPE, and INVALID_PACKET.
 {
     DATA_QUEUE_ELEMENT_INIT(element_index);
     DATA_QUEUE_ELEMENT_SET_PTYPE(element_index, INVALID_PACKET);
     DATA_QUEUE_ELEMENT_COPY_PDATA(element_index, NULL);
     DATA_QUEUE_ELEMENT_SET_PLEN(element_index, 0);
 }
static void data_queue_init (void) static
Initializes data buffer queue
Definition at line 87 of file dfu_transport_serial.c.
References dfu_data_queue_t::count, data_queue_element_init(), and MAX_BUFFERS.
 {
     uint32_t index;
     m_data_queue.count = 0;
     for (index = 0; index < MAX_BUFFERS; index++)
     {
         data_queue_element_init(index);
     }
 }
static uint32_t data_queue_element_free (uint8_t element_index) static
Function for freeing an element.
Parameters
[in] element_index index of the element.
Definition at line 103 of file dfu_transport_serial.c.
References dfu_data_queue_t::count, DATA_QUEUE_ELEMENT_GET_PDATA, DATA_QUEUE_ELEMENT_GET_PTYPE, data_queue_element_init(), INVALID_PACKET, MAX_BUFFERS, NRF_ERROR_INVALID_PARAM, and NRF_SUCCESS.
 {
     uint8_t * p_data;
     uint32_t  retval;
     retval = NRF_ERROR_INVALID_PARAM;
     if (MAX_BUFFERS > element_index)
     {
         p_data = (uint8_t *)DATA_QUEUE_ELEMENT_GET_PDATA(element_index);
         if (INVALID_PACKET != DATA_QUEUE_ELEMENT_GET_PTYPE(element_index))
         {
             m_data_queue.count--;
             data_queue_element_init (element_index);
             retval = hci_transport_rx_pkt_consume((p_data - 4));
             APP_ERROR_CHECK(retval);
         }
     }
     else
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     return NRF_SUCCESS;
 }
static uint32_t data_queue_element_alloc (uint8_t * p_element_index, uint8_t packet_type) static
Function for Allocating element.
Parameters
[in] packet_type packet type.
[out] p_element_index index of the element.
Definition at line 134 of file dfu_transport_serial.c.
References dfu_data_queue_t::count, DATA_QUEUE_ELEMENT_GET_PTYPE, DATA_QUEUE_ELEMENT_SET_PTYPE, DATA_QUEUE_FULL, INVALID_PACKET, MAX_BUFFERS, NRF_ERROR_INVALID_PARAM, NRF_ERROR_NO_MEM, and NRF_SUCCESS.
 {
     uint32_t retval;
     uint32_t index;
     retval = NRF_ERROR_NO_MEM;
     if (INVALID_PACKET == packet_type)
     {
         retval = NRF_ERROR_INVALID_PARAM;
     }
     else if (true == DATA_QUEUE_FULL())
     {
         retval = NRF_ERROR_NO_MEM;
     }
     else
     {
         for (index = 0; index < MAX_BUFFERS; index++)
         {
             if (INVALID_PACKET == DATA_QUEUE_ELEMENT_GET_PTYPE(index))
             {
                 // Found a free element: allocate, and end search.
                 *p_element_index = index;
                 DATA_QUEUE_ELEMENT_SET_PTYPE(index, packet_type);
                 retval = NRF_SUCCESS;
                 m_data_queue.count++;
                 break;
             }
         }
     }
     return retval;
 }
static void data_queue_flush (void) static
Definition at line 169 of file dfu_transport_serial.c.
References data_queue_element_free(), and MAX_BUFFERS.
 {
     uint32_t index;
     for (index = 0; index < MAX_BUFFERS; index++)
     {
          // In this case it does not matter if free succeeded or not as data packets are being flushed because DFU Trnsport was closed
         (void)data_queue_element_free(index);
     }
 }
static void dfu_cb_handler (uint32_t packet, uint32_t result, uint8_t * p_data) static
Function for handling the callback events from the dfu module. Callbacks are expected when dfu_data_pkt_handle has been executed.
Parameters
[in] packet Packet type for which this callback is related. START_PACKET, DATA_PACKET.
[in] result Operation result code. NRF_SUCCESS when a queued operation was successful.
[in] p_data Pointer to the data to which the operation is related.
Definition at line 188 of file dfu_transport_serial.c.
 {
     APP_ERROR_CHECK(result);
 }
static void process_dfu_packet (void * p_event_data, uint16_t event_size) static
Definition at line 194 of file dfu_transport_serial.c.
References dfu_data_queue_t::data_packet, DATA_PACKET, dfu_update_packet_t::data_packet, data_queue_element_free(), DATA_QUEUE_ELEMENT_GET_PTYPE, DATA_QUEUE_EMPTY, dfu_data_pkt_handle(), dfu_image_activate(), dfu_image_validate(), dfu_init_pkt_complete(), dfu_init_pkt_handle(), dfu_start_pkt_handle(), INIT_PACKET, INVALID_PACKET, MAX_BUFFERS, dfu_data_packet_t::p_data_packet, dfu_update_packet_t::packet_type, dfu_update_packet_t::params, START_PACKET, dfu_update_packet_t::start_packet, and STOP_DATA_PACKET.
 {
     uint32_t              retval;
     uint32_t              index;
     dfu_update_packet_t * packet;
         while (false == DATA_QUEUE_EMPTY())
         {
             // Fetch the element to be processed.
             for (index = 0; index < MAX_BUFFERS ; index++)
             {
                 packet = &m_data_queue.data_packet[index];
                 if (INVALID_PACKET != packet->packet_type)
                 {
                     switch (DATA_QUEUE_ELEMENT_GET_PTYPE(index))
                     {
                         case DATA_PACKET:
                             (void)dfu_data_pkt_handle(packet);
                             break;
                         case START_PACKET:
                             packet->params.start_packet =
                                 (dfu_start_packet_t*)packet->params.data_packet.p_data_packet;
                             retval = dfu_start_pkt_handle(packet);
                             APP_ERROR_CHECK(retval);
                             break;
                         case INIT_PACKET:
                             (void)dfu_init_pkt_handle(packet);
                             retval = dfu_init_pkt_complete();
                             APP_ERROR_CHECK(retval);
                             break;
                         case STOP_DATA_PACKET:
                             (void)dfu_image_validate();
                             (void)dfu_image_activate();
                             // Break the loop by returning.
                             return;
                         default:
                             // No implementation needed.
                             break;
                     }
                     // Free the processed element.
                     retval = data_queue_element_free(index);
                     APP_ERROR_CHECK(retval);
                 }
             }
         }
 }
void rpc_transport_event_handler (hci_transport_evt_t event)
Definition at line 249 of file dfu_transport_serial.c.
References app_sched_event_put(), data_queue_element_alloc(), DATA_QUEUE_ELEMENT_COPY_PDATA, DATA_QUEUE_ELEMENT_SET_PLEN, NRF_SUCCESS, and process_dfu_packet().
 {
     uint32_t  retval;
     uint16_t  rpc_cmd_length_read;
     uint8_t * p_rpc_cmd_buffer;
     uint8_t   element_index;
     retval = hci_transport_rx_pkt_extract(&p_rpc_cmd_buffer, &rpc_cmd_length_read);
     if (NRF_SUCCESS == retval)
     {
         // Verify if the data queue can buffer the packet.
         retval = data_queue_element_alloc(&element_index, p_rpc_cmd_buffer[0]);
         if (NRF_SUCCESS == retval)
         {
             //subtract 1 since we are interested in payload length and not the type field.
             DATA_QUEUE_ELEMENT_SET_PLEN(element_index,(rpc_cmd_length_read / sizeof(uint32_t)) - 1);
             DATA_QUEUE_ELEMENT_COPY_PDATA(element_index, &p_rpc_cmd_buffer[4]);
             retval = app_sched_event_put(NULL, 0, process_dfu_packet);
         }
     }
     if (NRF_SUCCESS != retval)
     {
         // Free the packet that could not be processed.
         retval = hci_transport_rx_pkt_consume(p_rpc_cmd_buffer);
         APP_ERROR_CHECK(retval);
     }
 }
Variable Documentation
dfu_data_queue_t m_data_queue static
Received-data packet queue.
Definition at line 72 of file dfu_transport_serial.c.