nRF51822 Beacon Firmware Documentation: Button Handler
Button Handler
Buttons handling module.
Data Structures
struct app_button_cfg_t
Button configuration structure.
struct pin_transition_t
Pin transition direction struct.
Macros
#define APP_BUTTON_SCHED_EVT_SIZE sizeof(app_button_event_t)
#define APP_BUTTON_PUSH 1
#define APP_BUTTON_RELEASE 0
#define APP_BUTTON_ACTIVE_HIGH 1
#define APP_BUTTON_ACTIVE_LOW 0
#define APP_BUTTON_INIT(BUTTONS, BUTTON_COUNT, DETECTION_DELAY, USE_SCHEDULER)
Macro for initializing the Button Handler module.
Typedefs
typedef void(* app_button_handler_t)(uint8_t pin_no, uint8_t button_action)
Button event handler type.
typedef uint32_t(* app_button_evt_schedule_func_t)(app_button_handler_t button_handler, uint8_t pin_no, uint8_t button_action)
Type of function for passing events from the Button Handler module to the scheduler.
Functions
uint32_t app_button_init (app_button_cfg_t *p_buttons, uint8_t button_count, uint32_t detection_delay, app_button_evt_schedule_func_t evt_schedule_func)
Function for initializing the Buttons.
uint32_t app_button_enable (void)
Function for enabling button detection.
uint32_t app_button_disable (void)
Function for disabling button detection.
uint32_t app_button_is_pushed (uint8_t button_id, bool *p_is_pushed)
Function for checking if a button is currently being pushed.
Detailed Description
Buttons handling module.
The button handler uses the app_gpiote to detect that a button has been pushed. To handle debouncing, it will start a timer in the GPIOTE event handler. The button will only be reported as pushed if the corresponding pin is still active when the timer expires. If there is a new GPIOTE event while the timer is running, the timer is restarted. Use the USE_SCHEDULER parameter of the APP_BUTTON_INIT() macro to select if the Scheduler is to be used or not.
Note
The app_button module uses the app_timer module. The user must ensure that the queue in app_timer is large enough to hold the app_timer_stop() / app_timer_start() operations which will be executed on each event from GPIOTE module (2 operations), as well as other app_timer operations queued simultaneously in the application.
Even if the scheduler is not used, app_button.h will include app_scheduler.h, so when compiling, app_scheduler.h must be available in one of the compiler include paths.
Macro Definition Documentation
#define APP_BUTTON_SCHED_EVT_SIZE sizeof(app_button_event_t)
Size of button events being passed through the scheduler (is to be used for computing the maximum size of scheduler events).
Definition at line 48 of file app_button.h.
#define APP_BUTTON_PUSH 1
Indicates that a button is pushed.
Definition at line 49 of file app_button.h.
#define APP_BUTTON_RELEASE 0
Indicates that a button is released.
Definition at line 50 of file app_button.h.
#define APP_BUTTON_ACTIVE_HIGH 1
Indicates that a button is active high.
Definition at line 51 of file app_button.h.
#define APP_BUTTON_ACTIVE_LOW 0
Indicates that a button is active low.
Definition at line 52 of file app_button.h.
#define APP_BUTTON_INIT (BUTTONS, BUTTON_COUNT, DETECTION_DELAY, USE_SCHEDULER)
Value:
do                                                                                             \
    {                                                                                              \
        uint32_t ERR_CODE = app_button_init((BUTTONS),                                             \
                                            (BUTTON_COUNT),                                        \
                                            (DETECTION_DELAY),                                     \
                                            (USE_SCHEDULER) ? app_button_evt_schedule : NULL);     \
        APP_ERROR_CHECK(ERR_CODE);                                                                 \
    } while (0)
Macro for initializing the Button Handler module.
It will initialize the specified pins as buttons, and configure the Button Handler module as a GPIOTE user (but it will not enable button detection). It will also connect the Button Handler module to the scheduler (if specified).
Parameters
[in] BUTTONS Array of buttons to be used (type app_button_cfg_t, must be static!).
[in] BUTTON_COUNT Number of buttons.
[in] DETECTION_DELAY Delay from a GPIOTE event until a button is reported as pushed.
[in] USE_SCHEDULER TRUE if the application is using the event scheduler, FALSE otherwise.
Definition at line 92 of file app_button.h.
Typedef Documentation
typedef void(* app_button_handler_t)(uint8_t pin_no, uint8_t button_action)
Button event handler type.
Definition at line 55 of file app_button.h.
typedef uint32_t(* app_button_evt_schedule_func_t)(app_button_handler_t button_handler, uint8_t pin_no, uint8_t button_action)
Type of function for passing events from the Button Handler module to the scheduler.
Definition at line 58 of file app_button.h.
Function Documentation
uint32_t app_button_init (app_button_cfg_t * p_buttons, uint8_t button_count, uint32_t detection_delay, app_button_evt_schedule_func_t evt_schedule_func)
Function for initializing the Buttons.
This function will initialize the specified pins as buttons, and configure the Button Handler module as a GPIOTE user (but it will not enable button detection).
Note
Normally initialization should be done using the APP_BUTTON_INIT() macro, as that will take care of connecting the Buttons module to the scheduler (if specified).
app_button_enable() function must be called in order to enable the button detection.
Parameters
[in] p_buttons Array of buttons to be used (NOTE: Must be static!).
[in] button_count Number of buttons.
[in] detection_delay Delay from a GPIOTE event until a button is reported as pushed.
[in] evt_schedule_func Function for passing button events to the scheduler. Point to app_button_evt_schedule() to connect to the scheduler. Set to NULL to make the Buttons module call the event handler directly from the delayed button push detection timeout handler.
Returns
NRF_SUCCESS on success, otherwise an error code.
Definition at line 158 of file app_button.c.
References app_timer_create(), APP_TIMER_MIN_TIMEOUT_TICKS, APP_TIMER_MODE_SINGLE_SHOT, detection_delay_timeout_handler(), gpiote_event_handler(), m_button_count, m_detection_delay, m_detection_delay_timer_id, m_evt_schedule_func, m_gpiote_user_id, NRF_ERROR_INVALID_PARAM, nrf_gpio_cfg_input(), NRF_SUCCESS, app_button_cfg_t::pin_no, and app_button_cfg_t::pull_cfg.
 {
     uint32_t err_code;
     if (detection_delay < APP_TIMER_MIN_TIMEOUT_TICKS)
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     // Save configuration.
     mp_buttons          = p_buttons;
     m_button_count      = button_count;
     m_detection_delay   = detection_delay;
     m_evt_schedule_func = evt_schedule_func;
     // Configure pins.
     uint32_t pins_transition_mask = 0;
     while (button_count--)
     {
         app_button_cfg_t * p_btn = &p_buttons[button_count];
         // Configure pin.
         nrf_gpio_cfg_input(p_btn->pin_no, p_btn->pull_cfg);
         // Build GPIOTE user registration masks.
         pins_transition_mask |= (1 << p_btn->pin_no);
     }
     // Register button module as a GPIOTE user.
     err_code = app_gpiote_user_register(&m_gpiote_user_id,
                                         pins_transition_mask,
                                         pins_transition_mask,
                                         gpiote_event_handler);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     // Create polling timer.
     return app_timer_create(&m_detection_delay_timer_id,
                             APP_TIMER_MODE_SINGLE_SHOT,
                             detection_delay_timeout_handler);
 }
uint32_t app_button_enable (void)
Function for enabling button detection.
Return values
NRF_ERROR_INVALID_PARAM GPIOTE has to many users.
NRF_ERROR_INVALID_STATE Button or GPIOTE not initialized.
NRF_SUCCESS Button detection successfully enabled.
Definition at line 207 of file app_button.c.
References m_gpiote_user_id, and NRF_ERROR_INVALID_STATE.
 {
     if (mp_buttons == NULL)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     return app_gpiote_user_enable(m_gpiote_user_id);
 }
uint32_t app_button_disable (void)
Function for disabling button detection.
Return values
NRF_ERROR_INVALID_PARAM GPIOTE has to many users.
NRF_ERROR_INVALID_STATE Button or GPIOTE not initialized.
NRF_SUCCESS Button detection successfully enabled.
Definition at line 218 of file app_button.c.
References app_timer_stop(), m_detection_delay_timer_id, m_gpiote_user_id, NRF_ERROR_INVALID_STATE, and NRF_SUCCESS.
 {
     uint32_t err_code;
     if (mp_buttons == NULL)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     err_code = app_gpiote_user_disable(m_gpiote_user_id);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     // Make sure polling timer is not running.
     return app_timer_stop(m_detection_delay_timer_id);
 }
uint32_t app_button_is_pushed (uint8_t button_id, bool * p_is_pushed)
Function for checking if a button is currently being pushed.
Parameters
[in] button_id Button index (in the app_button_cfg_t array given to app_button_init) to be checked.
[out] p_is_pushed Button state.
Return values
NRF_SUCCESS State successfully read.
NRF_ERROR_INVALID_PARAM Invalid button index.
Definition at line 239 of file app_button.c.
References app_button_cfg_t::active_state, APP_BUTTON_ACTIVE_HIGH, APP_BUTTON_ACTIVE_LOW, m_button_count, m_gpiote_user_id, NRF_ERROR_INVALID_PARAM, NRF_ERROR_INVALID_STATE, NRF_SUCCESS, and app_button_cfg_t::pin_no.
 {
     uint32_t err_code;
     uint32_t active_pins;
     if (button_id > m_button_count)
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     app_button_cfg_t * p_btn = &mp_buttons[button_id];
     if (mp_buttons == NULL)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     err_code = app_gpiote_pins_state_get(m_gpiote_user_id, &active_pins);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     if(p_btn->active_state == APP_BUTTON_ACTIVE_LOW)
     {
         // If the pin is active low, then the pin being high means it is not pushed.
         if(((active_pins >> p_btn->pin_no) & 0x01))
         {
             *p_is_pushed = false;
         }
         else
         {
             *p_is_pushed = true;
         }
     }
     else if(p_btn->active_state == APP_BUTTON_ACTIVE_HIGH)
     {
         // If the pin is active high, then the pin being high means it is pushed.
         if(((active_pins >> p_btn->pin_no) & 0x01))
         {
             *p_is_pushed = true;
         }
         else
         {
             *p_is_pushed = false;
         }
     }
     return NRF_SUCCESS;
 }