nRF51822 Beacon Firmware Documentation: DFU transport API.
DFU transport API.
DFU transport module interface.
Functions
uint32_t dfu_transport_update_start (void)
Function for starting the update of Device Firmware.
uint32_t dfu_transport_close (void)
Function for closing the transport layer.
Detailed Description
DFU transport module interface.
Function Documentation
uint32_t dfu_transport_update_start (void)
Function for starting the update of Device Firmware.
Return values
NRF_SUCCESS Operation success.
Definition at line 867 of file dfu_transport_ble_mod.c.
References advertising_start(), APP_GPIOTE_MAX_USERS, ble_evt_dispatch(), conn_params_init(), data_queue_init(), dfu_ble_get_peer_data(), dfu_cb_handler(), dfu_register_callback(), gap_params_init(), leds_init(), m_ble_peer_data_valid, m_pkt_type, NRF_SUCCESS, PKT_TYPE_INVALID, rpc_transport_event_handler(), sec_params_init(), and services_init().
 {
     uint32_t err_code;
     m_pkt_type = PKT_TYPE_INVALID;
     err_code = softdevice_ble_evt_handler_set(ble_evt_dispatch);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     dfu_register_callback(dfu_cb_handler);
     err_code = hci_mem_pool_open();
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = dfu_ble_get_peer_data(&m_ble_peer_data);
     if (err_code == NRF_SUCCESS)
     {
         m_ble_peer_data_valid = true;
     }
     gap_params_init();
     services_init();
     conn_params_init();
     sec_params_init();
     advertising_start();
     return NRF_SUCCESS;
 }
uint32_t dfu_transport_close (void)
Function for closing the transport layer.
Return values
NRF_SUCCESS Operation success.
Definition at line 903 of file dfu_transport_ble_mod.c.
References advertising_stop(), ble_conn_params_stop(), BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION, data_queue_flush(), IS_CONNECTED, m_conn_handle, and NRF_SUCCESS.
 {
     uint32_t err_code;
     if (IS_CONNECTED())
     {
         // Disconnect from peer.
         err_code = sd_ble_gap_disconnect(m_conn_handle, BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION);
         APP_ERROR_CHECK(err_code);
     }
     else
     {
         // If not connected, then the device will be advertising. Hence stop the advertising.
         advertising_stop();
     }
     err_code = ble_conn_params_stop();
     APP_ERROR_CHECK(err_code);
     return NRF_SUCCESS;
 }