nRF51822 Beacon Firmware Documentation: Bootloader API.
Bootloader API.
Bootloader module interface.
Modules
Types and definitions.
Bootloader module type and definitions.
Functions
uint32_t bootloader_init (void)
Function for initializing the Bootloader.
bool bootloader_app_is_valid (uint32_t app_addr)
Function for validating application region in flash.
uint32_t bootloader_dfu_start (void)
Function for starting the Device Firmware Update.
void bootloader_app_start (uint32_t app_addr)
Function for exiting bootloader and booting into application.
void bootloader_settings_get (bootloader_settings_t *const p_settings)
Function for retrieving the bootloader settings.
void bootloader_dfu_update_process (dfu_update_status_t update_status)
Function for processing DFU status update.
bool bootloader_dfu_sd_in_progress (void)
Function getting state of SoftDevice update in progress. After a successfull SoftDevice transfer the system restarts in orderto disable SoftDevice and complete the update.
uint32_t bootloader_dfu_sd_update_continue (void)
Function for continuing the Device Firmware Update of a SoftDevice.
uint32_t bootloader_dfu_sd_update_finalize (void)
Function for finalizing the Device Firmware Update of a SoftDevice.
Detailed Description
Bootloader module interface.
Function Documentation
uint32_t bootloader_init (void)
Function for initializing the Bootloader.
Return values
NRF_SUCCESS If bootloader was succesfully initialized.
Definition at line 247 of file bootloader.c.
References pstorage_module_param_t::block_count, pstorage_module_param_t::block_size, pstorage_module_param_t::cb, m_bootsettings_handle, NRF_SUCCESS, pstorage_callback_handler(), pstorage_init(), and pstorage_register().
 {
     uint32_t                err_code;
     pstorage_module_param_t storage_params;
     storage_params.cb          = pstorage_callback_handler;
     storage_params.block_size  = sizeof(bootloader_settings_t);
     storage_params.block_count = 1;
     err_code = pstorage_init();
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = pstorage_register(&storage_params, &m_bootsettings_handle);
     return err_code;
 }
bool bootloader_app_is_valid (uint32_t app_addr)
Function for validating application region in flash.
Parameters
[in] app_addr Address to the region in flash where the application is stored.
Return values
true If Application region is valid.
false If Application region is not valid.
Definition at line 98 of file bootloader.c.
References bootloader_settings_t::bank_0, bootloader_settings_t::bank_0_crc, bootloader_settings_t::bank_0_size, BANK_VALID_APP, bootloader_util_settings_get(), DFU_BANK_0_REGION_START, and EMPTY_FLASH_MASK.
 {
     const bootloader_settings_t * p_bootloader_settings;
     // There exists an application in CODE region 1.
     if (*((uint32_t *)app_addr) == EMPTY_FLASH_MASK)
     {
         return false;
     }
     bool success = false;
     bootloader_util_settings_get(&p_bootloader_settings);
     // The application in CODE region 1 is flagged as valid during update.
     if (p_bootloader_settings->bank_0 == BANK_VALID_APP)
     {
         uint16_t image_crc = 0;
         // A stored crc value of 0 indicates that CRC checking is not used.
         if (p_bootloader_settings->bank_0_crc != 0)
         {
             image_crc = crc16_compute((uint8_t *)DFU_BANK_0_REGION_START,
                                       p_bootloader_settings->bank_0_size,
                                       NULL);
         }
         success = (image_crc == p_bootloader_settings->bank_0_crc);
     }
     return success;
 }
uint32_t bootloader_dfu_start (void)
Function for starting the Device Firmware Update.
Return values
NRF_SUCCESS If new application image was successfully transferred.
Definition at line 268 of file bootloader.c.
References dfu_init(), dfu_transport_update_start(), NRF_SUCCESS, and wait_for_events().
 {
     uint32_t err_code;
     // Clear swap if banked update is used.
     err_code = dfu_init();
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = dfu_transport_update_start();
     wait_for_events();
     return err_code;
 }
void bootloader_app_start (uint32_t app_addr)
Function for exiting bootloader and booting into application.
This function will disable SoftDevice and all interrupts before jumping to application. The SoftDevice vector table base for interrupt forwarding will be set the application address.
Parameters
[in] app_addr Address to the region where the application is stored.
Definition at line 308 of file bootloader.c.
References bootloader_util_app_start(), CODE_REGION_1_START, interrupts_disable(), and NRF_POWER.
 {
     // If the applications CRC has been checked and passed, the magic number will be written and we
     // can start the application safely.
     uint32_t err_code = sd_softdevice_disable();
     APP_ERROR_CHECK(err_code);
     // FIX: https://devzone.nordicsemi.com/question/32497/power-consumption-of-ble_app_beacon/
     NRF_POWER->TASKS_LOWPWR = 1;
     interrupts_disable();
     err_code = sd_softdevice_vector_table_base_set(CODE_REGION_1_START);
     APP_ERROR_CHECK(err_code);
     bootloader_util_app_start(CODE_REGION_1_START);
 }
void bootloader_settings_get (bootloader_settings_t *const p_settings)
Function for retrieving the bootloader settings.
Parameters
[out] p_settings A copy of the current bootloader settings is returned in the structure provided.
Definition at line 382 of file bootloader.c.
References bootloader_settings_t::app_image_size, bootloader_settings_t::bank_0, bootloader_settings_t::bank_0_crc, bootloader_settings_t::bank_0_size, bootloader_settings_t::bank_1, bootloader_settings_t::bl_image_size, m_bootsettings_handle, pstorage_load(), bootloader_settings_t::sd_image_size, and bootloader_settings_t::sd_image_start.
 {
     bootloader_settings_t bootloader_settings;
     (void) pstorage_load((uint8_t *)&bootloader_settings,
                          &m_bootsettings_handle,
                          sizeof(bootloader_settings_t),
                          0);
     p_settings->bank_0         = bootloader_settings.bank_0;
     p_settings->bank_0_crc     = bootloader_settings.bank_0_crc;
     p_settings->bank_0_size    = bootloader_settings.bank_0_size;
     p_settings->bank_1         = bootloader_settings.bank_1;
     p_settings->sd_image_size  = bootloader_settings.sd_image_size;
     p_settings->bl_image_size  = bootloader_settings.bl_image_size;
     p_settings->app_image_size = bootloader_settings.app_image_size;
     p_settings->sd_image_start = bootloader_settings.sd_image_start;
 }
void bootloader_dfu_update_process (dfu_update_status_t update_status)
Function for processing DFU status update.
Parameters
[in] update_status DFU update status.
Definition at line 145 of file bootloader.c.
References dfu_update_status_t::app_crc, bootloader_settings_t::app_image_size, dfu_update_status_t::app_size, bootloader_settings_t::bank_0, bootloader_settings_t::bank_0_crc, bootloader_settings_t::bank_0_size, bootloader_settings_t::bank_1, BANK_INVALID_APP, BANK_VALID_APP, BANK_VALID_BOOT, BANK_VALID_SD, bootloader_settings_t::bl_image_size, dfu_update_status_t::bl_size, BOOTLOADER_RESET, bootloader_settings_save(), BOOTLOADER_SETTINGS_SAVING, BOOTLOADER_TIMEOUT, bootloader_util_settings_get(), DFU_BANK_0_ERASED, DFU_RESET, DFU_TIMEOUT, dfu_transport_close(), DFU_UPDATE_APP_COMPLETE, DFU_UPDATE_BOOT_COMPLETE, DFU_UPDATE_SD_COMPLETE, DFU_UPDATE_SD_SWAPPED, m_update_status, bootloader_settings_t::sd_image_size, bootloader_settings_t::sd_image_start, dfu_update_status_t::sd_image_start, dfu_update_status_t::sd_size, and dfu_update_status_t::status_code.
 {
     static bootloader_settings_t  settings;
     const bootloader_settings_t * p_bootloader_settings;
     bootloader_util_settings_get(&p_bootloader_settings);
     if (update_status.status_code == DFU_UPDATE_APP_COMPLETE)
     {
         settings.bank_0_crc  = update_status.app_crc;
         settings.bank_0_size = update_status.app_size;
         settings.bank_0      = BANK_VALID_APP;
         settings.bank_1      = BANK_INVALID_APP;
         m_update_status      = BOOTLOADER_SETTINGS_SAVING;
         bootloader_settings_save(&settings);
     }
     else if (update_status.status_code == DFU_UPDATE_SD_COMPLETE)
     {
         settings.bank_0_crc     = update_status.app_crc;
         settings.bank_0_size    = update_status.sd_size +
                                   update_status.bl_size +
                                   update_status.app_size;
         settings.bank_0         = BANK_VALID_SD;
         settings.bank_1         = BANK_INVALID_APP;
         settings.sd_image_size  = update_status.sd_size;
         settings.bl_image_size  = update_status.bl_size;
         settings.app_image_size = update_status.app_size;
         settings.sd_image_start = update_status.sd_image_start;
         m_update_status         = BOOTLOADER_SETTINGS_SAVING;
         bootloader_settings_save(&settings);
     }
     else if (update_status.status_code == DFU_UPDATE_BOOT_COMPLETE)
     {
         settings.bank_0         = p_bootloader_settings->bank_0;
         settings.bank_0_crc     = p_bootloader_settings->bank_0_crc;
         settings.bank_0_size    = p_bootloader_settings->bank_0_size;
         settings.bank_1         = BANK_VALID_BOOT;
         settings.sd_image_size  = update_status.sd_size;
         settings.bl_image_size  = update_status.bl_size;
         settings.app_image_size = update_status.app_size;
         m_update_status         = BOOTLOADER_SETTINGS_SAVING;
         bootloader_settings_save(&settings);
     }
     else if (update_status.status_code == DFU_UPDATE_SD_SWAPPED)
     {
         if (p_bootloader_settings->bank_0 == BANK_VALID_SD)
         {
             settings.bank_0_crc     = 0;
             settings.bank_0_size    = 0;
             settings.bank_0         = BANK_INVALID_APP;
         }
         // This handles cases where SoftDevice was not updated, hence bank0 keeps its settings.
         else
         {
             settings.bank_0         = p_bootloader_settings->bank_0;
             settings.bank_0_crc     = p_bootloader_settings->bank_0_crc;
             settings.bank_0_size    = p_bootloader_settings->bank_0_size;
         }
         settings.bank_1         = BANK_INVALID_APP;
         settings.sd_image_size  = 0;
         settings.bl_image_size  = 0;
         settings.app_image_size = 0;
         m_update_status         = BOOTLOADER_SETTINGS_SAVING;
         bootloader_settings_save(&settings);
     }
     else if (update_status.status_code == DFU_TIMEOUT)
     {
         // Timeout has occurred. Close the connection with the DFU Controller.
         uint32_t err_code = dfu_transport_close();
         APP_ERROR_CHECK(err_code);
         m_update_status = BOOTLOADER_TIMEOUT;
     }
     else if (update_status.status_code == DFU_BANK_0_ERASED)
     {
         settings.bank_0_crc  = 0;
         settings.bank_0_size = 0;
         settings.bank_0      = BANK_INVALID_APP;
         settings.bank_1      = p_bootloader_settings->bank_1;
         bootloader_settings_save(&settings);
     }
     else if (update_status.status_code == DFU_RESET)
     {
         // Reset requested. Close the connection with the DFU Controller.
         uint32_t err_code = dfu_transport_close();
         APP_ERROR_CHECK(err_code);
         m_update_status = BOOTLOADER_RESET;
     }
     else
     {
         // No implementation needed.
     }
 }
bool bootloader_dfu_sd_in_progress (void)
Function getting state of SoftDevice update in progress. After a successfull SoftDevice transfer the system restarts in orderto disable SoftDevice and complete the update.
Return values
true A SoftDevice update is in progress. This indicates that second stage of a SoftDevice update procedure can be initiated.
false No SoftDevice update is in progress.
Definition at line 327 of file bootloader.c.
References bootloader_settings_t::bank_0, bootloader_settings_t::bank_1, BANK_VALID_BOOT, BANK_VALID_SD, and bootloader_util_settings_get().
 {
     const bootloader_settings_t * p_bootloader_settings;
     bootloader_util_settings_get(&p_bootloader_settings);
     if (p_bootloader_settings->bank_0 == BANK_VALID_SD ||
         p_bootloader_settings->bank_1 == BANK_VALID_BOOT)
     {
         return true;
     }
     return false;
 }
uint32_t bootloader_dfu_sd_update_continue (void)
Function for continuing the Device Firmware Update of a SoftDevice.
Return values
NRF_SUCCESS If the final stage of SoftDevice update was successful.
Definition at line 343 of file bootloader.c.
References dfu_bl_image_swap(), dfu_bl_image_validate(), dfu_sd_image_swap(), dfu_sd_image_validate(), nrf_delay_ms(), and NRF_SUCCESS.
 {
     uint32_t err_code;
     if ((dfu_sd_image_validate() == NRF_SUCCESS) &&
         (dfu_bl_image_validate() == NRF_SUCCESS))
     {
         return NRF_SUCCESS;
     }
     // Ensure that flash operations are not executed within the first 100 ms seconds to allow
     // a debugger to be attached.
     nrf_delay_ms(100);
     err_code = dfu_sd_image_swap();
     APP_ERROR_CHECK(err_code);
     err_code = dfu_sd_image_validate();
     APP_ERROR_CHECK(err_code);
     err_code = dfu_bl_image_swap();
     APP_ERROR_CHECK(err_code);
     return err_code;
 }
uint32_t bootloader_dfu_sd_update_finalize (void)
Function for finalizing the Device Firmware Update of a SoftDevice.
Return values
NRF_SUCCESS If the final stage of SoftDevice update was successful.
Definition at line 370 of file bootloader.c.
References bootloader_dfu_update_process(), DFU_UPDATE_SD_SWAPPED, NRF_SUCCESS, and wait_for_events().
 {
     dfu_update_status_t update_status = {DFU_UPDATE_SD_SWAPPED, };
     bootloader_dfu_update_process(update_status);
     wait_for_events();
     return NRF_SUCCESS;
 }