nRF51822 Beacon Firmware Documentation: Device Firmware Update Service
Device Firmware Update Service
Device Firmware Update Service.
Data Structures
struct ble_dfu_pkt_write_t
DFU Packet structure.
struct ble_pkt_rcpt_notif_req_t
Packet receipt notification request structure.
struct ble_dfu_evt_t
DFU Event structure.
struct ble_dfu_s
DFU service structure.
struct ble_dfu_init_t
DFU service initialization structure.
Macros
#define BLE_DFU_SERVICE_UUID 0x1530
#define BLE_DFU_PKT_CHAR_UUID 0x1532
#define BLE_DFU_CTRL_PT_UUID 0x1531
#define BLE_DFU_STATUS_REP_UUID 0x1533
#define BLE_DFU_REV_CHAR_UUID 0x1534
Typedefs
typedef struct ble_dfu_s ble_dfu_t
DFU service structure.
typedef void(* ble_dfu_evt_handler_t)(ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
DFU Service event handler type.
Enumerations
enum ble_dfu_evt_type_t {
BLE_DFU_START, BLE_DFU_RECEIVE_INIT_DATA, BLE_DFU_RECEIVE_APP_DATA, BLE_DFU_VALIDATE,
BLE_DFU_ACTIVATE_N_RESET, BLE_DFU_SYS_RESET, BLE_DFU_PKT_RCPT_NOTIF_ENABLED, BLE_DFU_PKT_RCPT_NOTIF_DISABLED,
BLE_DFU_PACKET_WRITE, BLE_DFU_BYTES_RECEIVED_SEND
}
DFU Event type.
enum ble_dfu_procedure_t {
BLE_DFU_START_PROCEDURE = 1, BLE_DFU_INIT_PROCEDURE = 2, BLE_DFU_RECEIVE_APP_PROCEDURE = 3, BLE_DFU_VALIDATE_PROCEDURE = 4,
BLE_DFU_PKT_RCPT_REQ_PROCEDURE = 8
}
DFU Procedure type.
enum ble_dfu_resp_val_t {
BLE_DFU_RESP_VAL_SUCCESS = 1, BLE_DFU_RESP_VAL_INVALID_STATE, BLE_DFU_RESP_VAL_NOT_SUPPORTED, BLE_DFU_RESP_VAL_DATA_SIZE,
BLE_DFU_RESP_VAL_CRC_ERROR, BLE_DFU_RESP_VAL_OPER_FAILED
}
DFU Response value type.
Functions
void ble_dfu_on_ble_evt (ble_dfu_t *p_dfu, ble_evt_t *p_ble_evt)
Function for handling a BLE event.
uint32_t ble_dfu_init (ble_dfu_t *p_dfu, ble_dfu_init_t *p_dfu_init)
Function for initializing the DFU service.
uint32_t ble_dfu_response_send (ble_dfu_t *p_dfu, ble_dfu_procedure_t dfu_proc, ble_dfu_resp_val_t resp_val)
Function for sending response to a control point command.
uint32_t ble_dfu_bytes_rcvd_report (ble_dfu_t *p_dfu, uint32_t num_of_firmware_bytes_rcvd)
Function for notifying the peer about the number of bytes of firmware data received.
uint32_t ble_dfu_pkts_rcpt_notify (ble_dfu_t *p_dfu, uint32_t num_of_firmware_bytes_rcvd)
Function for sending Packet Receipt Notification to the peer.
Detailed Description
Device Firmware Update Service.
The Device Firmware Update (DFU) service is a GATT based service that can be used for performing firmware updates over BLE. Note that this implementation uses vendor specific UUIDs for service and characteristics and is intended to demonstrate the firmware updates over BLE. Refer ota_spec_sec and ota_profile_section for more information on the service and profile respectively.
Macro Definition Documentation
#define BLE_DFU_SERVICE_UUID 0x1530
The UUID of the DFU Service.
Definition at line 36 of file ble_dfu.h.
#define BLE_DFU_PKT_CHAR_UUID 0x1532
The UUID of the DFU Packet Characteristic.
Definition at line 37 of file ble_dfu.h.
#define BLE_DFU_CTRL_PT_UUID 0x1531
The UUID of the DFU Control Point.
Definition at line 38 of file ble_dfu.h.
#define BLE_DFU_STATUS_REP_UUID 0x1533
The UUID of the DFU Status Report Characteristic.
Definition at line 39 of file ble_dfu.h.
#define BLE_DFU_REV_CHAR_UUID 0x1534
The UUID of the DFU Revision Characteristic.
Definition at line 40 of file ble_dfu.h.
Typedef Documentation
typedef struct ble_dfu_s ble_dfu_t
DFU service structure.
This structure contains status information related to the service.
Definition at line 124 of file ble_dfu.h.
typedef void(* ble_dfu_evt_handler_t)(ble_dfu_t *p_dfu, ble_dfu_evt_t *p_evt)
DFU Service event handler type.
Definition at line 127 of file ble_dfu.h.
Enumeration Type Documentation
enum ble_dfu_evt_type_t
DFU Event type.
This enumeration contains the types of events that will be received from the DFU Service.
Enumerator
BLE_DFU_START
The event indicating that the peer wants the application to prepare for a new firmware update.
BLE_DFU_RECEIVE_INIT_DATA
The event indicating that the peer wants the application to prepare to receive init parameters.
BLE_DFU_RECEIVE_APP_DATA
The event indicating that the peer wants the application to prepare to receive the new firmware image.
BLE_DFU_VALIDATE
The event indicating that the peer wants the application to validate the newly received firmware image.
BLE_DFU_ACTIVATE_N_RESET
The event indicating that the peer wants the application to undergo activate new firmware and restart with new valid application
BLE_DFU_SYS_RESET
The event indicating that the peer wants the application to undergo a reset and start the currently valid application image.
BLE_DFU_PKT_RCPT_NOTIF_ENABLED
The event indicating that the peer has enabled packet receipt notifications. It is the responsibility of the application to call ble_dfu_pkts_rcpt_notify each time the number of packets indicated by num_of_pkts field in ble_dfu_evt_t is received.
BLE_DFU_PKT_RCPT_NOTIF_DISABLED
The event indicating that the peer has disabled the packet receipt notifications.
BLE_DFU_PACKET_WRITE
The event indicating that the peer has written a value to the 'DFU Packet' characteristic. The data received from the peer will be present in the BLE_DFU_PACKET_WRITE element contained within ble_dfu_evt_t.
BLE_DFU_BYTES_RECEIVED_SEND
The event indicating that the peer is requesting for the number of bytes of firmware data last received by the application. It is the responsibility of the application to call ble_dfu_pkts_rcpt_notify in response to this event.
Definition at line 46 of file ble_dfu.h.
 {
     BLE_DFU_START,
     BLE_DFU_RECEIVE_INIT_DATA,
     BLE_DFU_RECEIVE_APP_DATA,
     BLE_DFU_VALIDATE,
     BLE_DFU_ACTIVATE_N_RESET,
     BLE_DFU_SYS_RESET,
     BLE_DFU_PKT_RCPT_NOTIF_ENABLED,
     BLE_DFU_PKT_RCPT_NOTIF_DISABLED,
     BLE_DFU_PACKET_WRITE,
     BLE_DFU_BYTES_RECEIVED_SEND
 } ble_dfu_evt_type_t;
enum ble_dfu_procedure_t
DFU Procedure type.
This enumeration contains the types of DFU procedures.
Enumerator
BLE_DFU_START_PROCEDURE
DFU Start procedure.
BLE_DFU_INIT_PROCEDURE
DFU Initialization procedure.
BLE_DFU_RECEIVE_APP_PROCEDURE
Firmware receiving procedure.
BLE_DFU_VALIDATE_PROCEDURE
Firmware image validation procedure .
BLE_DFU_PKT_RCPT_REQ_PROCEDURE
Packet receipt notification request procedure.
Definition at line 64 of file ble_dfu.h.
 {
     BLE_DFU_START_PROCEDURE        = 1,
     BLE_DFU_INIT_PROCEDURE         = 2,
     BLE_DFU_RECEIVE_APP_PROCEDURE  = 3,
     BLE_DFU_VALIDATE_PROCEDURE     = 4,
     BLE_DFU_PKT_RCPT_REQ_PROCEDURE = 8
 } ble_dfu_procedure_t;
enum ble_dfu_resp_val_t
DFU Response value type.
Enumerator
BLE_DFU_RESP_VAL_SUCCESS
Success.
BLE_DFU_RESP_VAL_INVALID_STATE
Invalid state.
BLE_DFU_RESP_VAL_NOT_SUPPORTED
Operation not supported.
BLE_DFU_RESP_VAL_DATA_SIZE
Data size exceeds limit.
BLE_DFU_RESP_VAL_CRC_ERROR
CRC Error.
BLE_DFU_RESP_VAL_OPER_FAILED
Operation failed.
Definition at line 75 of file ble_dfu.h.
 {
     BLE_DFU_RESP_VAL_SUCCESS = 1,
     BLE_DFU_RESP_VAL_INVALID_STATE,
     BLE_DFU_RESP_VAL_NOT_SUPPORTED,
     BLE_DFU_RESP_VAL_DATA_SIZE,
     BLE_DFU_RESP_VAL_CRC_ERROR,
     BLE_DFU_RESP_VAL_OPER_FAILED
 } ble_dfu_resp_val_t;
Function Documentation
void ble_dfu_on_ble_evt (ble_dfu_t * p_dfu, ble_evt_t * p_ble_evt)
Function for handling a BLE event.
The DFU service expects the application to call this function each time an event is received from the S110 SoftDevice. This function processes the event, if it is relevant for the DFU service and calls the DFU event handler of the application if necessary.
Parameters
[in] p_dfu Pointer to the DFU service structure.
[in] p_ble_evt Pointer to the event received from S110 SoftDevice.
Definition at line 516 of file ble_dfu.c.
References BLE_GAP_EVT_CONNECTED, BLE_GAP_EVT_DISCONNECTED, BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST, BLE_GATTS_EVT_WRITE, ble_dfu_s::evt_handler, ble_evt_hdr_t::evt_id, ble_evt_t::header, on_connect(), on_disconnect(), on_rw_auth_req(), and on_write().
 {
     if ((p_dfu == NULL) || (p_ble_evt == NULL))
     {
         return;
     }
     if (p_dfu->evt_handler != NULL)
     {
         switch (p_ble_evt->header.evt_id)
         {
             case BLE_GAP_EVT_CONNECTED:
                 on_connect(p_dfu, p_ble_evt);
                 break;
             case BLE_GATTS_EVT_WRITE:
                 on_write(p_dfu, p_ble_evt);
                 break;
             case BLE_GAP_EVT_DISCONNECTED:
                 on_disconnect(p_dfu, p_ble_evt);
                 break;
             case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
                 on_rw_auth_req(p_dfu, p_ble_evt);
                 break;
             default:
                 // No implementation needed.
                 break;
         }
     }
 }
uint32_t ble_dfu_init (ble_dfu_t * p_dfu, ble_dfu_init_t * p_dfu_init)
Function for initializing the DFU service.
Parameters
[out] p_dfu Device Firmware Update service structure. This structure will have to be supplied by the application. It will be initialized by this function, and will later be used to identify the service instance.
[in] p_dfu_init Information needed to initialize the service.
Returns
NRF_SUCCESS if the DFU service and its characteristics were successfully added to the S110 SoftDevice. Otherwise an error code. This function returns NRF_ERROR_NULL if the value of evt_handler in p_dfu_init structure provided is NULL or if the pointers supplied as input are NULL.
Definition at line 447 of file ble_dfu.c.
References BLE_CONN_HANDLE_INVALID, BLE_DFU_SERVICE_UUID, BLE_GATTS_SRVC_TYPE_PRIMARY, ble_dfu_s::conn_handle, dfu_ctrl_pt_add(), dfu_pkt_char_add(), dfu_rev_char_add(), ble_dfu_s::error_handler, ble_dfu_init_t::error_handler, ble_dfu_s::evt_handler, ble_dfu_init_t::evt_handler, m_is_dfu_service_initialized, NRF_ERROR_NULL, NRF_SUCCESS, ble_dfu_s::service_handle, ble_uuid_t::type, ble_uuid_t::uuid, and ble_dfu_s::uuid_type.
 {
     if ((p_dfu == NULL) || (p_dfu_init == NULL) || (p_dfu_init->evt_handler == NULL))
     {
         return NRF_ERROR_NULL;
     }
     p_dfu->conn_handle = BLE_CONN_HANDLE_INVALID;
     ble_uuid_t service_uuid;
     uint32_t   err_code;
     const ble_uuid128_t base_uuid128 =
     {
         {
             0x23, 0xD1, 0xBC, 0xEA, 0x5F, 0x78, 0x23, 0x15,
             0xDE, 0xEF, 0x12, 0x12, 0x00, 0x00, 0x00, 0x00
         }
     };
     service_uuid.uuid = BLE_DFU_SERVICE_UUID;
     err_code = sd_ble_uuid_vs_add(&base_uuid128, &(service_uuid.type));
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY,
                                         &service_uuid,
                                         &(p_dfu->service_handle));
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     p_dfu->uuid_type = service_uuid.type;
     err_code = dfu_pkt_char_add(p_dfu);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = dfu_ctrl_pt_add(p_dfu);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = dfu_rev_char_add(p_dfu, p_dfu_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     p_dfu->evt_handler = p_dfu_init->evt_handler;
     if (p_dfu_init->error_handler != NULL)
     {
         p_dfu->error_handler = p_dfu_init->error_handler;
     }
     m_is_dfu_service_initialized = true;
     return NRF_SUCCESS;
 }
uint32_t ble_dfu_response_send (ble_dfu_t * p_dfu, ble_dfu_procedure_t dfu_proc, ble_dfu_resp_val_t resp_val)
Function for sending response to a control point command.
This function will encode a DFU Control Point response using the given input parameters and will send a notification of the same to the peer.
Parameters
[in] p_dfu Pointer to the DFU service structure.
[in] dfu_proc Procedure for which this response is to be sent.
[in] resp_val Response value.
Returns
NRF_SUCCESS if the DFU Service has successfully requested the S110 SoftDevice to send the notification. Otherwise an error code. This function returns NRF_ERROR_INVALID_STATE if the device is not connected to a peer or if the DFU service is not initialized or if the notification of the DFU Status Report characteristic was not enabled by the peer. It returns NRF_ERROR_NULL if the pointer p_dfu is NULL.
Definition at line 620 of file ble_dfu.c.
References BLE_CONN_HANDLE_INVALID, BLE_GATT_HVX_NOTIFICATION, ble_dfu_s::conn_handle, ble_dfu_s::dfu_ctrl_pt_handles, ble_gatts_hvx_params_t::handle, m_is_dfu_service_initialized, m_notif_buffer, NRF_ERROR_INVALID_STATE, NRF_ERROR_NULL, ble_gatts_hvx_params_t::offset, OP_CODE_RESPONSE, ble_gatts_hvx_params_t::p_data, ble_gatts_hvx_params_t::p_len, ble_gatts_hvx_params_t::type, and ble_gatts_char_handles_t::value_handle.
 {
     if (p_dfu == NULL)
     {
         return NRF_ERROR_NULL;
     }
     if ((p_dfu->conn_handle == BLE_CONN_HANDLE_INVALID) || !m_is_dfu_service_initialized)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     ble_gatts_hvx_params_t hvx_params;
     uint16_t               index = 0;
     m_notif_buffer[index++] = OP_CODE_RESPONSE;
     // Encode the Request Op code
     m_notif_buffer[index++] = (uint8_t)dfu_proc;
     // Encode the Response Value.
     m_notif_buffer[index++] = (uint8_t)resp_val;
     memset(&hvx_params, 0, sizeof(hvx_params));
     hvx_params.handle = p_dfu->dfu_ctrl_pt_handles.value_handle;
     hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
     hvx_params.offset = 0;
     hvx_params.p_len  = &index;
     hvx_params.p_data = m_notif_buffer;
     return sd_ble_gatts_hvx(p_dfu->conn_handle, &hvx_params);
 }
uint32_t ble_dfu_bytes_rcvd_report (ble_dfu_t * p_dfu, uint32_t num_of_firmware_bytes_rcvd)
Function for notifying the peer about the number of bytes of firmware data received.
Parameters
[in] p_dfu Pointer to the DFU service structure.
[in] num_of_firmware_bytes_rcvd Number of bytes.
Returns
NRF_SUCCESS if the DFU Service has successfully requested the S110 SoftDevice to send the notification. Otherwise an error code. This function returns NRF_ERROR_INVALID_STATE if the device is not connected to a peer or if the DFU service is not initialized or if the notification of the DFU Status Report characteristic was not enabled by the peer. It returns NRF_ERROR_NULL if the pointer p_dfu is NULL.
Definition at line 551 of file ble_dfu.c.
References BLE_CONN_HANDLE_INVALID, BLE_DFU_RESP_VAL_SUCCESS, BLE_GATT_HVX_NOTIFICATION, ble_dfu_s::conn_handle, ble_dfu_s::dfu_ctrl_pt_handles, ble_gatts_hvx_params_t::handle, m_is_dfu_service_initialized, m_notif_buffer, NRF_ERROR_INVALID_STATE, NRF_ERROR_NULL, ble_gatts_hvx_params_t::offset, OP_CODE_IMAGE_SIZE_REQ, OP_CODE_RESPONSE, ble_gatts_hvx_params_t::p_data, ble_gatts_hvx_params_t::p_len, ble_gatts_hvx_params_t::type, and ble_gatts_char_handles_t::value_handle.
 {
     if (p_dfu == NULL)
     {
         return NRF_ERROR_NULL;
     }
     if ((p_dfu->conn_handle == BLE_CONN_HANDLE_INVALID) || !m_is_dfu_service_initialized)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     ble_gatts_hvx_params_t hvx_params;
     uint16_t               index = 0;
     // Encode the Op Code.
     m_notif_buffer[index++] = OP_CODE_RESPONSE;
     // Encode the Reqest Op Code.
     m_notif_buffer[index++] = OP_CODE_IMAGE_SIZE_REQ;
     // Encode the Response Value.
     m_notif_buffer[index++] = (uint8_t)BLE_DFU_RESP_VAL_SUCCESS;
     index += uint32_encode(num_of_firmware_bytes_rcvd, &m_notif_buffer[index]);
     memset(&hvx_params, 0, sizeof(hvx_params));
     hvx_params.handle = p_dfu->dfu_ctrl_pt_handles.value_handle;
     hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
     hvx_params.offset = 0;
     hvx_params.p_len  = &index;
     hvx_params.p_data = m_notif_buffer;
     return sd_ble_gatts_hvx(p_dfu->conn_handle, &hvx_params);
 }
uint32_t ble_dfu_pkts_rcpt_notify (ble_dfu_t * p_dfu, uint32_t num_of_firmware_bytes_rcvd)
Function for sending Packet Receipt Notification to the peer.
        This function will encode the number of bytes received as input parameter into a
        notification of the control point characteristic and send it to the peer.
Parameters
[in] p_dfu Pointer to the DFU service structure.
[in] num_of_firmware_bytes_rcvd Number of bytes of firmware image received.
Returns
NRF_SUCCESS if the DFU Service has successfully requested the S110 SoftDevice to send the notification. Otherwise an error code. This function returns NRF_ERROR_INVALID_STATE if the device is not connected to a peer or if the DFU service is not initialized or if the notification of the DFU Status Report characteristic was not enabled by the peer. It returns NRF_ERROR_NULL if the pointer p_dfu is NULL.
Definition at line 589 of file ble_dfu.c.
References BLE_CONN_HANDLE_INVALID, BLE_GATT_HVX_NOTIFICATION, ble_dfu_s::conn_handle, ble_dfu_s::dfu_ctrl_pt_handles, ble_gatts_hvx_params_t::handle, m_is_dfu_service_initialized, m_notif_buffer, NRF_ERROR_INVALID_STATE, NRF_ERROR_NULL, ble_gatts_hvx_params_t::offset, OP_CODE_PKT_RCPT_NOTIF, ble_gatts_hvx_params_t::p_data, ble_gatts_hvx_params_t::p_len, ble_gatts_hvx_params_t::type, and ble_gatts_char_handles_t::value_handle.
 {
     if (p_dfu == NULL)
     {
         return NRF_ERROR_NULL;
     }
     if ((p_dfu->conn_handle == BLE_CONN_HANDLE_INVALID) || !m_is_dfu_service_initialized)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     ble_gatts_hvx_params_t hvx_params;
     uint16_t               index = 0;
     m_notif_buffer[index++] = OP_CODE_PKT_RCPT_NOTIF;
     index += uint32_encode(num_of_firmware_bytes_rcvd, &m_notif_buffer[index]);
     memset(&hvx_params, 0, sizeof(hvx_params));
     hvx_params.handle = p_dfu->dfu_ctrl_pt_handles.value_handle;
     hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
     hvx_params.offset = 0;
     hvx_params.p_len  = &index;
     hvx_params.p_data = m_notif_buffer;
     return sd_ble_gatts_hvx(p_dfu->conn_handle, &hvx_params);
 }