nRF51822 Beacon Firmware Documentation: main.c
main.c
Bootloader project main file.
Macros
#define LED_R_MSK (1UL << LED_RGB_RED)
#define LED_G_MSK (1UL << LED_RGB_GREEN)
#define LED_B_MSK (1UL << LED_RGB_BLUE)
#define IS_SRVC_CHANGED_CHARACT_PRESENT 1
#define BOOTLOADER_BUTTON BUTTON_0
#define UPDATE_IN_PROGRESS_LED_MSK (LED_B_MSK)
#define APP_TIMER_PRESCALER 0
#define APP_TIMER_MAX_TIMERS 4
#define APP_TIMER_OP_QUEUE_SIZE 5
#define BUTTON_DETECTION_DELAY APP_TIMER_TICKS(50, APP_TIMER_PRESCALER)
#define SCHED_MAX_EVENT_DATA_SIZE MAX(APP_TIMER_SCHED_EVT_SIZE, 0)
#define SCHED_QUEUE_SIZE 20
Functions
void assert_nrf_callback (uint16_t line_num, const uint8_t *p_file_name)
Callback function for asserts in the SoftDevice.
static void leds_init (void)
Function for initialization of LEDs.
static void timers_init (void)
Function for initializing the timer handler module (app_timer).
static void buttons_init (void)
Function for initializing the button module.
static void sys_evt_dispatch (uint32_t event)
Function for dispatching a BLE stack event to all modules with a BLE stack event handler.
static void ble_stack_init (bool init_softdevice)
Function for initializing the BLE stack.
static void scheduler_init (void)
Function for event scheduler initialization.
int main (void)
Function for bootloader main entry.
Detailed Description
Bootloader project main file.
Receive start data packet.
Based on start packet, prepare NVM area to store received data.
Receive data packet.
Validate data packet.
Write Data packet to NVM.
If not finished - Wait for next packet.
Receive stop data packet.
Activate Image, boot application.
Macro Definition Documentation
#define LED_R_MSK (1UL << LED_RGB_RED)
Red LED bitmask
Definition at line 54 of file main.c.
#define LED_G_MSK (1UL << LED_RGB_GREEN)
Green LED bitmask
Definition at line 55 of file main.c.
#define LED_B_MSK (1UL << LED_RGB_BLUE)
Blue LED bitmask
Definition at line 56 of file main.c.
#define IS_SRVC_CHANGED_CHARACT_PRESENT 1
Include or not the service_changed characteristic. if not enabled, the server's database cannot be changed for the lifetime of the device
Definition at line 58 of file main.c.
#define BOOTLOADER_BUTTON BUTTON_0
Button used to enter SW update mode.
Definition at line 60 of file main.c.
#define UPDATE_IN_PROGRESS_LED_MSK (LED_B_MSK)
Led used to indicate that DFU is active.
Definition at line 61 of file main.c.
#define APP_TIMER_PRESCALER 0
Value of the RTC1 PRESCALER register.
Definition at line 63 of file main.c.
#define APP_TIMER_MAX_TIMERS 4
Maximum number of simultaneously created timers.
Definition at line 64 of file main.c.
#define APP_TIMER_OP_QUEUE_SIZE 5
Size of timer operation queues.
Definition at line 65 of file main.c.
#define BUTTON_DETECTION_DELAY APP_TIMER_TICKS(50, APP_TIMER_PRESCALER)
Delay from a GPIOTE event until a button is reported as pushed (in number of timer ticks).
Definition at line 67 of file main.c.
#define SCHED_MAX_EVENT_DATA_SIZE MAX(APP_TIMER_SCHED_EVT_SIZE, 0)
Maximum size of scheduler events.
Definition at line 69 of file main.c.
#define SCHED_QUEUE_SIZE 20
Maximum number of events in the scheduler queue.
Definition at line 71 of file main.c.
Function Documentation
void assert_nrf_callback (uint16_t line_num, const uint8_t * p_file_name)
Callback function for asserts in the SoftDevice.
This function will be called in case of an assert in the SoftDevice.
Warning
This handler is an example only and does not fit a final product. You need to analyze how your product is supposed to react in case of Assert.
On assert from the SoftDevice, the system can only recover on reset.
Parameters
[in] line_num Line number of the failing ASSERT call.
[in] file_name File name of the failing ASSERT call.
Definition at line 85 of file main.c.
References app_error_handler().
 {
     app_error_handler(0xDEADBEEF, line_num, p_file_name);
 }
static void leds_init (void) static
Function for initialization of LEDs.
Definition at line 93 of file main.c.
References led_sb_init_params_t::active_high, led_sb_init_params_t::duty_cycle_max, led_sb_init_params_t::duty_cycle_min, led_sb_init_params_t::duty_cycle_step, LED_B_MSK, LED_G_MSK, LED_R_MSK, led_softblink_init(), led_sb_init_params_t::leds_pin_bm, nrf_gpio_cfg_output(), nrf_gpio_pin_set(), led_sb_init_params_t::off_time_ms, and led_sb_init_params_t::on_time_ms.
 {
     uint32_t             err_code;
     led_sb_init_params_t led_sb_init_params;
     nrf_gpio_cfg_output(LED_RGB_RED);
     nrf_gpio_cfg_output(LED_RGB_GREEN);
     nrf_gpio_cfg_output(LED_RGB_BLUE);
     nrf_gpio_pin_set(LED_RGB_RED);
     nrf_gpio_pin_set(LED_RGB_GREEN);
     nrf_gpio_pin_set(LED_RGB_BLUE);
     led_sb_init_params.active_high     = false;
     led_sb_init_params.duty_cycle_max  = 20;
     led_sb_init_params.duty_cycle_min  = 0;
     led_sb_init_params.duty_cycle_step = 1;
     led_sb_init_params.leds_pin_bm     = (LED_R_MSK | LED_G_MSK | LED_B_MSK);
     led_sb_init_params.off_time_ms     = 2000;
     led_sb_init_params.on_time_ms      = 0;
     err_code = led_softblink_init(&led_sb_init_params);
     APP_ERROR_CHECK(err_code);
 }
static void timers_init (void) static
Function for initializing the timer handler module (app_timer).
Definition at line 121 of file main.c.
References APP_TIMER_INIT, APP_TIMER_MAX_TIMERS, APP_TIMER_OP_QUEUE_SIZE, and APP_TIMER_PRESCALER.
 {
     // Initialize timer module, making it use the scheduler.
     APP_TIMER_INIT(APP_TIMER_PRESCALER, APP_TIMER_MAX_TIMERS, APP_TIMER_OP_QUEUE_SIZE, true);
 }
static void buttons_init (void) static
Function for initializing the button module.
Definition at line 130 of file main.c.
References BOOTLOADER_BUTTON, nrf_gpio_cfg_sense_input(), and NRF_GPIO_PIN_SENSE_LOW.
 {
     nrf_gpio_cfg_sense_input(BOOTLOADER_BUTTON,
                              BUTTON_PULL,
                              NRF_GPIO_PIN_SENSE_LOW);
 }
static void sys_evt_dispatch (uint32_t event) static
Function for dispatching a BLE stack event to all modules with a BLE stack event handler.
This function is called from the scheduler in the main loop after a BLE stack event has been received.
Parameters
[in] p_ble_evt Bluetooth stack event.
Definition at line 146 of file main.c.
References pstorage_sys_event_handler().
 {
     pstorage_sys_event_handler(event);
 }
static void ble_stack_init (bool init_softdevice) static
Function for initializing the BLE stack.
Initializes the SoftDevice and the BLE event interrupt.
Parameters
[in] init_softdevice true if SoftDevice should be initialized. The SoftDevice must only be initialized if a chip reset has occured. Soft reset from application must not reinitialize the SoftDevice.
Definition at line 160 of file main.c.
References BOOTLOADER_REGION_START, ble_enable_params_t::gatts_enable_params, IS_SRVC_CHANGED_CHARACT_PRESENT, NRF_CLOCK_LFCLKSRC_RC_250_PPM_8000MS_CALIBRATION, SD_MBR_COMMAND_INIT_SD, ble_gatts_enable_params_t::service_changed, SOFTDEVICE_HANDLER_INIT, softdevice_sys_evt_handler_set(), and sys_evt_dispatch().
 {
     uint32_t         err_code;
     sd_mbr_command_t com = {SD_MBR_COMMAND_INIT_SD, };
     if (init_softdevice)
     {
         err_code = sd_mbr_command(&com);
         APP_ERROR_CHECK(err_code);
     }
     err_code = sd_softdevice_vector_table_base_set(BOOTLOADER_REGION_START);
     APP_ERROR_CHECK(err_code);
     SOFTDEVICE_HANDLER_INIT(NRF_CLOCK_LFCLKSRC_RC_250_PPM_8000MS_CALIBRATION, true);
     // Enable BLE stack
     ble_enable_params_t ble_enable_params;
     memset(&ble_enable_params, 0, sizeof(ble_enable_params));
     ble_enable_params.gatts_enable_params.service_changed = IS_SRVC_CHANGED_CHARACT_PRESENT;
     err_code = sd_ble_enable(&ble_enable_params);
     APP_ERROR_CHECK(err_code);
     err_code = softdevice_sys_evt_handler_set(sys_evt_dispatch);
     APP_ERROR_CHECK(err_code);
 }
static void scheduler_init (void) static
Function for event scheduler initialization.
Definition at line 190 of file main.c.
References APP_SCHED_INIT, SCHED_MAX_EVENT_DATA_SIZE, and SCHED_QUEUE_SIZE.
 {
     APP_SCHED_INIT(SCHED_MAX_EVENT_DATA_SIZE, SCHED_QUEUE_SIZE);
 }
int main (void)
Function for bootloader main entry.
Definition at line 198 of file main.c.
References ble_stack_init(), bootloader_app_is_valid(), bootloader_app_start(), BOOTLOADER_BUTTON, bootloader_dfu_sd_in_progress(), bootloader_dfu_sd_update_continue(), bootloader_dfu_sd_update_finalize(), BOOTLOADER_DFU_START, bootloader_dfu_start(), bootloader_init(), BOOTLOADER_REGION_START, buttons_init(), CODE_PAGE_SIZE, DFU_BANK_0_REGION_START, led_softblink_start(), led_softblink_stop(), leds_init(), NRF_FICR, nrf_gpio_pin_read(), NRF_POWER, NRF_UICR_BOOT_START_ADDRESS, scheduler_init(), timers_init(), and UPDATE_IN_PROGRESS_LED_MSK.
 {
     uint32_t err_code;
     bool     dfu_start = false;
     bool     app_reset = (NRF_POWER->GPREGRET == BOOTLOADER_DFU_START);
     if (app_reset)
     {
         NRF_POWER->GPREGRET = 0;
     }
     // This check ensures that the defined fields in the bootloader corresponds with actual
     // setting in the nRF51 chip.
     APP_ERROR_CHECK_BOOL(*((uint32_t *)NRF_UICR_BOOT_START_ADDRESS) == BOOTLOADER_REGION_START);
     APP_ERROR_CHECK_BOOL(NRF_FICR->CODEPAGESIZE == CODE_PAGE_SIZE);
     // Initialize.
     timers_init();
     buttons_init();
     leds_init();
     (void)bootloader_init();
     if (bootloader_dfu_sd_in_progress())
     {
         led_softblink_start(UPDATE_IN_PROGRESS_LED_MSK);
         err_code = bootloader_dfu_sd_update_continue();
         APP_ERROR_CHECK(err_code);
         ble_stack_init(!app_reset);
         scheduler_init();
         err_code = bootloader_dfu_sd_update_finalize();
         APP_ERROR_CHECK(err_code);
         led_softblink_stop(UPDATE_IN_PROGRESS_LED_MSK);
     }
     else
     {
         // If stack is present then continue initialization of bootloader.
         ble_stack_init(!app_reset);
         scheduler_init();
     }
     dfu_start  = app_reset;
     dfu_start |= ((nrf_gpio_pin_read(BOOTLOADER_BUTTON) == 0) ? true: false);
     if (dfu_start || (!bootloader_app_is_valid(DFU_BANK_0_REGION_START)))
     {
         led_softblink_start(UPDATE_IN_PROGRESS_LED_MSK);
         // Initiate an update of the firmware.
         err_code = bootloader_dfu_start();
         APP_ERROR_CHECK(err_code);
         led_softblink_stop(UPDATE_IN_PROGRESS_LED_MSK);
     }
     if (bootloader_app_is_valid(DFU_BANK_0_REGION_START))
     {
         // Select a bank region to use as application region.
         // @note: Only applications running from DFU_BANK_0_REGION_START is supported.
         bootloader_app_start(DFU_BANK_0_REGION_START);
     }
     NVIC_SystemReset();
 }