nRF51822 Beacon Firmware Documentation: Beacon Configuration Service
Beacon Configuration Service
Beacon Configuration Service module.
Data Structures
struct ble_bcs_init_t
Beacon Configuration Service init structure. This contains all options and data needed for initialization of the service.
struct ble_bcs_s
Beacon Configuration Service structure. This contains various status information for the service.
Macros
#define BCS_UUID_BASE {0xAD, 0xE8, 0xF3, 0xD4, 0xB8, 0x84, 0x94, 0xA0, 0xAA, 0xF5, 0xE2, 0x0F, 0x00, 0x00, 0x5A, 0x95}
#define BCS_UUID_SERVICE 0x1523
#define BCS_UUID_BEACON_MAJ_MIN_CHAR 0x1526
#define BCS_UUID_BEACON_CALIB_CHAR 0x1525
#define BCS_UUID_BEACON_ID_CHAR 0x1524
#define BCS_UUID_BEACON_COMPANY_ID_CHAR 0x1527
#define BCS_UUID_BEACON_ADV_INT_CHAR 0x1528
#define BCS_UUID_BEACON_LED_CHAR 0x1529
#define BCS_DATA_MAJ_MIN_LEN 4
#define BCS_DATA_CALIB_LEN 1
#define BCS_DATA_ID_LEN 16
#define BCS_DATA_COMPANY_ID_LEN 2
#define BCS_DATA_ADV_INT_LEN 2
#define BCS_DATA_LED_LEN 1
Typedefs
typedef struct ble_bcs_s ble_bcs_t
typedef void(* ble_bcs_write_handler_t)(ble_bcs_t *p_bcs, beacon_data_type_t type, uint8_t *data)
Beacon Configuration Service event handler type.
typedef struct ble_bcs_s ble_lbs_t
Beacon Configuration Service structure. This contains various status information for the service.
Enumerations
enum beacon_data_type_t {
beacon_maj_min_data, beacon_measured_rssi_data, beacon_uuid_data, beacon_company_id_data,
beacon_adv_interval_data, beacon_led_data
}
Functions
uint32_t ble_bcs_init (ble_bcs_t *p_bcs, const ble_bcs_init_t *p_bcs_init)
Initialize the Beacon Configuration Service.
void ble_bcs_on_ble_evt (ble_bcs_t *p_bcs, ble_evt_t *p_ble_evt)
Beacon Configuration Service BLE stack event handler.
Detailed Description
Beacon Configuration Service module.
This module implements the Beacon Configuration Service with the Battery Level characteristic. During initialization it adds the Beacon Configuration Service and Battery Level characteristic to the BLE stack datalbse. Optionally it can also add a Report Reference descriptor to the Battery Level characteristic (used when including the Beacon Configuration Service in the HID service).
If specified, the module will support notification of the Battery Level characteristic through the ble_lbs_battery_level_update() function. If an event handler is supplied by the application, the LEDButton Service will generate Beacon Configuration Service events to the application.
Note
The application must propagate BLE stack events to the Beacon Configuration Service module by calling ble_bcs_on_ble_evt() from the from the ble_stack_handler callback.
Macro Definition Documentation
#define BCS_UUID_BASE {0xAD, 0xE8, 0xF3, 0xD4, 0xB8, 0x84, 0x94, 0xA0, 0xAA, 0xF5, 0xE2, 0x0F, 0x00, 0x00, 0x5A, 0x95}
Definition at line 45 of file ble_bcs.h.
#define BCS_UUID_SERVICE 0x1523
Definition at line 47 of file ble_bcs.h.
#define BCS_UUID_BEACON_MAJ_MIN_CHAR 0x1526
Definition at line 48 of file ble_bcs.h.
#define BCS_UUID_BEACON_CALIB_CHAR 0x1525
Definition at line 49 of file ble_bcs.h.
#define BCS_UUID_BEACON_ID_CHAR 0x1524
Definition at line 50 of file ble_bcs.h.
#define BCS_UUID_BEACON_COMPANY_ID_CHAR 0x1527
Definition at line 51 of file ble_bcs.h.
#define BCS_UUID_BEACON_ADV_INT_CHAR 0x1528
Definition at line 52 of file ble_bcs.h.
#define BCS_UUID_BEACON_LED_CHAR 0x1529
Definition at line 53 of file ble_bcs.h.
#define BCS_DATA_MAJ_MIN_LEN 4
Definition at line 55 of file ble_bcs.h.
#define BCS_DATA_CALIB_LEN 1
Definition at line 56 of file ble_bcs.h.
#define BCS_DATA_ID_LEN 16
Definition at line 57 of file ble_bcs.h.
#define BCS_DATA_COMPANY_ID_LEN 2
Definition at line 58 of file ble_bcs.h.
#define BCS_DATA_ADV_INT_LEN 2
Definition at line 59 of file ble_bcs.h.
#define BCS_DATA_LED_LEN 1
Definition at line 60 of file ble_bcs.h.
Typedef Documentation
typedef struct ble_bcs_s ble_bcs_t
Definition at line 72 of file ble_bcs.h.
typedef void(* ble_bcs_write_handler_t)(ble_bcs_t *p_bcs, beacon_data_type_t type, uint8_t *data)
Beacon Configuration Service event handler type.
Definition at line 75 of file ble_bcs.h.
typedef struct ble_bcs_s ble_lbs_t
Beacon Configuration Service structure. This contains various status information for the service.
Enumeration Type Documentation
enum beacon_data_type_t
Enumerator
beacon_maj_min_data
beacon_measured_rssi_data
beacon_uuid_data
beacon_company_id_data
beacon_adv_interval_data
beacon_led_data
Definition at line 62 of file ble_bcs.h.
              {
     beacon_maj_min_data,
     beacon_measured_rssi_data,
     beacon_uuid_data,
     beacon_company_id_data,
     beacon_adv_interval_data,
     beacon_led_data
 }beacon_data_type_t;
Function Documentation
uint32_t ble_bcs_init (ble_bcs_t * p_bcs, const ble_bcs_init_t * p_bcs_init)
Initialize the Beacon Configuration Service.
Parameters
[out] p_bcs
[in] p_bcs_init
Returns
NRF_SUCCESS on successful initialization of service, otherwise an error code.
Definition at line 438 of file ble_bcs.c.
References BCS_UUID_BASE, BCS_UUID_SERVICE, beacon_adv_interval_char_add(), beacon_calib_char_add(), beacon_company_id_char_add(), beacon_id_char_add(), beacon_led_char_add(), beacon_maj_min_char_add(), ble_bcs_init_t::beacon_write_handler, ble_bcs_s::beacon_write_handler, BLE_CONN_HANDLE_INVALID, BLE_GATTS_SRVC_TYPE_PRIMARY, ble_bcs_s::conn_handle, NRF_SUCCESS, ble_bcs_s::service_handle, ble_uuid_t::type, ble_uuid_t::uuid, and ble_bcs_s::uuid_type.
 {
     uint32_t   err_code;
     ble_uuid_t ble_uuid;
     // Initialize service structure
     p_bcs->conn_handle       = BLE_CONN_HANDLE_INVALID;
     p_bcs->beacon_write_handler = p_bcs_init->beacon_write_handler;
     // Add base UUID to softdevice's internal list.
     ble_uuid128_t base_uuid = BCS_UUID_BASE;
     err_code = sd_ble_uuid_vs_add(&base_uuid, &p_bcs->uuid_type);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     ble_uuid.type = p_bcs->uuid_type;
     ble_uuid.uuid = BCS_UUID_SERVICE;
     err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_bcs->service_handle);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = beacon_maj_min_char_add(p_bcs, p_bcs_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = beacon_calib_char_add(p_bcs, p_bcs_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = beacon_id_char_add(p_bcs, p_bcs_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = beacon_company_id_char_add(p_bcs, p_bcs_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = beacon_adv_interval_char_add(p_bcs, p_bcs_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     err_code = beacon_led_char_add(p_bcs, p_bcs_init);
     if (err_code != NRF_SUCCESS)
     {
         return err_code;
     }
     return NRF_SUCCESS;
 }
void ble_bcs_on_ble_evt (ble_bcs_t * p_bcs, ble_evt_t * p_ble_evt)
Beacon Configuration Service BLE stack event handler.
Handles all events from the BLE stack of interest to the Beacon Configuration Service.
Parameters
[in] p_bcs Beacon Configuration Service structure.
[in] p_ble_evt Event received from the BLE stack.
Definition at line 95 of file ble_bcs.c.
References BLE_GAP_EVT_CONNECTED, BLE_GAP_EVT_DISCONNECTED, BLE_GATTS_EVT_WRITE, ble_evt_hdr_t::evt_id, ble_evt_t::header, on_connect(), on_disconnect(), and on_write().
 {
     switch (p_ble_evt->header.evt_id)
     {
         case BLE_GAP_EVT_CONNECTED:
             on_connect(p_bcs, p_ble_evt);
             break;
         case BLE_GAP_EVT_DISCONNECTED:
             on_disconnect(p_bcs, p_ble_evt);
             break;
         case BLE_GATTS_EVT_WRITE:
             on_write(p_bcs, p_ble_evt);
             break;
         default:
             break;
     }
 }