nRF51822 Beacon Firmware Documentation: Persistent Storage Access Routines
Persistent Storage Access Routines
Persistent Storage Interface
Functions/Interface SDK modules use to persistently store data.
Functions
uint32_t pstorage_init (void)
Module Initialization Routine.
uint32_t pstorage_register (pstorage_module_param_t *p_module_param, pstorage_handle_t *p_block_id)
Register with persistent storage interface.
uint32_t pstorage_block_identifier_get (pstorage_handle_t *p_base_id, pstorage_size_t block_num, pstorage_handle_t *p_block_id)
Function to get block id with reference to base block identifier provided at time of registration.
uint32_t pstorage_store (pstorage_handle_t *p_dest, uint8_t *p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to persistently store data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address; Equivalent to Storage Write.
uint32_t pstorage_update (pstorage_handle_t *p_dest, uint8_t *p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to update persistently stored data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address.
uint32_t pstorage_load (uint8_t *p_dest, pstorage_handle_t *p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to load persistently stored data of length 'size' from 'p_src' address to 'p_dest' address; Equivalent to Storage Read.
uint32_t pstorage_clear (pstorage_handle_t *p_base_id, pstorage_size_t size)
Routine to clear data in persistent memory.
uint32_t pstorage_access_status_get (uint32_t *p_count)
API to get status of number of pending operations with the module.
Detailed Description
Functions/Interface SDK modules use to persistently store data.
Interface for Application & SDK module to load/store information persistently. Note: that while implementation of each of the persistent storage access function depends on the system and can specific to system/solution, the signature of the interface routines should not be altered.
Function Documentation
uint32_t pstorage_init (void)
Module Initialization Routine.
Initializes module. To be called once before any other APIs of the module are used.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
Definition at line 821 of file pstorage_mod.c.
References pstorage_module_table_t::block_count, pstorage_module_table_t::block_size, pstorage_module_table_t::cb, cmd_queue_init(), cmd_queue_t::flash_access, m_module_initialized, m_next_app_instance, m_next_page_addr, m_round_val, m_swap_state, NRF_SUCCESS, pstorage_module_table_t::num_of_pages, STATE_INIT, and STATE_SWAP_DIRTY.
 {
     uint32_t retval;
     cmd_queue_init();
     m_next_app_instance = 0;
     m_next_page_addr    = PSTORAGE_DATA_START_ADDR;
     m_round_val         = 0;
     for (uint32_t index = 0; index < PSTORAGE_MAX_APPLICATIONS; index++)
     {
         m_app_table[index].cb           = NULL;
         m_app_table[index].block_size   = 0;
         m_app_table[index].num_of_pages = 0;
         m_app_table[index].block_count  = 0;
     }
 #ifdef PSTORAGE_RAW_MODE_ENABLE
     m_raw_app_table.cb           = NULL;
     m_raw_app_table.num_of_pages = 0;
     m_module_initialized         = true;
     m_swap_state                 = STATE_INIT;
     retval = NRF_SUCCESS;
 #else
     m_swap_state = STATE_SWAP_DIRTY;
     // Erase swap region in case it is dirty.
     retval = sd_flash_page_erase(PSTORAGE_SWAP_ADDR / PSTORAGE_FLASH_PAGE_SIZE);
     if (retval == NRF_SUCCESS)
     {
         m_cmd_queue.flash_access = true;
         m_module_initialized     = true;
     }
 #endif //PSTORAGE_RAW_MODE_ENABLE
     return retval;
 }
uint32_t pstorage_register (pstorage_module_param_t * p_module_param, pstorage_handle_t * p_block_id)
Register with persistent storage interface.
Parameters
[in] p_module_param Module registration param.
[out] p_block_id Block identifier to identify persistent memory blocks in case registration succeeds. Application is expected to use the block ids for subsequent operations on requested persistent memory. Maximum registrations permitted is determined by configuration parameter PSTORAGE_MAX_APPLICATIONS. In case more than one memory blocks are requested, the identifier provided here is the base identifier for the first block and to identify subsequent block, application shall use @ref pstorage_block_identifier_get with this base identifier and block number. Therefore if 10 blocks of size 64 are requested and application wishes to store memory in 6th block, it shall use @ref pstorage_block_identifier_get with based id and provide a block number of 5. This way application is only expected to remember the base block identifier.
Note
To register an area with a total size (block count * block size) larger than the page size (usually 1024 bytes), the block size must be a divisor of the page size (page size % block size == 0).
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
NRF_ERROR_INVALID_PARAM if invalid parameters are passed to the API.
NRF_ERROR_NO_MEM in case no more registrations can be supported.
Definition at line 862 of file pstorage_mod.c.
References pstorage_module_table_t::base_id, pstorage_module_param_t::block_count, pstorage_module_table_t::block_count, BLOCK_COUNT_CHECK, pstorage_module_param_t::block_size, pstorage_module_table_t::block_size, BLOCK_SIZE_CHECK, pstorage_module_param_t::cb, pstorage_module_table_t::cb, m_next_app_instance, m_next_page_addr, MODULE_SIZE_CHECK, NRF_ERROR_INVALID_PARAM, NRF_ERROR_NO_MEM, NRF_SUCCESS, NULL_PARAM_CHECK, pstorage_module_table_t::num_of_pages, and VERIFY_MODULE_INITIALIZED.
 {
     uint16_t page_count;
     uint32_t total_size;
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_module_param);
     NULL_PARAM_CHECK(p_block_id);
     NULL_PARAM_CHECK(p_module_param->cb);
     BLOCK_SIZE_CHECK(p_module_param->block_size);
     BLOCK_COUNT_CHECK(p_module_param->block_count, p_module_param->block_size);
     // Block size should be a multiple of word size.
     if (!((p_module_param->block_size % sizeof(uint32_t)) == 0))
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     if (m_next_app_instance == PSTORAGE_MAX_APPLICATIONS)
     {
         return NRF_ERROR_NO_MEM;
     }
     p_block_id->module_id = m_next_app_instance;
     p_block_id->block_id  = m_next_page_addr;
     m_app_table[m_next_app_instance].base_id     = p_block_id->block_id;
     m_app_table[m_next_app_instance].cb          = p_module_param->cb;
     m_app_table[m_next_app_instance].block_size  = p_module_param->block_size;
     m_app_table[m_next_app_instance].block_count = p_module_param->block_count;
     // Calculate number of flash pages allocated for the device.
     page_count = 0;
     total_size = p_module_param->block_size * p_module_param->block_count;
     do
     {
         page_count++;
         if (total_size > PSTORAGE_FLASH_PAGE_SIZE)
         {
             total_size -= PSTORAGE_FLASH_PAGE_SIZE;
         }
         else
         {
             total_size = 0;
         }
         m_next_page_addr += PSTORAGE_FLASH_PAGE_SIZE;
     }
     while (total_size >= PSTORAGE_FLASH_PAGE_SIZE);
     m_app_table[m_next_app_instance].num_of_pages = page_count;
     m_next_app_instance++;
     return NRF_SUCCESS;
 }
uint32_t pstorage_block_identifier_get (pstorage_handle_t * p_base_id, pstorage_size_t block_num, pstorage_handle_t * p_block_id)
Function to get block id with reference to base block identifier provided at time of registration.
Function to get block id with reference to base block identifier provided at time of registration. In case more than one memory blocks were requested when registering, the identifier provided here is the base identifier for the first block and to identify subsequent block, application shall use this routine to get block identifier providing input as base identifier and block number. Therefore if 10 blocks of size 64 are requested and application wishes to store memory in 6th block, it shall use @ref pstorage_block_identifier_get with based id and provide a block number of 5. This way application is only expected to remember the base block identifier.
Parameters
[in] p_base_id Base block id received at the time of registration.
[in] block_num Block Number, with first block numbered zero.
[out] p_block_id Block identifier for the block number requested in case the API succeeds.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
NRF_ERROR_INVALID_PARAM if invalid parameters are passed to the API.
Definition at line 919 of file pstorage_mod.c.
References BLOCK_ID_RANGE_CHECK, MODULE_BLOCK_SIZE, MODULE_ID_RANGE_CHECK, NRF_SUCCESS, NULL_PARAM_CHECK, and VERIFY_MODULE_INITIALIZED.
 {
     pstorage_handle_t temp_id;
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_base_id);
     NULL_PARAM_CHECK(p_block_id);
     MODULE_ID_RANGE_CHECK(p_base_id);
     temp_id           = (*p_base_id);
     temp_id.block_id += (block_num * MODULE_BLOCK_SIZE(p_base_id));
     BLOCK_ID_RANGE_CHECK(&temp_id);
     (*p_block_id) = temp_id;
     return NRF_SUCCESS;
 }
uint32_t pstorage_store (pstorage_handle_t * p_dest, uint8_t * p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to persistently store data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address; Equivalent to Storage Write.
Parameters
[in] p_dest Destination address where data is to be stored persistently.
[in] p_src Source address containing data to be stored. API assumes this to be resident memory and no intermediate copy of data is made by the API.
[in] size Size of data to be stored expressed in bytes. Should be word aligned.
[in] offset Offset in bytes to be applied when writing to the block. For example, if within a block of 100 bytes, application wishes to write 20 bytes at offset of 12, then this field should be set to 12. Should be word aligned.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
NRF_ERROR_INVALID_PARAM if invalid parameters are passed to the API.
NRF_ERROR_INVALID_ADDR in case data address 'p_src' is not aligned.
NRF_ERROR_NO_MEM in case request cannot be processed.
Warning
No copy of the data is made, and hence memory provided for data source to be written to flash cannot be freed or reused by the application until this procedure is complete. End of this procedure is notified to the application using the notification callback registered by the application.
Definition at line 941 of file pstorage_mod.c.
References app_notify(), BLOCK_ID_RANGE_CHECK, cmd_queue_enqueue(), MODULE_ID_RANGE_CHECK, NRF_ERROR_INVALID_ADDR, NULL_PARAM_CHECK, OFFSET_CHECK, PSTORAGE_STORE_OP_CODE, SIZE_CHECK, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_src);
     NULL_PARAM_CHECK(p_dest);
     MODULE_ID_RANGE_CHECK(p_dest);
     BLOCK_ID_RANGE_CHECK(p_dest);
     SIZE_CHECK(p_dest, size);
     OFFSET_CHECK(p_dest, offset,size);
     // Verify word alignment.
     if ((!is_word_aligned(p_src)) || (!is_word_aligned((void *)(uint32_t)offset)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     if ((!is_word_aligned((uint32_t *)p_dest->block_id)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     return cmd_queue_enqueue(PSTORAGE_STORE_OP_CODE, p_dest, p_src, size, offset);
 }
uint32_t pstorage_update (pstorage_handle_t * p_dest, uint8_t * p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to update persistently stored data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address.
Parameters
[in] p_dest Destination address where data is to be updated.
[in] p_src Source address containing data to be stored. API assumes this to be resident memory and no intermediate copy of data is made by the API.
[in] size Size of data to be stored expressed in bytes. Should be word aligned.
[in] offset Offset in bytes to be applied when writing to the block. For example, if within a block of 100 bytes, application wishes to write 20 bytes at offset of 12, then this field should be set to 12. Should be word aligned.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
NRF_ERROR_INVALID_PARAM if invalid parameters are passed to the API.
NRF_ERROR_INVALID_ADDR in case data address 'p_src' is not aligned.
NRF_ERROR_NO_MEM in case request cannot be processed.
Warning
No copy of the data is made, and hence memory provided for data source to be written to flash cannot be freed or reused by the application until this procedure is complete. End of this procedure is notified to the application using the notification callback registered by the application.
Routine to update persistently stored data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address.
| Page1 | |_______________________________________________| | head | body (to be updated) | tail | |______|_________________________________|______|
| Page1 | Page2 | |_______________________________________________|______________________________________| | head | body (to be updated) | tail | |________________|________________________________________|____________________________|
ToDo: pointers not uint32_t for addresses
Definition at line 969 of file pstorage_mod.c.
References app_notify(), BLOCK_ID_RANGE_CHECK, cmd_queue_enqueue(), MODULE_ID_RANGE_CHECK, NRF_ERROR_INVALID_ADDR, NRF_SUCCESS, NULL_PARAM_CHECK, OFFSET_CHECK, PAGE_BASE_ADDR, PSTORAGE_UPDATE_OP_CODE, SIZE_CHECK, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_src);
     NULL_PARAM_CHECK(p_dest);
     MODULE_ID_RANGE_CHECK(p_dest);
     BLOCK_ID_RANGE_CHECK(p_dest);
     SIZE_CHECK(p_dest, size);
     OFFSET_CHECK(p_dest, offset, size);
     // Verify word alignment.
     if ((!is_word_aligned(p_src)) || (!is_word_aligned((void *)(uint32_t)offset)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     if ((!is_word_aligned((uint32_t *)p_dest->block_id)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     return cmd_queue_enqueue(PSTORAGE_UPDATE_OP_CODE, p_dest, p_src, size, offset);
 }
uint32_t pstorage_load (uint8_t * p_dest, pstorage_handle_t * p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to load persistently stored data of length 'size' from 'p_src' address to 'p_dest' address; Equivalent to Storage Read.
Parameters
[in] p_dest Destination address where persistently stored data is to be loaded.
[in] p_src Source from where data is to be loaded from persistent memory.
[in] size Size of data to be loaded from persistent memory expressed in bytes. Should be word aligned.
[in] offset Offset in bytes to be applied when loading from the block. For example, if within a block of 100 bytes, application wishes to load 20 bytes from offset of 12, then this field should be set to 12. Should be word aligned.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
NRF_ERROR_INVALID_PARAM if invalid parameters are passed to the API.
NRF_ERROR_INVALID_ADDR in case data address 'p_dst' is not aligned.
NRF_ERROR_NO_MEM in case request cannot be processed.
Definition at line 997 of file pstorage_mod.c.
References app_notify(), BLOCK_ID_RANGE_CHECK, pstorage_module_table_t::cb, MODULE_ID_RANGE_CHECK, NRF_ERROR_INVALID_ADDR, NRF_SUCCESS, NULL_PARAM_CHECK, OFFSET_CHECK, PSTORAGE_LOAD_OP_CODE, SIZE_CHECK, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_src);
     NULL_PARAM_CHECK(p_dest);
     MODULE_ID_RANGE_CHECK(p_src);
     BLOCK_ID_RANGE_CHECK(p_src);
     SIZE_CHECK(p_src, size);
     OFFSET_CHECK(p_src, offset, size);
     // Verify word alignment.
     if ((!is_word_aligned(p_dest)) || (!is_word_aligned((void *)(uint32_t)offset)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     if ((!is_word_aligned((uint32_t *)p_src->block_id)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     memcpy(p_dest, (((uint8_t *)p_src->block_id) + offset), size);
     m_app_table[p_src->module_id].cb(p_src, PSTORAGE_LOAD_OP_CODE, NRF_SUCCESS, p_dest, size);
     return NRF_SUCCESS;
 }
uint32_t pstorage_clear (pstorage_handle_t * p_base_id, pstorage_size_t size)
Routine to clear data in persistent memory.
Parameters
[in] p_base_id Base block identifier in persistent memory that needs to cleared; Equivalent to an Erase Operation.
[in] size Size of data to be cleared from persistent memory expressed in bytes. This parameter is to provision for clearing of certain blocks of memory, or all memory blocks in a registered module. If the total size of the application module is used (blocks * block size) in combination with the identifier for the first block in the module, all blocks in the module will be erased.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
NRF_ERROR_INVALID_PARAM if invalid parameters are passed to the API.
NRF_ERROR_INVALID_ADDR in case data address 'p_dst' is not aligned.
NRF_ERROR_NO_MEM in case request cannot be processed.
Note
Clear operations may take time. This API however, does not block until the clear procedure is complete. Application is notified of procedure completion using notification callback registered by the application. 'result' parameter of the callback suggests if the procedure was successful or not.
Definition at line 1029 of file pstorage_mod.c.
References app_notify(), pstorage_module_table_t::base_id, BLOCK_ID_RANGE_CHECK, pstorage_module_table_t::block_size, cmd_queue_enqueue(), MODULE_ID_RANGE_CHECK, NRF_ERROR_INVALID_ADDR, NRF_ERROR_INVALID_PARAM, NRF_SUCCESS, NULL_PARAM_CHECK, PSTORAGE_CLEAR_OP_CODE, and VERIFY_MODULE_INITIALIZED.
 {
     uint32_t retval;
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_dest);
     MODULE_ID_RANGE_CHECK(p_dest);
     BLOCK_ID_RANGE_CHECK(p_dest);
     if ((!is_word_aligned((uint32_t *)p_dest->block_id)))
     {
         return NRF_ERROR_INVALID_ADDR;
     }
     if (
         !(
             ((p_dest->block_id - m_app_table[p_dest->module_id].base_id) %
              m_app_table[p_dest->module_id].block_size) == 0
             )
         )
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     retval = cmd_queue_enqueue(PSTORAGE_CLEAR_OP_CODE, p_dest, NULL, size, 0);
     return retval;
 }
uint32_t pstorage_access_status_get (uint32_t * p_count)
API to get status of number of pending operations with the module.
Parameters
[out] p_count Number of storage operations pending with the module, if 0, there are no outstanding requests.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
NRF_ERROR_INVALID_STATE is returned is API is called without module initialization.
NRF_ERROR_NULL if NULL parameter has been passed.
Definition at line 1059 of file pstorage_mod.c.
References cmd_queue_t::count, NRF_SUCCESS, NULL_PARAM_CHECK, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     NULL_PARAM_CHECK(p_count);
     (*p_count) = m_cmd_queue.count;
     return NRF_SUCCESS;
 }