nRF51822 Beacon Firmware Documentation: Connection Parameters Negotiation
Connection Parameters Negotiation
Module for initiating and executing a connection parameters negotiation procedure.
Data Structures
struct ble_conn_params_evt_t
Connection Parameters Module event.
struct ble_conn_params_init_t
Connection Parameters Module init structure. This contains all options and data needed for initialization of the connection parameters negotiation module.
Typedefs
typedef void(* ble_conn_params_evt_handler_t)(ble_conn_params_evt_t *p_evt)
Connection Parameters Module event handler type.
Enumerations
enum ble_conn_params_evt_type_t { BLE_CONN_PARAMS_EVT_FAILED, BLE_CONN_PARAMS_EVT_SUCCEEDED }
Connection Parameters Module event type.
Functions
uint32_t ble_conn_params_init (const ble_conn_params_init_t *p_init)
Function for initializing the Connection Parameters module.
uint32_t ble_conn_params_stop (void)
Function for stopping the Connection Parameters module.
uint32_t ble_conn_params_change_conn_params (ble_gap_conn_params_t *new_params)
Function for changing the current connection parameters to a new set.
void ble_conn_params_on_ble_evt (ble_evt_t *p_ble_evt)
Function for handling the Application's BLE Stack events.
Detailed Description
Module for initiating and executing a connection parameters negotiation procedure.
Typedef Documentation
typedef void(* ble_conn_params_evt_handler_t)(ble_conn_params_evt_t *p_evt)
Connection Parameters Module event handler type.
Definition at line 42 of file ble_conn_params.h.
Enumeration Type Documentation
enum ble_conn_params_evt_type_t
Connection Parameters Module event type.
Enumerator
BLE_CONN_PARAMS_EVT_FAILED
Negotiation procedure failed.
BLE_CONN_PARAMS_EVT_SUCCEEDED
Negotiation procedure succeeded.
Definition at line 29 of file ble_conn_params.h.
 {
     BLE_CONN_PARAMS_EVT_FAILED   ,
     BLE_CONN_PARAMS_EVT_SUCCEEDED
 } ble_conn_params_evt_type_t;
Function Documentation
uint32_t ble_conn_params_init (const ble_conn_params_init_t * p_init)
Function for initializing the Connection Parameters module.
Note
If the negotiation procedure should be triggered when notification/indication of any characteristic is enabled by the peer, then this function must be called after having initialized the services.
Parameters
[in] p_init This contains information needed to initialize this module.
Returns
NRF_SUCCESS on successful initialization, otherwise an error code.
Definition at line 99 of file ble_conn_params.c.
References app_timer_create(), APP_TIMER_MODE_SINGLE_SHOT, BLE_CONN_HANDLE_INVALID, m_change_param, m_conn_handle, m_conn_params_timer_id, m_update_count, NRF_SUCCESS, ble_conn_params_init_t::p_conn_params, and update_timeout_handler().
 {
     uint32_t err_code;
     m_conn_params_config = *p_init;
     m_change_param = false;
     if (p_init->p_conn_params != NULL)
     {
         m_preferred_conn_params = *p_init->p_conn_params;
         // Set the connection params in stack
         err_code = sd_ble_gap_ppcp_set(&m_preferred_conn_params);
         if (err_code != NRF_SUCCESS)
         {
             return err_code;
         }
     }
     else
     {
         // Fetch the connection params from stack
         err_code = sd_ble_gap_ppcp_get(&m_preferred_conn_params);
         if (err_code != NRF_SUCCESS)
         {
             return err_code;
         }
     }
     m_conn_handle  = BLE_CONN_HANDLE_INVALID;
     m_update_count = 0;
     return app_timer_create(&m_conn_params_timer_id,
                             APP_TIMER_MODE_SINGLE_SHOT,
                             update_timeout_handler);
 }
uint32_t ble_conn_params_stop (void)
Function for stopping the Connection Parameters module.
This function is intended to be used by the application to clean up the connection parameters update module. This will stop the connection parameters update timer if running, thereby preventing any impending connection parameters update procedure. This function must be called by the application when it needs to clean itself up (for example, before disabling the bluetooth SoftDevice) so that an unwanted timer expiry event can be avoided.
Returns
NRF_SUCCESS on successful initialization, otherwise an error code.
Definition at line 135 of file ble_conn_params.c.
References app_timer_stop(), and m_conn_params_timer_id.
 {
     return app_timer_stop(m_conn_params_timer_id);
 }
uint32_t ble_conn_params_change_conn_params (ble_gap_conn_params_t * new_params)
Function for changing the current connection parameters to a new set.
Use this function to change the connection parameters to a new set of parameter (ie different from the ones given at init of the module). This function is usefull for scenario where most of the time the application needs a relatively big connection interval, and just sometimes, for a temporary period requires shorter connection interval, for example to transfer a higher amount of data. If the given parameters does not match the current connection's parameters this function initiates a new negotiation.
Parameters
[in] new_params This contains the new connections parameters to setup.
Returns
NRF_SUCCESS on successful initialization, otherwise an error code.
Definition at line 294 of file ble_conn_params.c.
References BLE_CONN_PARAMS_EVT_SUCCEEDED, ble_conn_params_init_t::evt_handler, ble_conn_params_evt_t::evt_type, is_conn_params_ok(), m_change_param, m_conn_handle, m_update_count, and NRF_SUCCESS.
 {
     uint32_t err_code;
     m_preferred_conn_params = *new_params;
     // Set the connection params in stack
     err_code = sd_ble_gap_ppcp_set(&m_preferred_conn_params);
     if (err_code == NRF_SUCCESS)
     {
         if (!is_conn_params_ok(&m_current_conn_params))
         {
             m_change_param = true;
             err_code = sd_ble_gap_conn_param_update(m_conn_handle, &m_preferred_conn_params);
             m_update_count = 1;
         }
         else
         {
             // Notify the application that the procedure has succeded
             if (m_conn_params_config.evt_handler != NULL)
             {
                 ble_conn_params_evt_t evt;
                 evt.evt_type = BLE_CONN_PARAMS_EVT_SUCCEEDED;
                 m_conn_params_config.evt_handler(&evt);
             }
             err_code = NRF_SUCCESS;
         }
     }
     return err_code;
 }
void ble_conn_params_on_ble_evt (ble_evt_t * p_ble_evt)
Function for handling the Application's BLE Stack events.
Handles all events from the BLE stack that are of interest to this module.
Parameters
[in] p_ble_evt The event received from the BLE stack.
Definition at line 267 of file ble_conn_params.c.
References BLE_GAP_EVT_CONN_PARAM_UPDATE, BLE_GAP_EVT_CONNECTED, BLE_GAP_EVT_DISCONNECTED, BLE_GATTS_EVT_WRITE, ble_evt_hdr_t::evt_id, ble_evt_t::header, on_conn_params_update(), on_connect(), on_disconnect(), and on_write().
 {
     switch (p_ble_evt->header.evt_id)
     {
         case BLE_GAP_EVT_CONNECTED:
             on_connect(p_ble_evt);
             break;
         case BLE_GAP_EVT_DISCONNECTED:
             on_disconnect(p_ble_evt);
             break;
         case BLE_GATTS_EVT_WRITE:
             on_write(p_ble_evt);
             break;
         case BLE_GAP_EVT_CONN_PARAM_UPDATE:
             on_conn_params_update(p_ble_evt);
             break;
         default:
             // No implementation needed.
             break;
     }
 }