nRF51822 Beacon Firmware Documentation: Device Firmware Update API.
Device Firmware Update API.
Device Firmware Update module interface.
Modules
Types and definitions.
Device Firmware Update module type and definitions.
Template file with an DFU init packet handling example.
This file contains a template on how to implement DFU init packet handling.
Typedefs
typedef void(* dfu_callback_t)(uint32_t packet, uint32_t result, uint8_t *p_data)
DFU event callback for asynchronous calls.
Functions
uint32_t dfu_init (void)
Function for initializing the Device Firmware Update module.
void dfu_register_callback (dfu_callback_t callback_handler)
Function for registering a callback listener for dfu_data_pkt_handle callbacks.
uint32_t dfu_start_pkt_handle (dfu_update_packet_t *p_packet)
Function for setting the DFU image size.
uint32_t dfu_data_pkt_handle (dfu_update_packet_t *p_packet)
Function for handling DFU data packets.
uint32_t dfu_init_pkt_handle (dfu_update_packet_t *p_packet)
Function for handling DFU init packets.
uint32_t dfu_image_validate (void)
Function for validating a transferred image after the transfer has completed.
uint32_t dfu_image_activate (void)
Function for activating the transfered image after validation has successfully completed.
void dfu_reset (void)
Function for reseting the current update procedure and return to initial state.
uint32_t dfu_bl_image_validate (void)
Function for validating that new bootloader has been correctly installed.
uint32_t dfu_sd_image_validate (void)
Function for validating that new SoftDevicehas been correctly installed.
uint32_t dfu_bl_image_swap (void)
Function for swapping existing bootloader with newly received.
uint32_t dfu_sd_image_swap (void)
Function for swapping existing SoftDevice with newly received.
uint32_t dfu_init_pkt_complete (void)
Function for handling DFU init packet complete.
Detailed Description
Device Firmware Update module interface.
Typedef Documentation
typedef void(* dfu_callback_t)(uint32_t packet, uint32_t result, uint8_t *p_data)
DFU event callback for asynchronous calls.
Parameters
[in] packet Packet type for which this callback is related. START_PACKET, DATA_PACKET.
[in] result Operation result code. NRF_SUCCESS when a queued operation was successful.
[in] p_data Pointer to the data to which the operation is related.
Definition at line 35 of file dfu.h.
Function Documentation
uint32_t dfu_init (void)
Function for initializing the Device Firmware Update module.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 303 of file dfu_dual_bank_mod.c.
References app_timer_create(), APP_TIMER_MODE_SINGLE_SHOT, app_timer_start(), pstorage_module_param_t::cb, DFU_BANK_0_REGION_START, DFU_BANK_1_REGION_START, DFU_STATE_IDLE, DFU_STATE_INIT_ERROR, dfu_timeout_handler(), DFU_TIMEOUT_INTERVAL, m_data_received, m_dfu_state, m_dfu_timer_id, m_image_crc, m_init_packet_length, m_storage_handle_app, m_storage_handle_swap, NRF_SUCCESS, and pstorage_callback_handler().
 {
     uint32_t                err_code;
     pstorage_module_param_t storage_module_param = {.cb = pstorage_callback_handler};
     m_init_packet_length = 0;
     m_image_crc          = 0;
     err_code = pstorage_raw_register(&storage_module_param, &m_storage_handle_app);
     if (err_code != NRF_SUCCESS)
     {
         m_dfu_state = DFU_STATE_INIT_ERROR;
         return err_code;
     }
     m_storage_handle_app.block_id  = DFU_BANK_0_REGION_START;
     m_storage_handle_swap          = m_storage_handle_app;
     m_storage_handle_swap.block_id = DFU_BANK_1_REGION_START;
     // Create the timer to monitor the activity by the peer doing the firmware update.
     err_code = app_timer_create(&m_dfu_timer_id,
                                 APP_TIMER_MODE_SINGLE_SHOT,
                                 dfu_timeout_handler);
     APP_ERROR_CHECK(err_code);
     // Start the DFU timer.
     err_code = app_timer_start(m_dfu_timer_id, DFU_TIMEOUT_INTERVAL, NULL);
     APP_ERROR_CHECK(err_code);
     m_data_received = 0;
     m_dfu_state     = DFU_STATE_IDLE;
     return NRF_SUCCESS;
 }
void dfu_register_callback (dfu_callback_t callback_handler)
Function for registering a callback listener for dfu_data_pkt_handle callbacks.
Parameters
[in] callback_handler Callback handler for receiving DFU events on completed operations of DFU packets.
Definition at line 339 of file dfu_dual_bank_mod.c.
References m_data_pkt_cb.
 {
     m_data_pkt_cb = callback_handler;
 }
uint32_t dfu_start_pkt_handle (dfu_update_packet_t * p_packet)
Function for setting the DFU image size.
Function sets the DFU image size. This function must be called when an update is started in order to notify the DFU of the new image size. If multiple images are to be transferred within the same update context then this function must be called with size information for each image being transfered. If an image type is not being transfered, e.g. SoftDevice but no Application , then the image size for application must be zero.
Parameters
[in] p_packet Pointer to the DFU packet containing information on DFU update process to be started.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 345 of file dfu_dual_bank_mod.c.
References dfu_bank_func_t::activate, dfu_start_packet_t::app_image_size, dfu_start_packet_t::bl_image_size, dfu_bank_func_t::cleared, CODE_PAGE_SIZE, dfu_activate_app(), dfu_activate_bl(), dfu_activate_sd(), DFU_BL_IMAGE_MAX_SIZE, dfu_cleared_func_app(), dfu_cleared_func_swap(), DFU_IMAGE_MAX_SIZE_BANKED, DFU_IMAGE_MAX_SIZE_FULL, dfu_prepare_func_app_erase(), dfu_prepare_func_swap_erase(), DFU_STATE_IDLE, dfu_timer_restart(), IS_UPDATING_APP, IS_UPDATING_BL, IS_UPDATING_SD, IS_WORD_SIZED, m_dfu_state, m_image_size, NRF_ERROR_DATA_SIZE, NRF_ERROR_INVALID_STATE, NRF_ERROR_NOT_SUPPORTED, NRF_SUCCESS, dfu_update_packet_t::params, dfu_bank_func_t::prepare, dfu_start_packet_t::sd_image_size, and dfu_update_packet_t::start_packet.
 {
     uint32_t err_code;
     m_start_packet = *(p_packet->params.start_packet);
     // Check that the requested update procedure is supported.
     // Currently the following combinations are allowed:
     // - Application
     // - SoftDevice
     // - Bootloader
     // - SoftDevice with Bootloader
     if (IS_UPDATING_APP(m_start_packet) &&
         (IS_UPDATING_SD(m_start_packet) || IS_UPDATING_BL(m_start_packet)))
     {
         // App update is only supported independently.
         return NRF_ERROR_NOT_SUPPORTED;
     }
     if (!(IS_WORD_SIZED(m_start_packet.sd_image_size) &&
           IS_WORD_SIZED(m_start_packet.bl_image_size) &&
           IS_WORD_SIZED(m_start_packet.app_image_size)))
     {
         // Image_sizes are not a multiple of 4 (word size).
         return NRF_ERROR_NOT_SUPPORTED;
     }
     m_image_size = m_start_packet.sd_image_size + m_start_packet.bl_image_size +
                    m_start_packet.app_image_size;
     if (m_start_packet.bl_image_size > DFU_BL_IMAGE_MAX_SIZE)
     {
         return NRF_ERROR_DATA_SIZE;
     }
     if (IS_UPDATING_SD(m_start_packet))
     {
         if (m_image_size > (DFU_IMAGE_MAX_SIZE_FULL))
         {
             return NRF_ERROR_DATA_SIZE;
         }
         m_functions.prepare  = dfu_prepare_func_app_erase;
         m_functions.cleared  = dfu_cleared_func_app;
         m_functions.activate = dfu_activate_sd;
     }
     else
     {
         if (m_image_size > DFU_IMAGE_MAX_SIZE_BANKED)
         {
             return NRF_ERROR_DATA_SIZE;
         }
         m_functions.prepare = dfu_prepare_func_swap_erase;
         m_functions.cleared = dfu_cleared_func_swap;
         if (IS_UPDATING_BL(m_start_packet))
         {
             m_functions.activate = dfu_activate_bl;
         }
         else
         {
             m_functions.activate = dfu_activate_app;
         }
     }
     switch (m_dfu_state)
     {
         case DFU_STATE_IDLE:
             // Valid peer activity detected. Hence restart the DFU timer.
             err_code = dfu_timer_restart();
             if (err_code != NRF_SUCCESS)
             {
                 return err_code;
             }
             m_functions.prepare(m_image_size);
             break;
         default:
             err_code = NRF_ERROR_INVALID_STATE;
             break;
     }
     return err_code;
 }
uint32_t dfu_data_pkt_handle (dfu_update_packet_t * p_packet)
Function for handling DFU data packets.
Parameters
[in] p_packet Pointer to the DFU packet.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 431 of file dfu_dual_bank_mod.c.
References dfu_update_packet_t::data_packet, DFU_STATE_RDY, DFU_STATE_RX_DATA_PKT, DFU_STATE_RX_INIT_PKT, dfu_timer_restart(), m_data_received, m_dfu_state, m_image_size, mp_storage_handle_active, NRF_ERROR_DATA_SIZE, NRF_ERROR_INVALID_ADDR, NRF_ERROR_INVALID_LENGTH, NRF_ERROR_INVALID_STATE, NRF_ERROR_NULL, NRF_SUCCESS, dfu_data_packet_t::p_data_packet, dfu_data_packet_t::packet_length, and dfu_update_packet_t::params.
 {
     uint32_t   data_length;
     uint32_t   err_code;
     uint32_t * p_data;
     if (p_packet == NULL)
     {
         return NRF_ERROR_NULL;
     }
     // Check pointer alignment.
     if (!is_word_aligned(p_packet->params.data_packet.p_data_packet))
     {
         // The p_data_packet is not word aligned address.
         return NRF_ERROR_INVALID_ADDR;
     }
     switch (m_dfu_state)
     {
         case DFU_STATE_RDY:
         case DFU_STATE_RX_INIT_PKT:
             return NRF_ERROR_INVALID_STATE;
         case DFU_STATE_RX_DATA_PKT:
             data_length = p_packet->params.data_packet.packet_length * sizeof(uint32_t);
             if ((m_data_received + data_length) > m_image_size)
             {
                 // The caller is trying to write more bytes into the flash than the size provided to
                 // the dfu_image_size_set function. This is treated as a serious error condition and
                 // an unrecoverable one. Hence point the variable mp_app_write_address to the top of
                 // the flash area. This will ensure that all future application data packet writes
                 // will be blocked because of the above check.
                 m_data_received = 0xFFFFFFFF;
                 return NRF_ERROR_DATA_SIZE;
             }
             // Valid peer activity detected. Hence restart the DFU timer.
             err_code = dfu_timer_restart();
             if (err_code != NRF_SUCCESS)
             {
                 return err_code;
             }
             p_data = (uint32_t *)p_packet->params.data_packet.p_data_packet;
             err_code = pstorage_raw_store(mp_storage_handle_active,
                                           (uint8_t *)p_data,
                                           data_length,
                                           m_data_received);
             if (err_code != NRF_SUCCESS)
             {
                 return err_code;
             }
             m_data_received += data_length;
             if (m_data_received != m_image_size)
             {
                 // The entire image is not received yet. More data is expected.
                 err_code = NRF_ERROR_INVALID_LENGTH;
             }
             else
             {
                 // The entire image has been received. Return NRF_SUCCESS.
                 err_code = NRF_SUCCESS;
             }
             break;
         default:
             err_code = NRF_ERROR_INVALID_STATE;
             break;
     }
     return err_code;
 }
uint32_t dfu_init_pkt_handle (dfu_update_packet_t * p_packet)
Function for handling DFU init packets.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 538 of file dfu_dual_bank_mod.c.
References dfu_update_packet_t::data_packet, DFU_STATE_RDY, DFU_STATE_RX_INIT_PKT, dfu_timer_restart(), IMAGE_WRITE_IN_PROGRESS, m_dfu_state, m_init_packet, m_init_packet_length, NRF_ERROR_INVALID_LENGTH, NRF_ERROR_INVALID_STATE, NRF_SUCCESS, dfu_data_packet_t::p_data_packet, dfu_data_packet_t::packet_length, and dfu_update_packet_t::params.
 {
     uint32_t err_code = NRF_SUCCESS;
     uint32_t length;
     switch (m_dfu_state)
     {
         case DFU_STATE_RDY:
             m_dfu_state = DFU_STATE_RX_INIT_PKT;
             // When receiving init packet in state ready just update and fall through this case.
         case DFU_STATE_RX_INIT_PKT:
             // DFU initialization has been done and a start packet has been received.
             if (IMAGE_WRITE_IN_PROGRESS())
             {
                 // Image write is already in progress. Cannot handle an init packet now.
                 return NRF_ERROR_INVALID_STATE;
             }
             // Valid peer activity detected. Hence restart the DFU timer.
             err_code = dfu_timer_restart();
             if (err_code != NRF_SUCCESS)
             {
                 return err_code;
             }
             length = p_packet->params.data_packet.packet_length * sizeof(uint32_t);
             if ((m_init_packet_length + length) > sizeof(m_init_packet))
             {
                 return NRF_ERROR_INVALID_LENGTH;
             }
             memcpy(&m_init_packet[m_init_packet_length],
                    &p_packet->params.data_packet.p_data_packet[0],
                    length);
             m_init_packet_length += length;
             break;
         default:
             // Either the start packet was not received or dfu_init function was not called before.
             err_code = NRF_ERROR_INVALID_STATE;
             break;
     }
     return err_code;
 }
uint32_t dfu_image_validate (void)
Function for validating a transferred image after the transfer has completed.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 586 of file dfu_dual_bank_mod.c.
References dfu_init_postvalidate(), DFU_STATE_RX_DATA_PKT, DFU_STATE_VALIDATE, DFU_STATE_WAIT_4_ACTIVATE, dfu_timer_restart(), m_data_received, m_dfu_state, m_image_size, mp_storage_handle_active, NRF_ERROR_INVALID_STATE, and NRF_SUCCESS.
 {
     uint32_t err_code;
     switch (m_dfu_state)
     {
         case DFU_STATE_RX_DATA_PKT:
             m_dfu_state = DFU_STATE_VALIDATE;
             // Check if the application image write has finished.
             if (m_data_received != m_image_size)
             {
                 // Image not yet fully transfered by the peer or the peer has attempted to write
                 // too much data. Hence the validation should fail.
                 err_code = NRF_ERROR_INVALID_STATE;
             }
             else
             {
                 // Valid peer activity detected. Hence restart the DFU timer.
                 err_code = dfu_timer_restart();
                 if (err_code == NRF_SUCCESS)
                 {
                     err_code = dfu_init_postvalidate((uint8_t *)mp_storage_handle_active->block_id,
                                                      m_image_size);
                     if (err_code != NRF_SUCCESS)
                     {
                         return err_code;
                     }
                     m_dfu_state = DFU_STATE_WAIT_4_ACTIVATE;
                 }
             }
             break;
         default:
             err_code = NRF_ERROR_INVALID_STATE;
             break;
     }
     return err_code;
 }
uint32_t dfu_image_activate (void)
Function for activating the transfered image after validation has successfully completed.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 629 of file dfu_dual_bank_mod.c.
References dfu_bank_func_t::activate, app_timer_stop(), DFU_STATE_WAIT_4_ACTIVATE, m_dfu_state, m_dfu_timer_id, and NRF_ERROR_INVALID_STATE.
 {
     uint32_t err_code;
     switch (m_dfu_state)
     {
         case DFU_STATE_WAIT_4_ACTIVATE:
             // Stop the DFU Timer because the peer activity need not be monitored any longer.
             err_code = app_timer_stop(m_dfu_timer_id);
             APP_ERROR_CHECK(err_code);
             err_code = m_functions.activate();
             break;
         default:
             err_code = NRF_ERROR_INVALID_STATE;
             break;
     }
     return err_code;
 }
void dfu_reset (void)
Function for reseting the current update procedure and return to initial state.
This function call will result in a system reset to ensure correct system behavior. The reset will might be scheduled to execute at a later point in time to ensure pending flash operations has completed.
Definition at line 653 of file dfu_dual_bank_mod.c.
References bootloader_dfu_update_process(), DFU_RESET, and dfu_update_status_t::status_code.
 {
     dfu_update_status_t update_status;
     update_status.status_code = DFU_RESET;
     bootloader_dfu_update_process(update_status);
 }
uint32_t dfu_bl_image_validate (void)
Function for validating that new bootloader has been correctly installed.
Returns
NRF_SUCCESS if install was successful. NRF_ERROR_NULL if the images differs.
Definition at line 807 of file dfu_dual_bank_mod.c.
References bootloader_settings_t::bl_image_size, BOOTLOADER_REGION_START, bootloader_settings_get(), sd_mbr_command_t::command, sd_mbr_command_t::compare, DFU_BANK_0_REGION_START, DFU_BANK_1_REGION_START, sd_mbr_command_compare_t::len, NRF_SUCCESS, sd_mbr_command_t::params, sd_mbr_command_compare_t::ptr1, sd_mbr_command_compare_t::ptr2, bootloader_settings_t::sd_image_size, bootloader_settings_t::sd_image_start, and SD_MBR_COMMAND_COMPARE.
 {
     bootloader_settings_t bootloader_settings;
     sd_mbr_command_t      sd_mbr_cmd;
     bootloader_settings_get(&bootloader_settings);
     if (bootloader_settings.bl_image_size != 0)
     {
         uint32_t bl_image_start = (bootloader_settings.sd_image_size == 0) ?
                                   DFU_BANK_1_REGION_START :
                                   bootloader_settings.sd_image_start +
                                   bootloader_settings.sd_image_size;
         sd_mbr_cmd.command             = SD_MBR_COMMAND_COMPARE;
         sd_mbr_cmd.params.compare.ptr1 = (uint32_t *)BOOTLOADER_REGION_START;
         sd_mbr_cmd.params.compare.ptr2 = (uint32_t *)(bl_image_start);
         sd_mbr_cmd.params.compare.len  = bootloader_settings.bl_image_size / sizeof(uint32_t);
         return sd_mbr_command(&sd_mbr_cmd);
     }
     return NRF_SUCCESS;
 }
uint32_t dfu_sd_image_validate (void)
Function for validating that new SoftDevicehas been correctly installed.
Returns
NRF_SUCCESS if install was successful. NRF_ERROR_NULL if the images differs.
Definition at line 832 of file dfu_dual_bank_mod.c.
References bootloader_settings_get(), sd_mbr_command_t::command, sd_mbr_command_t::compare, dfu_sd_img_block_swap(), sd_mbr_command_compare_t::len, NRF_ERROR_NULL, NRF_SUCCESS, sd_mbr_command_t::params, sd_mbr_command_compare_t::ptr1, sd_mbr_command_compare_t::ptr2, bootloader_settings_t::sd_image_size, bootloader_settings_t::sd_image_start, SD_MBR_COMMAND_COMPARE, SOFTDEVICE_INFORMATION, and SOFTDEVICE_REGION_START.
 {
     bootloader_settings_t bootloader_settings;
     sd_mbr_command_t      sd_mbr_cmd;
     bootloader_settings_get(&bootloader_settings);
     if (bootloader_settings.sd_image_size == 0)
     {
         return NRF_SUCCESS;
     }
     if ((SOFTDEVICE_REGION_START + bootloader_settings.sd_image_size) > bootloader_settings.sd_image_start)
     {
         uint32_t sd_start        = SOFTDEVICE_REGION_START;
         uint32_t block_size      = (bootloader_settings.sd_image_start - sd_start) / 2;
         uint32_t image_end       = bootloader_settings.sd_image_start +
                                    bootloader_settings.sd_image_size;
         uint32_t img_block_start = bootloader_settings.sd_image_start + 2 * block_size;
         uint32_t sd_block_start  = sd_start + 2 * block_size;
         if (SOFTDEVICE_INFORMATION->softdevice_size < bootloader_settings.sd_image_size)
         {
             return NRF_ERROR_NULL;
         }
         return dfu_sd_img_block_swap((uint32_t *)img_block_start,
                                      (uint32_t *)sd_block_start,
                                      image_end - img_block_start,
                                      block_size);
     }
     sd_mbr_cmd.command             = SD_MBR_COMMAND_COMPARE;
     sd_mbr_cmd.params.compare.ptr1 = (uint32_t *)SOFTDEVICE_REGION_START;
     sd_mbr_cmd.params.compare.ptr2 = (uint32_t *)bootloader_settings.sd_image_start;
     sd_mbr_cmd.params.compare.len  = bootloader_settings.sd_image_size / sizeof(uint32_t);
     return sd_mbr_command(&sd_mbr_cmd);
 }
uint32_t dfu_bl_image_swap (void)
Function for swapping existing bootloader with newly received.
Returns
NRF_SUCCESS on succesfull swapping. For error code please refer to sd_mbr_command_copy_bl_t.
Definition at line 783 of file dfu_dual_bank_mod.c.
References bootloader_settings_t::bl_image_size, sd_mbr_command_copy_bl_t::bl_len, sd_mbr_command_copy_bl_t::bl_src, bootloader_settings_get(), sd_mbr_command_t::command, sd_mbr_command_t::copy_bl, DFU_BANK_0_REGION_START, DFU_BANK_1_REGION_START, NRF_SUCCESS, sd_mbr_command_t::params, bootloader_settings_t::sd_image_size, bootloader_settings_t::sd_image_start, and SD_MBR_COMMAND_COPY_BL.
 {
     bootloader_settings_t bootloader_settings;
     sd_mbr_command_t      sd_mbr_cmd;
     bootloader_settings_get(&bootloader_settings);
     if (bootloader_settings.bl_image_size != 0)
     {
         uint32_t bl_image_start = (bootloader_settings.sd_image_size == 0) ?
                                   DFU_BANK_1_REGION_START :
                                   bootloader_settings.sd_image_start +
                                   bootloader_settings.sd_image_size;
         sd_mbr_cmd.command               = SD_MBR_COMMAND_COPY_BL;
         sd_mbr_cmd.params.copy_bl.bl_src = (uint32_t *)(bl_image_start);
         sd_mbr_cmd.params.copy_bl.bl_len = bootloader_settings.bl_image_size / sizeof(uint32_t);
         return sd_mbr_command(&sd_mbr_cmd);
     }
     return NRF_SUCCESS;
 }
uint32_t dfu_sd_image_swap (void)
Function for swapping existing SoftDevice with newly received.
Returns
NRF_SUCCESS on succesfull swapping. For error code please refer to sd_mbr_command_copy_sd_t.
Definition at line 725 of file dfu_dual_bank_mod.c.
References bootloader_settings_get(), dfu_copy_sd(), dfu_sd_img_block_swap(), NRF_SUCCESS, bootloader_settings_t::sd_image_size, bootloader_settings_t::sd_image_start, SOFTDEVICE_INFORMATION, and SOFTDEVICE_REGION_START.
 {
     bootloader_settings_t boot_settings;
     bootloader_settings_get(&boot_settings);
     if (boot_settings.sd_image_size == 0)
     {
         return NRF_SUCCESS;
     }
     if ((SOFTDEVICE_REGION_START + boot_settings.sd_image_size) > boot_settings.sd_image_start)
     {
         uint32_t err_code;
         uint32_t sd_start        = SOFTDEVICE_REGION_START;
         uint32_t block_size      = (boot_settings.sd_image_start - sd_start) / 2;
         uint32_t image_end       = boot_settings.sd_image_start + boot_settings.sd_image_size;
         uint32_t img_block_start = boot_settings.sd_image_start + 2 * block_size;
         uint32_t sd_block_start  = sd_start + 2 * block_size;
         if (SOFTDEVICE_INFORMATION->softdevice_size < boot_settings.sd_image_size)
         {
             // This will clear a page thus ensuring the old image is invalidated before swapping.
             err_code = dfu_copy_sd((uint32_t *)(sd_start + block_size),
                                    (uint32_t *)(sd_start + block_size),
                                    sizeof(uint32_t));
             if (err_code != NRF_SUCCESS)
             {
                 return err_code;
             }
             err_code = dfu_copy_sd((uint32_t *)sd_start, (uint32_t *)sd_start, sizeof(uint32_t));
             if (err_code != NRF_SUCCESS)
             {
                 return err_code;
             }
         }
         return dfu_sd_img_block_swap((uint32_t *)img_block_start,
                                      (uint32_t *)sd_block_start,
                                      image_end - img_block_start,
                                      block_size);
     }
     else
     {
         if (boot_settings.sd_image_size != 0)
         {
             return dfu_copy_sd((uint32_t *)boot_settings.sd_image_start,
                                (uint32_t *)SOFTDEVICE_REGION_START,
                                boot_settings.sd_image_size);
         }
     }
     return NRF_SUCCESS;
 }
uint32_t dfu_init_pkt_complete (void)
Function for handling DFU init packet complete.
Returns
NRF_SUCCESS on success, an error_code otherwise.
Definition at line 511 of file dfu_dual_bank_mod.c.
References dfu_init_prevalidate(), DFU_STATE_RX_DATA_PKT, DFU_STATE_RX_INIT_PKT, IMAGE_WRITE_IN_PROGRESS, m_dfu_state, m_init_packet, m_init_packet_length, NRF_ERROR_INVALID_STATE, and NRF_SUCCESS.
 {
     uint32_t err_code = NRF_ERROR_INVALID_STATE;
     // DFU initialization has been done and a start packet has been received.
     if (IMAGE_WRITE_IN_PROGRESS())
     {
         // Image write is already in progress. Cannot handle an init packet now.
         return NRF_ERROR_INVALID_STATE;
     }
     if (m_dfu_state == DFU_STATE_RX_INIT_PKT)
     {
         err_code = dfu_init_prevalidate(m_init_packet, m_init_packet_length);
         if (err_code == NRF_SUCCESS)
         {
             m_dfu_state = DFU_STATE_RX_DATA_PKT;
         }
         else
         {
             m_init_packet_length = 0;
         }
     }
     return err_code;
 }