nRF51822 Beacon Firmware Documentation: Scheduler
Scheduler
The scheduler is used for transferring execution from the interrupt context to the main context.
Macros
#define APP_SCHED_EVENT_HEADER_SIZE 8
#define APP_SCHED_BUF_SIZE(EVENT_SIZE, QUEUE_SIZE) (((EVENT_SIZE) + APP_SCHED_EVENT_HEADER_SIZE) * ((QUEUE_SIZE) + 1))
Compute number of bytes required to hold the scheduler buffer.
#define APP_SCHED_INIT(EVENT_SIZE, QUEUE_SIZE)
Macro for initializing the event scheduler.
Typedefs
typedef void(* app_sched_event_handler_t)(void *p_event_data, uint16_t event_size)
Scheduler event handler type.
Functions
uint32_t app_sched_init (uint16_t max_event_size, uint16_t queue_size, void *p_evt_buffer)
Function for initializing the Scheduler.
void app_sched_execute (void)
Function for executing all scheduled events.
uint32_t app_sched_event_put (void *p_event_data, uint16_t event_size, app_sched_event_handler_t handler)
Function for scheduling an event.
Detailed Description
The scheduler is used for transferring execution from the interrupt context to the main context.
See seq_diagrams_sched for sequence diagrams illustrating the flow of events when using the Scheduler.
Requirements:
Logic in main context:
Define an event handler for each type of event expected.
Initialize the scheduler by calling the APP_SCHED_INIT() macro before entering the application main loop.
Call app_sched_execute() from the main loop each time the application wakes up because of an event (typically when sd_app_evt_wait() returns).
Logic in interrupt context:
In the interrupt handler, call app_sched_event_put() with the appropriate data and event handler. This will insert an event into the scheduler's queue. The app_sched_execute() function will pull this event and call its handler in the main context.
The high level design of the scheduler
Macro Definition Documentation
#define APP_SCHED_EVENT_HEADER_SIZE 8
Size of app_scheduler.event_header_t (only for use inside APP_SCHED_BUF_SIZE()).
Definition at line 56 of file app_scheduler.h.
#define APP_SCHED_BUF_SIZE (EVENT_SIZE, QUEUE_SIZE) (((EVENT_SIZE) + APP_SCHED_EVENT_HEADER_SIZE) * ((QUEUE_SIZE) + 1))
Compute number of bytes required to hold the scheduler buffer.
Parameters
[in] EVENT_SIZE Maximum size of events to be passed through the scheduler.
[in] QUEUE_SIZE Number of entries in scheduler queue (i.e. the maximum number of events that can be scheduled for execution).
Returns
Required scheduler buffer size (in bytes).
Definition at line 66 of file app_scheduler.h.
#define APP_SCHED_INIT (EVENT_SIZE, QUEUE_SIZE)
Value:
do                                                                                             \
    {                                                                                              \
        static uint32_t APP_SCHED_BUF[CEIL_DIV(APP_SCHED_BUF_SIZE((EVENT_SIZE), (QUEUE_SIZE)),     \
                                               sizeof(uint32_t))];                                 \
        uint32_t ERR_CODE = app_sched_init((EVENT_SIZE), (QUEUE_SIZE), APP_SCHED_BUF);             \
        APP_ERROR_CHECK(ERR_CODE);                                                                 \
    } while (0)
Macro for initializing the event scheduler.
It will also handle dimensioning and allocation of the memory buffer required by the scheduler, making sure the buffer is correctly aligned.
Parameters
[in] EVENT_SIZE Maximum size of events to be passed through the scheduler.
[in] QUEUE_SIZE Number of entries in scheduler queue (i.e. the maximum number of events that can be scheduled for execution).
Note
Since this macro allocates a buffer, it must only be called once (it is OK to call it several times as long as it is from the same location, e.g. to do a reinitialization).
Definition at line 84 of file app_scheduler.h.
Typedef Documentation
typedef void(* app_sched_event_handler_t)(void *p_event_data, uint16_t event_size)
Scheduler event handler type.
Definition at line 70 of file app_scheduler.h.
Function Documentation
uint32_t app_sched_init (uint16_t max_event_size, uint16_t queue_size, void * p_evt_buffer)
Function for initializing the Scheduler.
It must be called before entering the main loop.
Parameters
[in] max_event_size Maximum size of events to be passed through the scheduler.
[in] queue_size Number of entries in scheduler queue (i.e. the maximum number of events that can be scheduled for execution).
[in] p_evt_buffer Pointer to memory buffer for holding the scheduler queue. It must be dimensioned using the APP_SCHED_BUFFER_SIZE() macro. The buffer must be aligned to a 4 byte boundary.
Note
Normally initialization should be done using the APP_SCHED_INIT() macro, as that will both allocate the scheduler buffer, and also align the buffer correctly.
Return values
NRF_SUCCESS Successful initialization.
NRF_ERROR_INVALID_PARAM Invalid parameter (buffer not aligned to a 4 byte boundary).
Definition at line 57 of file app_scheduler.c.
References NRF_ERROR_INVALID_PARAM, and NRF_SUCCESS.
 {
     uint16_t data_start_index = (queue_size + 1) * sizeof(event_header_t);
     // Check that buffer is correctly aligned
     if (!is_word_aligned(p_event_buffer))
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     // Initialize event scheduler
     m_queue_event_headers = p_event_buffer;
     m_queue_event_data    = &((uint8_t *)p_event_buffer)[data_start_index];
     m_queue_end_index     = 0;
     m_queue_start_index   = 0;
     m_queue_event_size    = event_size;
     m_queue_size          = queue_size;
     return NRF_SUCCESS;
 }
void app_sched_execute (void)
Function for executing all scheduled events.
This function must be called from within the main loop. It will execute all events scheduled since the last time it was called.
Definition at line 168 of file app_scheduler.c.
References app_sched_event_get(), is_app_sched_paused(), and NRF_SUCCESS.
 {
     void                    * p_event_data;
     uint16_t                  event_data_size;
     app_sched_event_handler_t event_handler;
     // Get next event (if any), and execute handler
     while ((app_sched_event_get(&p_event_data, &event_data_size, &event_handler) == NRF_SUCCESS))
     {
         event_handler(p_event_data, event_data_size);
     }
 }
uint32_t app_sched_event_put (void * p_event_data, uint16_t event_size, app_sched_event_handler_t handler)
Function for scheduling an event.
Puts an event into the event queue.
Parameters
[in] p_event_data Pointer to event data to be scheduled.
[in] event_size Size of event data to be scheduled.
[in] handler Event handler to receive the event.
Returns
NRF_SUCCESS on success, otherwise an error code.
Definition at line 79 of file app_scheduler.c.
References APP_SCHED_QUEUE_FULL, event_header_t::event_data_size, event_header_t::handler, m_queue_end_index, next_index(), NRF_ERROR_INVALID_LENGTH, NRF_ERROR_NO_MEM, and NRF_SUCCESS.
 {
     uint32_t err_code;
     if (event_data_size <= m_queue_event_size)
     {
         uint16_t event_index = 0xFFFF;
         CRITICAL_REGION_ENTER();
         if (!APP_SCHED_QUEUE_FULL())
         {
             event_index       = m_queue_end_index;
             m_queue_end_index = next_index(m_queue_end_index);
         }
         CRITICAL_REGION_EXIT();
         if (event_index != 0xFFFF)
         {
             // NOTE: This can be done outside the critical region since the event consumer will
             //       always be called from the main loop, and will thus never interrupt this code.
             m_queue_event_headers[event_index].handler = handler;
             if ((p_event_data != NULL) && (event_data_size > 0))
             {
                 memcpy(&m_queue_event_data[event_index * m_queue_event_size],
                        p_event_data,
                        event_data_size);
                 m_queue_event_headers[event_index].event_data_size = event_data_size;
             }
             else
             {
                 m_queue_event_headers[event_index].event_data_size = 0;
             }
             err_code = NRF_SUCCESS;
         }
         else
         {
             err_code = NRF_ERROR_NO_MEM;
         }
     }
     else
     {
         err_code = NRF_ERROR_INVALID_LENGTH;
     }
     return err_code;
 }