nRF51822 Beacon Firmware Documentation: nrf51_beacon/common/led_softblink/led_softblink.c File Reference
led_softblink.c File Reference
#include <string.h>
#include "led_softblink.h"
#include "nrf_gpio.h"
#include "app_timer.h"
Data Structures
struct led_sb_context_t
Macros
#define NULL_PARAM_CHECK(PARAM)
Macro for verifying NULL parameters are not passed to API.
#define VERIFY_MODULE_INITIALIZED()
Macro for verifying module's initialization status.
#define VERIFY_MODULE_INITIALIZED_VOID()
Macro for verifying module's initialization status. Returns in case it is not initialized.
#define APP_TIMER_PRESCALER 0
#define LED_PWM_PERIOD_TICKS APP_TIMER_TICKS(20, APP_TIMER_PRESCALER)
Functions
static void led_softblink_on_timeout (void *p_context)
uint32_t led_softblink_start (uint32_t leds_pin_bit_mask)
Start blinking LED.
uint32_t led_softblink_stop (uint32_t leds_pin_bit_mask)
Stop blinking LED.
uint32_t led_softblink_off_time_set (uint32_t off_time_ms)
Set the pause time between each blink.
uint32_t led_softblink_init (led_sb_init_params_t *init_params)
LED softblink initialization.
Variables
static led_sb_context_t m_led_sb = {0}
Macro Definition Documentation
#define NULL_PARAM_CHECK (PARAM)
Value:
if ((PARAM) == NULL)                                   \
    {                                                      \
        return (NRF_ERROR_NULL); \
    }
Macro for verifying NULL parameters are not passed to API.
Parameters
[in] PARAM Parameter checked for NULL.
Return values
(NRF_ERROR_NULL | DEVICE_MANAGER_ERR_BASE) when PARAM is NULL.
Definition at line 24 of file led_softblink.c.
#define VERIFY_MODULE_INITIALIZED ()
Value:
do                                                                  \
    {                                                                   \
        if (!m_led_sb.initialized)                                      \
        {                                                               \
            return (NRF_ERROR_INVALID_STATE); \
        }                                                               \
    } while (0)
Macro for verifying module's initialization status.
Return values
(NRF_ERROR_INVALID_STATE | DEVICE_MANAGER_ERR_BASE) when module is not initialized.
Definition at line 34 of file led_softblink.c.
#define VERIFY_MODULE_INITIALIZED_VOID ()
Value:
do                                   \
    {                                    \
        if (!m_led_sb.initialized)       \
        {                                \
            return;                      \
        }                                \
    } while (0)
Macro for verifying module's initialization status. Returns in case it is not initialized.
Definition at line 45 of file led_softblink.c.
#define APP_TIMER_PRESCALER 0
Definition at line 54 of file led_softblink.c.
#define LED_PWM_PERIOD_TICKS APP_TIMER_TICKS(20, APP_TIMER_PRESCALER)
LED Softblink PWM period in app_timer ticks.
Definition at line 55 of file led_softblink.c.
Function Documentation
static void led_softblink_on_timeout (void * p_context) static
Definition at line 71 of file led_softblink.c.
References led_sb_init_params_t::active_high, APP_TIMER_PRESCALER, app_timer_start(), APP_TIMER_TICKS, led_sb_context_t::bit_mask, led_sb_context_t::duty_cycle, led_sb_init_params_t::duty_cycle_max, led_sb_init_params_t::duty_cycle_min, led_sb_init_params_t::duty_cycle_step, led_sb_context_t::is_counting_up, LED_PWM_PERIOD_TICKS, led_sb_context_t::leds_is_on, NRF_GPIO, led_sb_init_params_t::off_time_ms, led_sb_context_t::params, led_sb_context_t::timer_id, and VERIFY_MODULE_INITIALIZED_VOID.
 {
     uint32_t new_timeout_ticks;
     uint32_t err_code;
     VERIFY_MODULE_INITIALIZED_VOID();
     if (m_led_sb.leds_is_on)
     {
         // Turn off LEDs
         if (m_led_sb.params.active_high)
         {
             NRF_GPIO->OUTCLR = m_led_sb.bit_mask;
         }
         else
         {
             NRF_GPIO->OUTSET = m_led_sb.bit_mask;
         }
         m_led_sb.leds_is_on = false;
         if (m_led_sb.is_counting_up)
         {
             m_led_sb.duty_cycle += m_led_sb.params.duty_cycle_step;
             if(m_led_sb.duty_cycle >= m_led_sb.params.duty_cycle_max)
             {
                 // Max PWM duty cycle is reached, start decrementing.
                 m_led_sb.is_counting_up = false;
             }
         }
         else
         {
             m_led_sb.duty_cycle -= m_led_sb.params.duty_cycle_step;
             if(m_led_sb.duty_cycle <= m_led_sb.params.duty_cycle_min)
             {
                 // Min PWM duty cycle is reached, start incrementing.
                 m_led_sb.is_counting_up = true;
             }
         }
         if (m_led_sb.duty_cycle <= m_led_sb.params.duty_cycle_min)
         {
             new_timeout_ticks = APP_TIMER_TICKS(m_led_sb.params.off_time_ms, APP_TIMER_PRESCALER);
         }
         else
         {
             new_timeout_ticks = (LED_PWM_PERIOD_TICKS / 100) * (100 - m_led_sb.duty_cycle) + 5;
         }
     }
     else
     {
         // Turn on LEDs
         if (m_led_sb.params.active_high)
         {
             NRF_GPIO->OUTSET = m_led_sb.bit_mask;;
         }
         else
         {
             NRF_GPIO->OUTCLR = m_led_sb.bit_mask;;
         }
         m_led_sb.leds_is_on = true;
         new_timeout_ticks = (LED_PWM_PERIOD_TICKS / 100) * m_led_sb.duty_cycle + 5;
     }
     err_code = app_timer_start(m_led_sb.timer_id, new_timeout_ticks, NULL);
     APP_ERROR_CHECK(err_code);
 }
uint32_t led_softblink_start (uint32_t leds_pin_bit_mask)
Start blinking LED.
Parameters
[in] leds_pin_bit_mask Bit mask containing the pins for the leds to be started.
Returns
Return values
NRF_SUCCESS
Definition at line 141 of file led_softblink.c.
References app_timer_start(), led_sb_context_t::bit_mask, LED_PWM_PERIOD_TICKS, NRF_SUCCESS, led_sb_context_t::timer_id, led_sb_context_t::timer_running, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     m_led_sb.bit_mask |= leds_pin_bit_mask;
     if (!m_led_sb.timer_running)
     {
         uint32_t err_code;
         err_code = app_timer_start(m_led_sb.timer_id, LED_PWM_PERIOD_TICKS, NULL);
         if (err_code != NRF_SUCCESS)
         {
             return err_code;
         }
         m_led_sb.timer_running = true;
     }
     return NRF_SUCCESS;
 }
uint32_t led_softblink_stop (uint32_t leds_pin_bit_mask)
Stop blinking LED.
Parameters
[in] leds_pin_bit_mask Bit mask containing the pins for the leds to be stopped.
Returns
Return values
NRF_SUCCESS
Definition at line 163 of file led_softblink.c.
References app_timer_stop(), led_sb_context_t::bit_mask, NRF_SUCCESS, led_sb_context_t::timer_id, led_sb_context_t::timer_running, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     m_led_sb.bit_mask &= ~leds_pin_bit_mask;
     if (m_led_sb.timer_running && (m_led_sb.bit_mask == 0))
     {
         uint32_t err_code;
         err_code = app_timer_stop(m_led_sb.timer_id);
         if (err_code != NRF_SUCCESS)
         {
             return err_code;
         }
         m_led_sb.timer_running = false;
     }
     return NRF_SUCCESS;
 }
uint32_t led_softblink_off_time_set (uint32_t off_time_ms)
Set the pause time between each blink.
Parameters
[in] off_time_ms Off time in ms.
Returns
Return values
NRF_SUCCESS
Definition at line 185 of file led_softblink.c.
References NRF_SUCCESS, led_sb_init_params_t::off_time_ms, led_sb_context_t::params, and VERIFY_MODULE_INITIALIZED.
 {
     VERIFY_MODULE_INITIALIZED();
     m_led_sb.params.off_time_ms = off_time_ms;
     return NRF_SUCCESS;
 }
uint32_t led_softblink_init (led_sb_init_params_t * init_params)
LED softblink initialization.
Parameters
[in] leds_pin_bit_mask Bit mask containing the pins for the leds.
Returns
Return values
NRF_SUCCESS
Definition at line 194 of file led_softblink.c.
References led_sb_init_params_t::active_high, app_timer_create(), APP_TIMER_MODE_SINGLE_SHOT, led_sb_init_params_t::duty_cycle_max, led_sb_init_params_t::duty_cycle_min, led_sb_init_params_t::duty_cycle_step, led_sb_context_t::initialized, led_sb_context_t::is_counting_up, led_softblink_on_timeout(), led_sb_init_params_t::leds_pin_bm, NRF_ERROR_INVALID_PARAM, NRF_ERROR_INVALID_STATE, nrf_gpio_cfg_output(), nrf_gpio_pin_clear(), nrf_gpio_pin_set(), NULL_PARAM_CHECK, led_sb_context_t::params, and led_sb_context_t::timer_id.
 {
     uint32_t bit_mask;
     uint32_t pin_number = 0;
     if (m_led_sb.initialized)
     {
         return NRF_ERROR_INVALID_STATE;
     }
     NULL_PARAM_CHECK(init_params);
     if ( (init_params->duty_cycle_max == 0)                           ||
          (init_params->duty_cycle_max <= init_params->duty_cycle_min) ||
          (init_params->duty_cycle_step == 0)                          ||
          (init_params->leds_pin_bm == 0))
     {
         return NRF_ERROR_INVALID_PARAM;
     }
     memset(&m_led_sb, 0, sizeof(led_sb_context_t));
     memcpy(&m_led_sb.params, init_params, sizeof(led_sb_init_params_t));
     m_led_sb.is_counting_up = true;
     bit_mask = m_led_sb.params.leds_pin_bm;
     // Configure IO according to the leds_pin_bit_mask
     while (bit_mask)
     {
         if (bit_mask & 0x1UL)
         {
             nrf_gpio_cfg_output(pin_number);
             if (m_led_sb.params.active_high)
             {
                 nrf_gpio_pin_clear(pin_number);
             }
             else
             {
                 nrf_gpio_pin_set(pin_number);
             }
         }
         pin_number++;
         bit_mask >>= 1UL;
     }
     m_led_sb.initialized = true;
     return app_timer_create(&m_led_sb.timer_id, APP_TIMER_MODE_SINGLE_SHOT, led_softblink_on_timeout);
 }
Variable Documentation
led_sb_context_t m_led_sb = {0} static
Definition at line 69 of file led_softblink.c.