var modules =
[
    [ "main.c", "group__ble__app__beacon__main.html", "group__ble__app__beacon__main" ],
    [ "Memory Pool Internal", "group__memory__pool__internal.html", "group__memory__pool__internal" ],
    [ "main.c", "group__ble__app__bootloader__main.html", "group__ble__app__bootloader__main" ],
    [ "Beacon Configuration Service", "group__ble__sdk__srv__bcs.html", "group__ble__sdk__srv__bcs" ],
    [ "DFU BLE packet handling in Application", "group__nrf__dfu__app__handler.html", "group__nrf__dfu__app__handler" ],
    [ "API Parameters check macros.", "group__api__param__check.html", "group__api__param__check" ],
    [ "Utility internal functions.", "group__utility__functions.html", "group__utility__functions" ],
    [ "SoftDevice Event Handler", "group__softdevice__handler.html", "group__softdevice__handler" ],
    [ "BLE SoftDevice Common", "group___b_l_e___c_o_m_m_o_n.html", "group___b_l_e___c_o_m_m_o_n" ],
    [ "SoftDevice Manager API", "group__nrf__sdm__api.html", "group__nrf__sdm__api" ],
    [ "SoC Library API", "group__nrf__soc__api.html", "group__nrf__soc__api" ],
    [ "Master Boot Record API", "group__nrf__mbr__api.html", "group__nrf__mbr__api" ],
    [ "Bootloader API.", "group__nrf__bootloader.html", "group__nrf__bootloader" ],
    [ "Bootloader settings API.", "group__nrf__bootloader__settings.html", "group__nrf__bootloader__settings" ],
    [ "Bootloader util API.", "group__nrf__bootloader__util.html", "group__nrf__bootloader__util" ],
    [ "Device Firmware Update API.", "group__nrf__dfu.html", "group__nrf__dfu" ],
    [ "Device Firmware Update internal header for bank handling in DFU.", "group__dfu__bank__internal.html", "group__dfu__bank__internal" ],
    [ "DFU BLE SVC", "group__nrf__dfu__ble__svc.html", "group__nrf__dfu__ble__svc" ],
    [ "DFU BLE SVC internal", "group__nrf__dfu__ble__svc__internal.html", "group__nrf__dfu__ble__svc__internal" ],
    [ "Init packet handling in DFU.", "group__nrf__dfu__init.html", "group__nrf__dfu__init" ],
    [ "DFU transport API.", "group__nrf__dfu__transport.html", "group__nrf__dfu__transport" ],
    [ "HCI Transport Layer Configuration", "group__ble__sdk__bootloader__hci__congfig.html", "group__ble__sdk__bootloader__hci__congfig" ],
    [ "Button Handler", "group__app__button.html", "group__app__button" ],
    [ "Scheduler", "group__app__scheduler.html", "group__app__scheduler" ],
    [ "Application Timer", "group__app__timer.html", "group__app__timer" ],
    [ "Persistent Storage Interface", "group__persistent__storage.html", "group__persistent__storage" ],
    [ "AES ECB encryption", "group__nrf__ecb.html", "group__nrf__ecb" ],
    [ "GPIO abstraction", "group__nrf__gpio.html", "group__nrf__gpio" ],
    [ "GPIOTE abstraction", "group__nrf__gpiote.html", "group__nrf__gpiote" ],
    [ "Non-volatile memory controller", "group__nrf__nvmc.html", "group__nrf__nvmc" ],
    [ "TEMP (temperature) abstraction", "group__nrf__temperature.html", "group__nrf__temperature" ],
    [ "Advertising Data Encoder", "group__ble__sdk__lib__advdata.html", "group__ble__sdk__lib__advdata" ],
    [ "Connection Parameters Negotiation", "group__ble__sdk__lib__conn__params.html", "group__ble__sdk__lib__conn__params" ],
    [ "BLE Date Time characteristic type", "group__ble__sdk__srv__date__time.html", "group__ble__sdk__srv__date__time" ],
    [ "Common service definitions", "group__ble__sdk__srv__common.html", "group__ble__sdk__srv__common" ],
    [ "Device Firmware Update Service", "group__ble__sdk__srv__dfu.html", "group__ble__sdk__srv__dfu" ],
    [ "Generic Access Profile (GAP)", "group___b_l_e___g_a_p.html", "group___b_l_e___g_a_p" ],
    [ "Functions", "group___b_l_e___g_a_p___f_u_n_c_t_i_o_n_s.html", "group___b_l_e___g_a_p___f_u_n_c_t_i_o_n_s" ],
    [ "Generic Attribute Profile (GATT) Common", "group___b_l_e___g_a_t_t.html", "group___b_l_e___g_a_t_t" ],
    [ "Generic Attribute Profile (GATT) Client", "group___b_l_e___g_a_t_t_c.html", "group___b_l_e___g_a_t_t_c" ],
    [ "Generic Attribute Profile (GATT) Server", "group___b_l_e___g_a_t_t_s.html", "group___b_l_e___g_a_t_t_s" ],
    [ "Logical Link Control and Adaptation Protocol (L2CAP)", "group___b_l_e___l2_c_a_p.html", "group___b_l_e___l2_c_a_p" ],
    [ "Semiconductor", "group___nordic.html", "group___nordic" ]
];