nRF51822 Beacon Firmware Documentation: components/drivers_nrf/pstorage/pstorage.c File Reference
pstorage.c File Reference
#include "pstorage.h"
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "nordic_common.h"
#include "nrf_error.h"
#include "nrf_assert.h"
#include "nrf.h"
#include "nrf_soc.h"
#include "app_util.h"
Data Structures
struct pstorage_module_table_t
Application registration information.
struct cmd_queue_element_t
Defines command queue element.
struct cmd_queue_t
Defines command queue, an element is free if op_code field is not invalid.
Macros
#define INVALID_OPCODE 0x00
#define SOC_MAX_WRITE_SIZE 1024
#define RAW_MODE_APP_ID (PSTORAGE_MAX_APPLICATIONS + 1)
#define NULL_PARAM_CHECK(PARAM)
Check if the input pointer is NULL, if it is returns NRF_ERROR_NULL.
#define MODULE_ID_RANGE_CHECK(ID)
Verifies the module identifier supplied by the application is within permissible range.
#define BLOCK_ID_RANGE_CHECK(ID)
Verifies the block identifier supplied by the application is within the permissible range.
#define BLOCK_SIZE_CHECK(X)
Verifies the block size requested by the application can be supported by the module.
#define BLOCK_COUNT_CHECK(COUNT, SIZE)
Verifies block size requested by Application in registration API.
#define SIZE_CHECK(ID, SIZE)
Verifies size parameter provided by application in API.
#define OFFSET_CHECK(ID, OFFSET, SIZE)
Verifies offset parameter provided by application in API.
#define VERIFY_MODULE_INITIALIZED()
Verify module's initialization status.
#define MODULE_BLOCK_SIZE(ID) (m_app_table[(ID)->module_id].block_size)
Macro to fetch the block size registered for the module.
Enumerations
enum swap_backup_state_t {
STATE_INIT, STATE_DATA_TO_SWAP_WRITE, STATE_DATA_ERASE, STATE_HEAD_RESTORE,
STATE_TAIL_RESTORE, STATE_NEW_BODY_WRITE, STATE_SWAP_ERASE, STATE_COMPLETE,
STATE_SWAP_DIRTY, STATE_INIT, STATE_DATA_TO_SWAP_WRITE, STATE_DATA_ERASE,
STATE_HEAD_RESTORE, STATE_TAIL_RESTORE, STATE_NEW_BODY_WRITE, STATE_SWAP_ERASE,
STATE_COMPLETE, STATE_SWAP_DIRTY
}
States for the Update/Clear swap backup state machine.
Functions
static uint32_t cmd_process (void)
Routine called to actually issue the flash access request to the SoftDevice.
static void app_notify (uint32_t result)
Routine to notify application of any errors.
static void cmd_queue_element_init (uint32_t index)
Initializes command queue element.
static void cmd_queue_init (void)
Initializes command queue.
static uint32_t cmd_queue_enqueue (uint8_t opcode, pstorage_handle_t *p_storage_addr, uint8_t *p_data_addr, pstorage_size_t size, pstorage_size_t offset)
Routine to enqueue a flash access operation.
static uint32_t cmd_queue_dequeue (void)
Dequeues a command element.
void pstorage_sys_event_handler (uint32_t sys_evt)
Handles Flash Access Result Events declared in pstorage_platform.h.
static uint32_t swap_state_process (cmd_queue_element_t *p_cmd, uint32_t page_number, uint32_t head_word_size, uint32_t tail_word_size)
Function for handling flash accesses when using swap.
uint32_t pstorage_init (void)
Module Initialization Routine.
uint32_t pstorage_register (pstorage_module_param_t *p_module_param, pstorage_handle_t *p_block_id)
Register with persistent storage interface.
uint32_t pstorage_block_identifier_get (pstorage_handle_t *p_base_id, pstorage_size_t block_num, pstorage_handle_t *p_block_id)
Function to get block id with reference to base block identifier provided at time of registration.
uint32_t pstorage_store (pstorage_handle_t *p_dest, uint8_t *p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to persistently store data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address; Equivalent to Storage Write.
uint32_t pstorage_update (pstorage_handle_t *p_dest, uint8_t *p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to update persistently stored data of length 'size' contained in 'p_src' address in storage module at 'p_dest' address.
uint32_t pstorage_load (uint8_t *p_dest, pstorage_handle_t *p_src, pstorage_size_t size, pstorage_size_t offset)
Routine to load persistently stored data of length 'size' from 'p_src' address to 'p_dest' address; Equivalent to Storage Read.
uint32_t pstorage_clear (pstorage_handle_t *p_dest, pstorage_size_t size)
Routine to clear data in persistent memory.
uint32_t pstorage_access_status_get (uint32_t *p_count)
API to get status of number of pending operations with the module.
Variables
static cmd_queue_t m_cmd_queue
static pstorage_size_t m_next_app_instance
static uint32_t m_next_page_addr
static pstorage_size_t m_round_val
static bool m_module_initialized = false
static swap_backup_state_t m_swap_state
static pstorage_module_table_t m_app_table [PSTORAGE_MAX_APPLICATIONS]
Macro Definition Documentation
#define INVALID_OPCODE 0x00
Invalid op code identifier.
Definition at line 24 of file pstorage.c.
#define SOC_MAX_WRITE_SIZE 1024
Maximum write size allowed for a single call to sd_flash_write as specified in the SoC API.
Definition at line 25 of file pstorage.c.
#define RAW_MODE_APP_ID (PSTORAGE_MAX_APPLICATIONS + 1)
Application id for raw mode.
Definition at line 26 of file pstorage.c.
#define VERIFY_MODULE_INITIALIZED ()
Value:
do                                                                                        \
        {                                                                                         \
            if (!m_module_initialized)                                                            \
            {                                                                                     \
                 return NRF_ERROR_INVALID_STATE;                                                  \
            }                                                                                     \
        } while(0)
Verify module's initialization status.
Verify module's initialization status. Returns NRF_ERROR_INVALID_STATE in case a module API is called without initializing the module.
Definition at line 128 of file pstorage.c.
#define MODULE_BLOCK_SIZE (ID) (m_app_table[(ID)->module_id].block_size)
Macro to fetch the block size registered for the module.
Definition at line 138 of file pstorage.c.
Enumeration Type Documentation
enum swap_backup_state_t
States for the Update/Clear swap backup state machine.
Enumerator
STATE_INIT
State for indicating that swap can be used when using update/clear API.
STATE_DATA_TO_SWAP_WRITE
State for doing backup of data page into the swap page when using update/clear API.
STATE_DATA_ERASE
State for erasing data page when using update/clear API.
STATE_HEAD_RESTORE
State for restoring head (beginning) of backed up data from swap to data page when using update/clear API.
STATE_TAIL_RESTORE
State for restoring tail (end) of backed up data from swap to data page when using update/clear API.
STATE_NEW_BODY_WRITE
State for writing body (middle) data to the data page when using update/clear API.
STATE_SWAP_ERASE
State for erasing the swap page when using the update/clear API.
STATE_COMPLETE
State for indicating that update/clear sequence is completed internal in the module when using the update/clear API.
STATE_SWAP_DIRTY
State for initializing the swap region on module initialization.
STATE_INIT
State for indicating that swap can be used when using update/clear API.
STATE_DATA_TO_SWAP_WRITE
State for doing backup of data page into the swap page when using update/clear API.
STATE_DATA_ERASE
State for erasing data page when using update/clear API.
STATE_HEAD_RESTORE
State for restoring head (beginning) of backed up data from swap to data page when using update/clear API.
STATE_TAIL_RESTORE
State for restoring tail (end) of backed up data from swap to data page when using update/clear API.
STATE_NEW_BODY_WRITE
State for writing body (middle) data to the data page when using update/clear API.
STATE_SWAP_ERASE
State for erasing the swap page when using the update/clear API.
STATE_COMPLETE
State for indicating that update/clear sequence is completed internal in the module when using the update/clear API.
STATE_SWAP_DIRTY
State for initializing the swap region on module initialization.
Definition at line 142 of file pstorage.c.
 {
     STATE_INIT,
     STATE_DATA_TO_SWAP_WRITE,
     STATE_DATA_ERASE,
     STATE_HEAD_RESTORE,
     STATE_TAIL_RESTORE,
     STATE_NEW_BODY_WRITE,
     STATE_SWAP_ERASE,
     STATE_COMPLETE,
     STATE_SWAP_DIRTY
 } swap_backup_state_t;
Function Documentation
static uint32_t cmd_process (void) static
Routine called to actually issue the flash access request to the SoftDevice.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
Definition at line 699 of file pstorage.c.
References pstorage_module_table_t::base_id, pstorage_module_table_t::block_count, pstorage_module_table_t::block_size, cmd_queue_t::cmd, cmd_queue_t::flash_access, m_round_val, NRF_ERROR_FORBIDDEN, NRF_SUCCESS, cmd_queue_element_t::offset, cmd_queue_element_t::op_code, cmd_queue_element_t::p_data_addr, PSTORAGE_CLEAR_OP_CODE, PSTORAGE_STORE_OP_CODE, PSTORAGE_UPDATE_OP_CODE, RAW_MODE_APP_ID, cmd_queue_t::rp, cmd_queue_element_t::size, SOC_MAX_WRITE_SIZE, cmd_queue_element_t::storage_addr, and swap_state_process().
 {
     uint32_t              retval;
     uint32_t              storage_addr;
     cmd_queue_element_t * p_cmd;
     retval = NRF_ERROR_FORBIDDEN;
     p_cmd = &m_cmd_queue.cmd[m_cmd_queue.rp];
     storage_addr = p_cmd->storage_addr.block_id;
     switch (p_cmd->op_code)
     {
         case PSTORAGE_STORE_OP_CODE:
         {
             uint32_t  size;
             uint32_t  offset;
             uint8_t * p_data_addr = p_cmd->p_data_addr;
             offset        = (m_round_val * SOC_MAX_WRITE_SIZE);
             size          = p_cmd->size - offset;
             p_data_addr  += offset;
             storage_addr += (p_cmd->offset + offset);
             if (size < SOC_MAX_WRITE_SIZE)
             {
                 retval = sd_flash_write(((uint32_t *)storage_addr),
                                         (uint32_t *)p_data_addr,
                                         size / sizeof(uint32_t));
             }
             else
             {
                 retval = sd_flash_write(((uint32_t *)storage_addr),
                                         (uint32_t *)p_data_addr,
                                         SOC_MAX_WRITE_SIZE / sizeof(uint32_t));
             }
         }
         break;
         case PSTORAGE_CLEAR_OP_CODE:
         {
             // Calculate page number before clearing.
             uint32_t page_number;
             pstorage_size_t block_size =
                 m_app_table[p_cmd->storage_addr.module_id].block_size;
             pstorage_size_t block_count =
                 m_app_table[p_cmd->storage_addr.module_id].block_count;
             pstorage_block_t base_address =
                 m_app_table[p_cmd->storage_addr.module_id].base_id;
             // If the whole module should be cleared.
             if (((base_address == storage_addr) && (block_size * block_count == p_cmd->size)) ||
                 (p_cmd->storage_addr.module_id == RAW_MODE_APP_ID))
             {
                 page_number = ((storage_addr / PSTORAGE_FLASH_PAGE_SIZE) + m_round_val);
                 retval = sd_flash_page_erase(page_number);
             }
             // If one block is to be erased.
             else
             {
                 page_number = (storage_addr / PSTORAGE_FLASH_PAGE_SIZE);
                 uint32_t head_word_size = (
                     storage_addr -
                     (page_number * PSTORAGE_FLASH_PAGE_SIZE)
                     ) / sizeof(uint32_t);
                 uint32_t tail_word_size = (
                     ((page_number + 1) * PSTORAGE_FLASH_PAGE_SIZE) -
                     (storage_addr + p_cmd->size)
                     ) / sizeof(uint32_t);
                 retval = swap_state_process(p_cmd,
                                             page_number,
                                             head_word_size,
                                             tail_word_size);
             }
         }
         break;
         case PSTORAGE_UPDATE_OP_CODE:
         {
             uint32_t page_number = (storage_addr / PSTORAGE_FLASH_PAGE_SIZE);
             uint32_t head_word_size = (
                 storage_addr + p_cmd->offset -
                 (page_number * PSTORAGE_FLASH_PAGE_SIZE)
                 ) / sizeof(uint32_t);
             uint32_t tail_word_size = (
                 ((page_number + 1) * PSTORAGE_FLASH_PAGE_SIZE) -
                 (storage_addr + p_cmd->offset + p_cmd->size)
                 ) / sizeof(uint32_t);
             retval = swap_state_process(p_cmd, page_number, head_word_size, tail_word_size);
         }
         break;
         default:
             // Should never reach here.
             break;
     }
     if (retval == NRF_SUCCESS)
     {
         m_cmd_queue.flash_access = true;
     }
     return retval;
 }
static void cmd_queue_element_init (uint32_t index) static
Initializes command queue element.
Parameters
[in] index Element index being initialized.
Definition at line 267 of file pstorage.c.
References cmd_queue_t::cmd, INVALID_OPCODE, cmd_queue_element_t::offset, cmd_queue_element_t::op_code, cmd_queue_element_t::p_data_addr, cmd_queue_element_t::size, and cmd_queue_element_t::storage_addr.
 {
     // Internal function and checks on range of index can be avoided.
     m_cmd_queue.cmd[index].op_code                = INVALID_OPCODE;
     m_cmd_queue.cmd[index].size                   = 0;
     m_cmd_queue.cmd[index].storage_addr.module_id = PSTORAGE_MAX_APPLICATIONS;
     m_cmd_queue.cmd[index].storage_addr.block_id  = 0;
     m_cmd_queue.cmd[index].p_data_addr            = NULL;
     m_cmd_queue.cmd[index].offset                 = 0;
 }
static void cmd_queue_init (void) static
Initializes command queue.
Definition at line 282 of file pstorage.c.
References cmd_queue_element_init(), cmd_queue_t::count, cmd_queue_t::flash_access, m_round_val, m_swap_state, cmd_queue_t::rp, and STATE_INIT.
 {
     uint32_t cmd_index;
     m_round_val              = 0;
     m_swap_state             = STATE_INIT;
     m_cmd_queue.rp           = 0;
     m_cmd_queue.count        = 0;
     m_cmd_queue.flash_access = false;
     for (cmd_index = 0; cmd_index < PSTORAGE_CMD_QUEUE_SIZE; cmd_index++)
     {
         cmd_queue_element_init(cmd_index);
     }
 }
static uint32_t cmd_queue_enqueue (uint8_t opcode, pstorage_handle_t * p_storage_addr, uint8_t * p_data_addr, pstorage_size_t size, pstorage_size_t offset) static
Routine to enqueue a flash access operation.
Parameters
[in] opcode Identifies operation requested to be enqueued.
[in] p_storage_addr Identiifes module and flash address on which operation is requested.
[in] p_data_addr Identifies data address for flash access.
[in] size Size in bytes of data requested for the access operation.
[in] offset Offset within the flash memory block at which operation is requested.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
Note
All paramater check should be performed before requesting in an enqueue.
Definition at line 312 of file pstorage.c.
References cmd_queue_t::cmd, cmd_process(), cmd_queue_t::count, cmd_queue_t::flash_access, NRF_ERROR_BUSY, NRF_ERROR_NO_MEM, NRF_SUCCESS, cmd_queue_element_t::offset, cmd_queue_element_t::op_code, cmd_queue_element_t::p_data_addr, cmd_queue_t::rp, cmd_queue_element_t::size, and cmd_queue_element_t::storage_addr.
 {
     uint32_t retval;
     uint8_t  write_index = 0;
     if (m_cmd_queue.count != PSTORAGE_CMD_QUEUE_SIZE)
     {
         // Enqueue the command if it is queue is not full.
         write_index = m_cmd_queue.rp + m_cmd_queue.count;
         if (write_index >= PSTORAGE_CMD_QUEUE_SIZE)
         {
             write_index -= PSTORAGE_CMD_QUEUE_SIZE;
         }
         m_cmd_queue.cmd[write_index].op_code      = opcode;
         m_cmd_queue.cmd[write_index].p_data_addr  = p_data_addr;
         m_cmd_queue.cmd[write_index].storage_addr = (*p_storage_addr);
         m_cmd_queue.cmd[write_index].size         = size;
         m_cmd_queue.cmd[write_index].offset       = offset;
         retval                                    = NRF_SUCCESS;
         if (m_cmd_queue.flash_access == false)
         {
             retval = cmd_process();
             if (retval == NRF_ERROR_BUSY)
             {
                 // In case of busy error code, it is possible to attempt to access flash.
                 retval = NRF_SUCCESS;
             }
         }
         m_cmd_queue.count++;
     }
     else
     {
         retval = NRF_ERROR_NO_MEM;
     }
     return retval;
 }
static uint32_t cmd_queue_dequeue (void) static
Dequeues a command element.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
Definition at line 362 of file pstorage.c.
References cmd_process(), cmd_queue_t::count, NRF_ERROR_BUSY, and NRF_SUCCESS.
 {
     uint32_t retval;
     retval = NRF_SUCCESS;
     // If any flash operation is enqueued, schedule.
     if (m_cmd_queue.count > 0)
     {
         retval = cmd_process();
         if (retval != NRF_SUCCESS)
         {
             // Flash could be accessed by modules other than Bond Manager, hence a busy error is
             // acceptable, but any other error needs to be indicated to the bond manager.
             if (retval == NRF_ERROR_BUSY)
             {
                 // In case of busy error code, it is possible to attempt to access flash.
                 retval = NRF_SUCCESS;
             }
         }
     }
     else
     {
         // No flash access request pending.
     }
     return retval;
 }
static uint32_t swap_state_process (cmd_queue_element_t * p_cmd, uint32_t page_number, uint32_t head_word_size, uint32_t tail_word_size) static
Function for handling flash accesses when using swap.
| Page | |________________________________________________________| | head | affected body (to be updated or cleared) | tail | |______|__________________________________________|______|
Parameters
[in] p_cmd Queue element being processed.
[in] page_number The affected page number.
[in] head_word_size Size of the head in number of words.
[in] tail_word_size Size of the tail in number of words.
Return values
NRF_SUCCESS on success, else an error code indicating reason for failure.
Definition at line 545 of file pstorage.c.
References m_swap_state, NRF_ERROR_INTERNAL, NRF_SUCCESS, cmd_queue_element_t::op_code, cmd_queue_element_t::p_data_addr, PSTORAGE_CLEAR_OP_CODE, cmd_queue_element_t::size, STATE_COMPLETE, STATE_DATA_ERASE, STATE_DATA_TO_SWAP_WRITE, STATE_HEAD_RESTORE, STATE_INIT, STATE_NEW_BODY_WRITE, STATE_SWAP_ERASE, and STATE_TAIL_RESTORE.
 {
     uint32_t retval = NRF_ERROR_INTERNAL;
     // Adjust entry point to state machine if needed. When we update has no head or tail its
     // no need for using the swap.
     if (m_swap_state == STATE_INIT)
     {
         if ((head_word_size == 0) && (tail_word_size == 0))
         {
             // Only skip swap usage if the new data fills a whole flash page.
             m_swap_state = STATE_DATA_ERASE;
         }
         else
         {
             // Else start backing up application data to swap.
             m_swap_state = STATE_DATA_TO_SWAP_WRITE;
         }
     }
     switch (m_swap_state)
     {
         case STATE_DATA_TO_SWAP_WRITE:
             // Backup previous content into swap page.
             retval = sd_flash_write((uint32_t *)(PSTORAGE_SWAP_ADDR),
                                     (uint32_t *)(page_number * PSTORAGE_FLASH_PAGE_SIZE),
                                     PSTORAGE_FLASH_PAGE_SIZE / sizeof(uint32_t));
             if (retval == NRF_SUCCESS)
             {
                 m_swap_state = STATE_DATA_ERASE;
             }
             break;
         case STATE_DATA_ERASE:
             // Clear the application data page.
             retval = sd_flash_page_erase(page_number);
             if (retval == NRF_SUCCESS)
             {
                 if (head_word_size == 0)
                 {
                     if (tail_word_size == 0)
                     {
                         if (p_cmd->op_code == PSTORAGE_CLEAR_OP_CODE)
{
                             m_swap_state = STATE_COMPLETE;
                         }
                         else
{
                             m_swap_state = STATE_NEW_BODY_WRITE;
                         }
                     }
                     else
                     {
                         m_swap_state = STATE_TAIL_RESTORE;
                     }
                 }
                 else
                 {
                     m_swap_state = STATE_HEAD_RESTORE;
                 }
             }
             break;
         case STATE_HEAD_RESTORE:
             // Restore head from swap to application data page.
             retval = sd_flash_write((uint32_t *)(page_number * PSTORAGE_FLASH_PAGE_SIZE),
                                     (uint32_t *)PSTORAGE_SWAP_ADDR,
                                     head_word_size);
             if (retval == NRF_SUCCESS)
             {
                 if (tail_word_size == 0)
                 {
                     if (p_cmd->op_code == PSTORAGE_CLEAR_OP_CODE)
                     {
                         m_swap_state = STATE_SWAP_ERASE;
                     }
                     else
                     {
                         m_swap_state = STATE_NEW_BODY_WRITE;
                     }
                 }
                 else
                 {
                     m_swap_state = STATE_TAIL_RESTORE;
                 }
             }
             break;
         case STATE_TAIL_RESTORE:
             // Restore tail from swap to application data page.
             retval = sd_flash_write((uint32_t *)((page_number * PSTORAGE_FLASH_PAGE_SIZE) +
                                                  (head_word_size * sizeof(uint32_t)) +
                                                  p_cmd->size),
                                     (uint32_t *)(PSTORAGE_SWAP_ADDR +
                                                  (head_word_size * sizeof(uint32_t)) +
                                                  p_cmd->size),
                                     tail_word_size);
             if (retval == NRF_SUCCESS)
             {
                 if (p_cmd->op_code == PSTORAGE_CLEAR_OP_CODE)
                 {
                     m_swap_state = STATE_SWAP_ERASE;
                 }
                 else
                 {
                     m_swap_state = STATE_NEW_BODY_WRITE;
                 }
             }
             break;
         case STATE_NEW_BODY_WRITE:
             // Write new data (body) to application data page.
             retval = sd_flash_write((uint32_t *)((page_number * PSTORAGE_FLASH_PAGE_SIZE) +
                                                  (head_word_size * sizeof(uint32_t))),
                                     (uint32_t *)p_cmd->p_data_addr,
                                     p_cmd->size / sizeof(uint32_t));
             if (retval == NRF_SUCCESS)
             {
                 if ((head_word_size == 0) && (tail_word_size == 0))
                 {
                     m_swap_state = STATE_COMPLETE;
                 }
                 else
                 {
                     m_swap_state = STATE_SWAP_ERASE;
                 }
             }
             break;
         case STATE_SWAP_ERASE:
             // Clear the swap page for subsequent use.
             retval = sd_flash_page_erase(PSTORAGE_SWAP_ADDR / PSTORAGE_FLASH_PAGE_SIZE);
             if (retval == NRF_SUCCESS)
             {
                 m_swap_state = STATE_COMPLETE;
             }
             break;
         default:
             break;
     }
     return retval;
 }
Variable Documentation
cmd_queue_t m_cmd_queue static
Flash operation request queue.
Definition at line 220 of file pstorage.c.
pstorage_size_t m_next_app_instance static
Points to the application module instance that can be allocated next.
Definition at line 221 of file pstorage.c.
uint32_t m_next_page_addr static
Points to the flash address that can be allocated to a module next, this is needed as blocks of a module can span across flash pages.
Definition at line 222 of file pstorage.c.
pstorage_size_t m_round_val static
Round value for multiple round operations. For erase operations, the round value will contain current round counter which is identical to number of pages erased. For store operations, the round value contains current round of operation * SOC_MAX_WRITE_SIZE to ensure each store to the SoC Flash API is within the SoC limit.
Definition at line 223 of file pstorage.c.
bool m_module_initialized = false static
Flag for checking if module has been initialized.
Definition at line 224 of file pstorage.c.
swap_backup_state_t m_swap_state static
Swap page state.
Definition at line 225 of file pstorage.c.
pstorage_module_table_t m_app_table[PSTORAGE_MAX_APPLICATIONS] static
Registered application information table.
Definition at line 228 of file pstorage.c.